### DISCUSSION TITLE
Migration from SNMP node.js to SNMP go.d

### DISCUSSION THREAD

**Discussion by nikobearrr** [netdata/netdata#13971] [Q&A]
I am doing some tests where I migrate my existing snmp node.js config to go.d

Here is my simple case. I have a switch which I fetch the uptime for:

node.js:
```
{
  "enable_autodetect": false,
  "max_request_size": 100,
  "servers": [
    {
      "charts": {
        "snmp.switch.switch1.uptime": {
          "dimensions": {
            "uptime": {
              "algorithm": "absolute",
              "divisor": 100,
              "multiplier": 1,
              "offset": 0,
              "oid": ".1.3.6.1.2.1.1.3.0"
            }
          },
          "family": "switch1",
          "priority": 1000,
          "title": "uptime",
          "type": "line",
          "units": "seconds"
        }
      },
      "community": "public",
      "hostname": "switch1",
      "max_request_size": 50,
      "options": {
        "timeout": 10000
      },
      "update_every": 10
    }
  ]
}
```

snmp go.d:

```
update_every: 10
autodetection_retry: 0
priority: 70000
jobs:
  - name: switch1
    update_every: 10
    hostname: "switch1"
    charts:
      - id: "uptime"
        units: "seconds"
        type: "line"
        dimensions:
          - name: "uptime"
            oid: "1.3.6.1.2.1.1.3.0"
            algorithm: "absolute"
            divisor: 100
```

both of those configs produce the same chart and both look correct.

I am exporting those metrics to a TSDB so I would like to keep the same naming schema so I can keep using the same metrics.

However, there is a small difference between the name(?) of the charts.

For the node.js version it produces `uptime (snmp.switch.switch1.uptime)` and metrics are send as `netdata.xxx.snmp.switch.switch1.uptime`
However, for the go.d version, it is produced as `uptime (snmp_switch1.uptime)` and the metrics are coming as `netdata.xxx.snmp_switch1.uptime`

Is there a way I can achieve the migration without having to re-do all my graphs and dashboards as well as keep historical data?
