### DISCUSSION TITLE
Make customizing chart context information simpler, consistent and collaborative

### DISCUSSION THREAD

**Discussion by shyamvalsan** [netdata/netdata#14107] [Ideas]
## Objective

When creating a new collector or editing an existing one, I should be able to specify the below details per chart context in a single code location in a consistent, simple manner

1.    Information regarding the context that helps the user understand what the chart is and why to use it and any other helpful information that aids their troubleshooting journey
2.    Default `group-by` the chart should use
3.    Whether to use `AVG, SUM, MIN or MAX `by default
4.    What dimensions to use for this chart by default
5.    Default Aggregation function over time 
6.    Default Chart type
7.    Filter by condition
8.    Dimension sort order

![image](https://user-images.githubusercontent.com/24860547/206413563-f6a14a47-8e80-485f-8172-cc090c740a5e.png)

I should also be able to define what charts show up in the summary dashboard for a collector, and in what form and what order these charts should be visualized.

## Problem(s)

1. On Netdata cloud to edit the context information (1) I need to edit [`contexts.js `](https://github.com/netdata/cloud-frontend/blob/develop/src/domains/charts/toc/contexts.js)file in the `netdata/cloud-frontend` repo (This is a private repo and this file cannot be edited by the community)
    - On the local agent dashboard there is a separate file (this time in `netdata/netdata` repo) I need to edit called [`dashboard_info.js`](https://github.com/netdata/netdata/blob/master/web/gui/dashboard_info.js) but changes done here will have to be manually ported over to the previously mentioned  [`contexts.js`](https://github.com/netdata/cloud-frontend/blob/develop/src/domains/charts/toc/contexts.js) file in the netdata/cloud-frontend repo
    - This makes editing metric information cumbersome, time consuming and not very collaborative, not to mention having to edit frontend javascript code everytime I want to change something is not ideal.

2. The other details such as default group-by, aggregation function etc. cannot currently be modified by someone working on the collector. 
    - For the few charts where this is done (For eg. Postgres charts which are` group by database` by default) it is hardcoded in the `cloud-frontend` private repo by the FE team

3. To create summary dashboards for a collector (section) I need to edit the same [`contexts.js `](https://github.com/netdata/cloud-frontend/blob/develop/src/domains/charts/toc/contexts.js)file in the private `netdata/cloud-frontend` repo (Hence cannot be edited by the community, changes not propagated automatically to local dashboard etc.)

## Idea

- Create a YAML file, `contexts.yaml`,  in the `netdata/netdata-cloud` public repo which is accessible to community
- Define a YAML definition format that defines all of the above details per chart 

```
context:
  description: <mandatory field, markdown supported>
  group-by: <optional field, default is group-by dimension>
  apply: <optional field, default is AVG, options are AVG|SUM|MIN|MAX>
  dimensions: <optional field, default is all>
  aggregation: <optional field, default is AVG>
  filter-by: <optional field, default is NULL>
  dims-sort-order: <optional field, default is alphabetical, options are ascending|descending|alphabetical>
  chart-type: <optional field, default is line, options are line|area|stacked - and any chart types we support in future> 
```

Here's a short example

```
redis.ping_latency:
  description: "The average time it takes from a client request to the server response. High latency could be caused slow commands, over utilized network links or a high backlog in the command queue."

```

And a more verbose example
```
postgres.db_cache_io_ratio:
  description: "PostgreSQL uses a shared buffer cache to store frequently accessesed data in memory, and avoid slower disk reads. If you are seeing performance issues, consider increasing the [shared_buffers](https://www.postgresql.org/docs/current/runtime-config-resource.html#GUC-SHARED-BUFFERS) size or tuning [effective_cache_size](https://www.postgresql.org/docs/current/runtime-config-query.html#GUC-EFFECTIVE-CACHE-SIZE)"
  group-by: database
  apply: AVG
  dimensions: All
  aggregation: AVG
  chart-type: stacked
```

- Create a YAML file, `summary.yaml`, dedicated to summary dashboards with a YAML definition per collector

```
collector.summary:
  section: <optional field, text>
    row: <optional field, number>
       collector.metric: 
            chart-type: <mandatory, options are gauge|pie|number and any summary chart types we support in future>
            title: <mandatory> 
            units: <mandatory>
       textbox: <optional, supports markdown>
```

The `section` , `row` , `textbox` fields are for future proofing, we do not support these in Netdata today. But to do full page useful summary dashboards per section we need these three fields. 
- `section` defines a header where charts can be grouped together, 
- `row` defines how many rows there are per section and how many charts per row. 
- `textbox` allows us to create a helpful info box with hyperlinks or any other text.

An example: 

```
redis.summary:
       redis.ping_latency: 
            chart-type: pie
            title: "Latency"
            units: "ms"
       redis.commands:
            chart-type: pie
            title: "Commands"
            units: "Commands"
       redis.keyspace_lookup_hitrate:
            chart-type: gauge
            title: "Lookup Hitrate"
            units: "percentage"
       redis.mem_fragmentation_ratio:
            chart-type: gauge
            title: "Memory Fragmentation Ratio"
            units: "percentage"
       redis.uptime:
            chart-type: number
            title: "Uptime"
            units: "Seconds"
```

 - Any changes to these YAML file will need to be approved by the maintainers, there should also be a test that auto-checks syntax for every PR
- `netdata/cloud-frontend` will always pull the latest version of the YAML when doing a build and use it to auto-generate the `contexts.js` file

This will ensure that the problems mentioned above are solved, and there's a simple, consistent and collaborative way to do this.

**Comment by shyamvalsan** [comment]
@netdata/product @ktsaou @cakrit @amalkov @ralphm @ilyam8 @novykh 

Please share your thoughts/feedback on the above proposal. Do you see any problems or issues in this approach?

**Reply by ilyam8** [reply]
> redis.summary:

Should be a list, not a dictionary. There are cases when you want to create N gauges using the same metric - e.g. Net Inbound/Outbound gauges. A lot of them.

**Comment by andrewm4894** [comment]
@shyamvalsan how about if you start be extending the existing metadata to what we might want to have. 

eg what would we need to add here: https://london.my-netdata.io/api/v1/chart?chart=system.cpu

```javascript
		{
			"id": "system.cpu",
			"name": "system.cpu",
			"type": "system",
			"family": "cpu",
			"context": "system.cpu",
			"title": "Total CPU utilization (system.cpu)",
			"priority": 100,
			"plugin": "proc.plugin",
			"module": "/proc/stat",
			"units": "percentage",
			"data_url": "/api/v1/data?chart=system.cpu",
			"chart_type": "stacked",
			"duration": 138995,
			"first_entry": 1670364870,
			"last_entry": 1670503864,
			"update_every": 1,
			"dimensions": {
				"guest_nice": { "name": "guest_nice" },
				"guest": { "name": "guest" },
				"steal": { "name": "steal" },
				"softirq": { "name": "softirq" },
				"irq": { "name": "irq" },
				"user": { "name": "user" },
				"system": { "name": "system" },
				"nice": { "name": "nice" },
				"iowait": { "name": "iowait" }
			},
			"chart_variables": {
			},
			"green": null,
			"red": null,
			"alarms": {
				"20min_steal_cpu": {
					"id": 1650007870,
					"status": "CLEAR",
					"units": "%",
					"update_every": 300
				},
				"10min_cpu_iowait": {
					"id": 1650007869,
					"status": "CLEAR",
					"units": "%",
					"update_every": 60
				},
				"10min_cpu_usage": {
					"id": 1650007868,
					"status": "CLEAR",
					"units": "%",
					"update_every": 60
				}
			},
			"chart_labels": {
				"_collect_plugin":"proc.plugin",
				"_collect_module":"/proc/stat",
				"_instance_family":"cpu"
			}

		}
```

Then we would have a sort of end state goal that building on something we already have. 

And then from there we could try work backwards to see how we might then centrally define such a global master /charts type lookup in yaml somewhere central.

I think if we can introduce as little new terms like `section`, `row` etc like above as possible we should. 

I think all we really need is to extend whats in the chart json above in a few ways - like you are suggesting and then just define it globally in one place and move to that then being the central source of truth for it all.

**Reply by shyamvalsan** [reply]
One part of this is that a user, who sees a particular chart and based on their subject matter expertise recognizes that either the "info" or "group-by" or "aggregation" should be different, should be able to easily - with minimal effort - open a PR for this. YAML is easier to grok than code (especially if our collector code is going to be primarily Go based, and the user is not a Go-dev).

How easy would it be for such a user to update our existing metadata format?

The other part is regarding the summary dashboard - I agree we should minimize new terms but we need some level of flexibility as well. Need to find right balance. It's debatable whether the summary dashboard definition needs to live in standard metadata or it can be its own thing.

**Reply by sashwathn** [reply]
> One part of this is that a user, who sees a particular chart and based on their subject matter expertise recognizes that either the "info" or "group-by" or "aggregation" should be different, should be able to easily - with minimal effort - open a PR for this. YAML is easier to grok than code (especially if our collector code is going to be primarily Go based, and the user is not a Go-dev).

@shyamvalsan : I am not sure if this should be a global setting based on "one" user recommendation?
I am not sure if we can allow the user to change / modify the parameters mentioned above just for their spaces without the need for a PR? So basically 2 user journeys here:

- For Netdata team / users to request a change in the chart default rendering and to be done on the netdata-cloud repo.
- For each Netdata user to modify their visualisation and is only applicable to their spaces - @amalkov and @cakrit @hugovalente-pm : Has this ever been a consideration in the past?

And the above considerations to be made for each chart as well as the summary dashboards.

**Reply by shyamvalsan** [reply]
This is not per space, it's for Netdata as a whole. The YAML is a centralized file, only one copy of it in production. 

So there's really only 1 user journey:
- For Netdata team / users to request a change in the chart default rendering and to be done on the netdata-cloud repo.

I don't think we need to be as flexible as to do this per space at this moment. Lots of bigger fish to fry :)

**Comment by andrewm4894** [comment]
@shyamvalsan can you make the full yaml for the `system.cpu` chart as an example?

**Reply by andrewm4894** [reply]
the redis stuff above is a little confusing to me as im not sure if i actually see any dims in it?

**Reply by andrewm4894** [reply]
i also wonder if we should maybe just drop all down straight to the metric level and then have a separate place that defines a chart as a collection of metrics.

**Reply by andrewm4894** [reply]
this below seems to mix chart and metric stuff:

```yaml
collector.summary:
  section: <optional field, text>
    row: <optional field, number>
       collector.metric: 
            chart-type: <mandatory, options are gauge|pie|number and any summary chart types we support in future>
            title: <mandatory> 
            units: <mandatory>
       textbox: <optional, supports markdown>
```

**Reply by andrewm4894** [reply]
think will be easier (as much as possible) to just define all metrics separate and then charts separate and just use the metric key's in them

eg can we not have equivalent to a spreadsheet - one row per metric, a col for each metadata of importance - could something like that work (not suggesting a spreadsheet - just to help us conceptualize if we could make one row per metric work).

**Reply by shyamvalsan** [reply]
This is primarily about charts, yes. Me mentioning the word "`metric`" might have added some confusion here.

I took my cue from `contexts.js` and `dashboard_info.js` - the redis example (and others) are basically a straight map to what's in js files today.

So I guess I am suggesting something similar to what you are suggesting :) metric metadata can remain in the place where it is today and have a separate place to define chart properties.

**Reply by shyamvalsan** [reply]
I made some updates above to reflect that we're talking about contexts and charts.

**Comment by hugovalente-pm** [comment]
agreed with all said so far, the centralized place to keep chart properties definitions per context summary sections, default options, etc. makes total sense.

> For each Netdata user to modify their visualisation and is only applicable to their spaces - @amalkov and @cakrit @hugovalente-pm : Has this ever been a consideration in the past?

I think this has come in the past, to allow definitions per Space / War Room / User to be used on the Overview but we focused first on providing this on the custom dashboards first.
We wil need to revisit this and brainstorm more on this to agree on what makes sense, because there are multiple possibilities around this.

**Comment by shyamvalsan** [comment]
I think we should also consider the TOC sections here - I've updated the YAML description to include. 

`  toc-section: <optioal field, decides which sub-section under the context section in toc this chart should be dispalyed>`

**Reply by hugovalente-pm** [reply]
on this one I'm not so sure... the goal is for this stuff to be driven from the context itself and OpenTelemetry standards https://github.com/netdata/netdata-cloud/issues/354 and having two things commanding the creation on the TOC seems to lead to a possible big mess

I think you're probably mentioning this because of this https://github.com/netdata/netdata-cloud/issues/550, I would probably keep the TOC creation as it is and allow the definition of a chart label to be used as a group by/breakdown to create further sub-sections on the TOC. that would probably deliver what is on [#550](https://github.com/netdata/netdata-cloud/issues/550)

**Reply by shyamvalsan** [reply]
Fair point @hugovalente-pm 

But the question is should collector really be the only place we can modify the sections a chart shows up in. For example, if a user who's an SME wants to propose a new section or ordering, is collector code the best place for it?

**Reply by hugovalente-pm** [reply]
in a situation like that, it would probably mean our naming of the metric is not the most appropriate, so I think we should really review it from the collector. 
the concern is that with the naming of the metric there are also labels associated with it, based on the context it has, that could be driving more things. not sure allowing another approach to tweak its positioning wouldn't cause other issues

@ilyam8 is into this in more depth so he can probably share his view

**Reply by shyamvalsan** [reply]
I'm removing` toc-section` from the proposal for now.

**Reply by hugovalente-pm** [reply]
I still think this would probably be valuable:
> allow the definition of a chart label to be used as a group by/breakdown to create further sub-sections on the TOC. that would probably deliver what is on https://github.com/netdata/netdata-cloud/issues/550

here we would be just using the available metadata associated with the context to allow a further breakdown on TOC sub-sections

**Comment by shyamvalsan** [comment]
Feedback from call with @cakrit @sashwathn @amalkov :
- Include more options in `contexts.yaml`
  - dimension sort order
  - filter by condition

- Ideally summary charts should support everything that normal charts do, by default chart properties are inherited from `contexts.yaml`, but can be over-ridden by `summary.yaml`

- Need a discussion with @novykh to evaluate the proposal and figure out next steps (work to be planned in Q1)

- In the short term, unblock use case team by creating a YAML to `contexts.js` converter script and following the current process to open PRs on `cloud-frontend`.

**Comment by shyamvalsan** [comment]
More feedback based on feedback, discussions and research:

- The ordering of the summary dashboard charts must be based on what is defined in `summary.yaml` (currently the ordering is inherited from the collector which doesn't make sense in some cases for the summary)
- Summary chart tiles must have the option to indicate their status through color (value thresholds for Red, Yellow, Green) that quickly let the user know if they have a problem for a particular metric or context. The YAML format must be updated to account for this.
- Summary should support infobox tiles, which can contain markdown and/or metric(s) that do not change very often. Eg: version number, count of instances such as DBs, uptime aggregated into days. It could look something like this:

![image](https://user-images.githubusercontent.com/24860547/208852417-9e537d4d-9ba7-4ae2-a926-30f0e26b5262.png)

- The summary dashboard MUST show the currently active alerts and current anomaly rate for this section in the summary (This is not part of the YAML definition and must be done by default for all summaries)
   -  Optionally, consider if a sub-section has active alerts then showing that in a separate summary tile with brief info on what alerts are raised in that sub-section


An updated version of the `summary.yaml` format

```
collector.summary:
  section: <optional field, text>
    row: <optional field, number>
       context: 
            chart-type: <mandatory, options are gauge|pie|number and any summary chart types we support in future>
            title: <mandatory> 
            units: <mandatory>
	    red: <optional, eg: > 90>
	    yellow: <optional, eg: >70>
	    green: <optional, eg: <=69>
       infobox: <optional, supports markdown and/or metric values>
```

Until FE has implemented the changes (section separator, multiple rows in summary, color coded thresholds, info box supporting markdown) the following fields will be ignored: `section`, `row`, `red`, `yellow`, `green`, `infobox `
