### DISCUSSION TITLE
Ping collector modes - which mode is being used infact?

### DISCUSSION THREAD

**Discussion by nicknaychov** [netdata/netdata#14845] [Q&A]
Hi
according to docs There are two operational modes - privileged and unprivileged. First one is default.

If the first one is not supported does system fallback to unprivileged (I am using centos and debian)?

How I can actually asses which mode is being used in fact?

Thank you

**Comment by ilyam8** [comment]
Hi, @nicknaychov. Fallback to the unprivileged mode is not implemented. You are correct, [the default is privileged](https://github.com/netdata/go.d.plugin/blob/abec2027a488f3dbc588a0b5a016ce14f34e30cf/config/go.d/ping.conf#L67-L71). To change the mode you need to explicitly disable it. Example:

```yaml
jobs:
  - name: example
    privileged: no
    hosts:
      - 192.0.2.0
      - 192.0.2.1
```
