### DISCUSSION TITLE
ping plugin: unprivileged mode

### DISCUSSION THREAD

**Discussion by brl9** [netdata/netdata#15006] [Q&A]
Hi 2 all.
i am trying to set up the ping go.d module: 
```
jobs:
  - name: udp
    hosts:
      - srv1
    privileged: no
```
and i see only icmp in the tcpdump. 
UDP doesn't work? 
or did i set it up wrong?
tested on  vers: 1.37.1/1.38.0/1.38.1
