### DISCUSSION TITLE
Alarm on temperature

### DISCUSSION THREAD

**Discussion by plegrand1** [netdata/netdata#15346] [Q&A]
Hello,
I use Netdata among other things to monitor the temperature of our technical room via a switch whose temperature I read from an SNMP oid.
I configure the SNMP as follows: 
 
 ```
- name: SW035
    update_every: 5
    hostname: "xxx.xxx.xxx.xxx"
    community: xxxxxxxxxx
    options:
      version: 2
    charts:
      - id: "SW035_TEMP"
        title: "Température du switch SW035"
        units: "Degres"
        type: "area"
        family: "SW035_TEMP"
        dimensions:
          - name: "Temperature"
            oid: "1.3.6.1.4.1.9.9.13.1.3.1.7.1010"
            algorithm: "absolute"
            multiplier: 1
            divisor: 1
```

I would have liked to set up an alarm as soon as the temperature exceeds a certain value.
I've searched the site without much success.
Could you give me some instructions on how to set up this alarm?
Thank you for your help.
Pascal

**Comment by MrZammler** [comment]
Hi Pascal!

You can check out first our page on creating a new health entity (a new alert) here: https://learn.netdata.cloud/docs/alerting/health-configuration-reference#write-a-new-health-entity

Start from there to get a gist of how they are constructed, and do let us know if you want more help on it.

I would imagine that something like the example there could fit your needs (which in essence checks the last 1minute, and if the average value is above a certain number it fires a warning or critical).

**Comment by plegrand1** [comment]
Hello and thanks for your answer,
then if i understand well i only need to create a configuration file like this one and reload Netdata

My English is not very good and some points are not very clear to me.

_alarm: temp_sw035
on: **How can i find the graph name ?**
lookup: **not really clear for me**
 units: **I can choose anything i want like "degre"?**
 every: 1m
  warn: $this > 30
  crit: $this > 35
  info: Temperature in LT00_

Thanks for your help
Pascal

**Comment by ilyam8** [comment]
Hi. Try

```yaml
template: temp_sw035
      on: snmp.SW035_TEMP
    calc: $Temperature
   units: degre
   every: 1m
    warn: $this > (($status >= $WARNING)  ? (28) : (30))
    crit: $this > (($status == $CRITICAL) ? (30) : (35))
    info: Temperature in LT00
```

See "[Special use of the conditional operator](https://learn.netdata.cloud/docs/alerting/health-configuration-reference)" to understand warn/crit

**Comment by plegrand1** [comment]
Thanks a lot for your answer,
This is what i did : 

```
cd /etc/netdata
touch health.d/sw037-temp.conf
./edit-config go.d/sw037-temp.conf

template: temp_sw037
      on: snmp.SW037_TEMP
    calc: $Temperature
   units: degre
   every: 1m
    warn: $this > (($status >= $WARNING)  ? (28) : (30))
    crit: $this > (($status == $CRITICAL) ? (30) : (35))
    info: Temperature in LT02
    
systemctl restart netdata.service    
```

3 things:
- What is the "$Temperature" variable ?
- Not sure the name of the graph is OK
![image](https://github.com/netdata/netdata/assets/8543044/cc7b3428-58e0-445c-aeeb-0e5ca8212eb1)
May be it should be : "**snmp_SW037.SW037_TEMP**" ?
- How i test my alarm ?

Thanks again

**Reply by ilyam8** [reply]
> title

title: "Température du switch SW035" => title: "Temperature du switch SW035"


> May be it should be : "snmp_SW037.SW037_TEMP" ?

You need exact chart id when using `alarm:`, in my example it is `template:` so it should be fine with `on: snmp.SW037_TEMP`. You can use `on: snmp_SW037.SW037_TEMP` if change template to alarm.

> How i test my alarm ?

Open Alarms => All and find your alarm.

**Comment by plegrand1** [comment]
With this configuration:

**SNMP**
```
  - name: SW037
    update_every: 5
    hostname: "xxx.xxx.xxx.xxx"
    community: xxxxxxxxxx
    options:
      version: 2
    charts:
      - id: "SW037_TEMP"
        title: "Température du switch SW037 (LT02 - GEII)"
        units: "Degres"
        type: "area"
        family: "SW037_TEMP"
        dimensions:
          - name: "Temperature"
            oid: "1.3.6.1.4.1.9.9.13.1.3.1.7.1010"
            algorithm: "absolute"
            multiplier: 1
            divisor: 1

```           
ALARM
```
template: temp_sw037
      on: snmp.SW037_TEMP
    calc: $Temperature
   units: degre
   every: 1m
    warn: $this > (($status >= $WARNING)  ? (28) : (30))
    crit: $this > (($status == $CRITICAL) ? (30) : (35))
    info: Temperature in LT02
```
I cant see my alarm on the list
