### DISCUSSION TITLE
k8s-state metrics are empty while pod is running

### DISCUSSION THREAD

**Discussion by Garahk** [netdata/netdata#15566] [Q&A]
I have a setup of 2 servers, both with k3s clusters, am using the helm chart to install netdata, and on both of them the k8s-state won't load anything on the dashboard:

![image](https://github.com/netdata/netdata/assets/99432183/e9907305-5974-4d93-93bf-0eb9583c3082)

Am thinking the servers might be low on resources and that a delay might be needed like the one you suggested for the kubelet in the child pod to allow the plugins to load:

```
    kubelet:
      enabled: true
      path: /etc/netdata/go.d/k8s_kubelet.conf
      data: |
        update_every: 1
        autodetection_retry: 0
        jobs:
          - url: http://127.0.0.1:10255/metrics
          - url: https://localhost:10250/metrics
            update_every: 10
            timeout: 10
            tls_skip_verify: yes

```

And if so is the case, would the lines be inserted at go.d and go.d-k8s_state?

```
    go.d:
      enabled: true
      path: /etc/netdata/go.d.conf
      data: |
        default_run: no
        modules:
          k8s_state: yes
    go.d-k8s_state:
      enabled: true
      path: /etc/netdata/go.d/k8s_state.conf
      data: |
        jobs:
          - name: k8s_state
            update_every: 1
```

I have logs for the parent, child and k8s-state pods of one of the servers, if needed I can share for suggestions.
