### DISCUSSION TITLE
[How To]  netdata monitor docker containers?

### DISCUSSION THREAD

**Discussion by klissda** [netdata/netdata#16310] [Q&A]
I would like to know the steps for using netdata to monitor a docker container
by using docker-compose

**Comment by ilyam8** [comment]
Hi. See https://learn.netdata.cloud/docs/installing/docker#recommended-way. That guide has instructions for both docker run and docker compose.

**Reply by klissda** [reply]
Sorry, I read it and didn't quite understand it. There will be an example. docker-compose for container monitoring?

**Reply by ilyam8** [reply]
There is an example of docker-compose.

<details><summary>screenshot</summary>

<img width="1270" alt="Screenshot 2023-11-01 at 09 32 33" src="https://github.com/netdata/netdata/assets/22274335/c2a295df-18eb-4f0e-926e-838fae4a7ccc">

</details>

**Comment by klissda** [comment]
> There is an example of docker-compose.
> 
> screenshot

Thank  @ilyam8 

I'm sorry, please help me look at an example. docker-compose for me please
If I want to monitor  ```container_name: document-expire-backend```    What do I have to do?

docker-compose.yml
```
version: '3.8'

services:

  document-expire-backend:
    container_name: document-expire-backend
    image: document-expire-backend:0.0.5
    build:
      context: .
    ports:
      - "3800:3800"
    environment:
      - EXTERNAL_PORT=3800

  netdata:
    image: netdata/netdata
    container_name: netdata
    ports:
      - 19999:19999
    environment:
      - NETDATA_UID=0
      - NETDATA_GID=0
    cap_add:
      - SYS_PTRACE
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./netdataconfig:/etc/netdata/go.d

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginxconfig/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - netdata

volumes:
  nps_data: {}

```

nginxconfig/nginx.conf
```
events {}

http {
  server {
    listen 80;
    server_name localhost;

    location / {
      proxy_pass http://netdata:19999;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location = /basic_status {
        stub_status;
    }
  }
}
```

netdataconfig/nginx.conf
```
jobs:
  - name: local
    url: http://nginx:80/basic_status

```


netdataconfig/docker.conf
```
# /etc/netdata/go.d/docker.conf

jobs:
  - name: local
    address: 'unix:///var/run/docker.sock'

  - name: nginx
    address: 'unix:///var/run/docker.sock'
    containers: 'nginx'
    memory: yes
    cpu: yes
    network: yes
    diskio: yes
    update_every: 10  # Adjust the update interval to 10 seconds (or your desired value)
    autodetection_retry: 5  # Set the number of retries for autodetection to 5
```
