### DISCUSSION TITLE
Netdata on QNAP docker - local-custom-dashboard not saving

### DISCUSSION THREAD

**Discussion by televisi** [netdata/netdata#17080] [Q&A]
Hi,

I installed Netdata on a docker (host is using QNAP).

The docker compose I used:
```
version: '3'
services:
  netdata:
    image: netdata/netdata
    hostname: 192.168.1.26
    pid: host
    network_mode: host
    restart: unless-stopped
    environment:
      - NETDATA_EXTRA_DEB_PACKAGES=apcupsd
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - /share/Container-Data/netdata/config:/etc/netdata
      - /share/Container-Data/netdata/lib:/var/lib/netdata
      - /share/Container-Data/netdata/cache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock
      #Below added as per https://github.com/netdata/netdata/blob/master/src/collectors/cgroups.plugin/README.md
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
```

I added various metric/reports into local-custom-dashboard.
I also renamed "local-custom-dashboard" into something else
And saved the dashboard.

When I tried to access the dashboard from a different browser (or in incognito mode); seems the dashboard from earlier session not saved.

Is this an expected behaviour? OR did I miss a docker configuration to allow the dashboard to be saved (and accessible from other browser)?

Thank you
