### DISCUSSION TITLE
Collect from multiple paths in web_log

### DISCUSSION THREAD

**Discussion by aloz77** [netdata/netdata#17303] [Q&A]
How can I setup **web_log** to collect from multiple paths? Something like this doesn't seem to work as expected:

```
  # APACHE
  # debian
  - name: apache
    path: /var/log/apache2/*/access.log
```

But it looks like I can collect from one specific path:

```
  # APACHE
  # debian
  - name: apache
    path: /var/log/apache2/domain1.com/access.log
```

**Comment by ilyam8** [comment]
Hi, @aloz77. No, it is not possible to collect data from multiple files within a single data collection job.

**Reply by aloz77** [reply]
What is the best approach to use `web_log` if Apache/NGINX writes separate log files (for different domains) ?

**Reply by ririsoft** [reply]
@aloz77 : you can configure multiple jobs, one for each log:

```yaml
- name: apache_domainA
    path: /var/log/apache/access_domainA.log
- name: apache_domainB
    path: /var/log/apache/access_domainB.log
```

@ilyam8 : What about turning this discussion into a feature request, do you think it would be accepted ?
