### DISCUSSION TITLE
How to add custom label for mongodb job in netdata

### DISCUSSION THREAD

**Discussion by klingsoltrout** [netdata/netdata#17597] [Q&A] [answered]
I can't distinguish two rs in metrics, Add a custom labels in mongo jobs is urgently needed, how can i do it?

**Comment by klingsoltrout** [comment]
![111](https://github.com/netdata/netdata/assets/42562246/364d7374-bb18-48cb-b124-4eb389095d3e)

**Reply by ilyam8** [reply, marked as answer]
Hi, @YexinZhang. You can add it by using the `labels` setting

```yaml
jobs:
- name: sa_nosql_replica_01
  uri: "mongodb://..."
  labels:
     key1: value
     key2: value
```
