### DISCUSSION TITLE
Noob needs help on MacOS, monitoring Docker

### DISCUSSION THREAD

**Discussion by nothing2obvi** [netdata/netdata#17796] [Q&A]
Hello. I'm usually one to figure this stuff out on my own but I'm completely lost. I've installed Netdata on my Intel Mac via Homebrew and I want to monitor Docker. I'd appreciate it greatly if someone could please check these over, including their file locations. I have tried variations in the spacing before modules and plugins but still can't get it to show up. I always used the `edit-config` command to make changes (is this necessary?), and I use `brew services restart netdata` after making changes. I will note that I don't see a `go.d.plugin` anywhere. Or a plugins folder. Thank you very much.

`/usr/local/etc/netdata/netdata.conf`
```
# netdata configuration
#
# You can get the latest version of this file, using:
#
#  netdatacli dumpconfig > /etc/netdata/netdata.conf
#
# You can also download it using:
#
#  wget -O /etc/netdata/netdata.conf http://localhost:19999/netdata.conf
# or
#  curl -o /etc/netdata/netdata.conf http://localhost:19999/netdata.conf
#
# You can uncomment and change any of the options below.
# The value shown in the commented settings, is the default value.
#

[global]
    run as user = netdata

    # default storage size - increase for longer data retention
    page cache size = 32
    dbengine multihost disk space = 256

[plugins]
 go.d = yes # enabled
```

`/usr/local/etc/netdata/go.d.conf`
```
# netdata go.d.plugin configuration
#
# This file is in YAML format.

# Enable/disable the whole go.d.plugin.
enabled: yes

# Enable/disable default value for all modules.
default_run: yes

# Maximum number of used CPUs. Zero means no limit.
max_procs: 0

# Enable/disable specific g.d.plugin module
# If you want to change any value, you need to uncomment out it first.
# IMPORTANT: Do not remove all spaces, just remove # symbol. There should be a space before module name.
modules:
#  adaptec_raid: yes
#  activemq: yes
#  apache: yes
#  bind: yes
#  chrony: yes
#  clickhouse: yes
#  cockroachdb: yes
#  consul: yes
#  coredns: yes
#  couchbase: yes
#  couchdb: yes
#  dnsdist: yes
#  dnsmasq: yes
#  dnsmasq_dhcp: yes
#  dns_query: yes
  docker: yes
  docker_engine: yes
#  dockerhub: yes
#  elasticsearch: yes
#  envoy: yes
#  example: no
#  fail2ban: yes
#  filecheck: yes
#  fluentd: yes
#  freeradius: yes
#  haproxy: yes
#  hddtemp: yes
#  hdfs: yes
#  hpssa: yes
#  httpcheck: yes
#  intelgpu: yes
#  isc_dhcpd: yes
#  k8s_kubelet: yes
#  k8s_kubeproxy: yes
#  lighttpd: yes
#  litespeed: yes
#  logind: yes
#  logstash: yes
#  lvm: yes
#  megacli: yes
#  mongodb: yes
#  mysql: yes
#  nginx: yes
#  nginxplus: yes
#  nginxvts: yes
#  ntpd: yes
#  nvme: yes
#  nvidia_smi: no
#  openvpn: no
#  openvpn_status_log: yes
#  ping: yes
#  pgbouncer: yes
#  phpdaemon: yes
#  phpfpm: yes
#  pihole: yes
#  pika: yes
#  portcheck: yes
#  postgres: yes
#  powerdns: yes
#  powerdns_recursor: yes
#  prometheus: yes
#  pulsar: yes
#  rabbitmq: yes
#  redis: yes
#  rspamd: yes
#  scaleio: yes
#  sensors: yes
#  snmp: yes
#  squidlog: yes
#  smartctl: yes
#  storcli: yes
#  supervisord: yes
#  systemdunits: yes
#  tengine: yes
#  traefik: yes
#  upsd: yes
#  unbound: yes
#  vernemq: yes
#  vcsa: yes
#  vsphere: yes
#  web_log: yes
#  wireguard: yes
#  whoisquery: yes
#  windows: yes
#  x509check: yes
#  zfspool: yes
#  zookeeper: yes
```

`/usr/local/etc/netdata/go.d/docker.conf`
```
## All available configuration options, their descriptions and default values:
## https://github.com/netdata/netdata/tree/master/src/go/collectors/go.d.plugin/modules/docker#readme

jobs:
  - name: local
    address: 'unix:///var/run/docker.sock'
    timeout: 2
    collect_container_size: no
```

`/usr/local/etc/netdata/go.d/docker_engine.conf`
```
## All available configuration options, their descriptions and default values:
## https://github.com/netdata/netdata/tree/master/src/go/collectors/go.d.plugin/modules/docker_engine#readme

jobs:
  - name: local
    url: http://127.0.0.1:9323/metrics
```

Thank you again!
