### DISCUSSION TITLE
NVME Integration doesn't show any charts

### DISCUSSION THREAD

**Discussion by TurtleTony** [netdata/netdata#18698] [Q&A]
Hi everybody,
I am trying to setup netdata for my NAS. I want to monitor the nvme drives so naturally I stumbled across the NVMe devices collector. My netdata is running in docker and I was able to configure the drives in the compose file:

```
    environment:
      NETDATA_EXTRA_DEB_PACKAGES: nvme-cli
    devices:
      - "/dev/nvme0n1:/dev/nvme0n1"
      - "/dev/nvme1n1:/dev/nvme1n1"
      - "/dev/nvme2n1:/dev/nvme2n1"
      - "/dev/nvme3n1:/dev/nvme3n1"
```

The config _seems_ to be working, I can even see some logs about the devices

`time=2024-10-06T18:50:42.811+00:00 comm=netdata source=health level=info tid=449 thread=HEALTH msg_id=9ce0cb58ab8b44df82c4bf1ad9ee22de node=netdata.turtletony.net instance=disk_util.nvme3n1 context=disk.util code=0 alert_id=1728234588 alert_unique_id=1728245636 alert_event_id=41 alert_transition_id=beca5cb215754f63b0fd4a616a384240 alert_config=12a5910867544718a28ce6e73450f456 alert=10min_disk_utilization alert_class=Utilization alert_component=Disk alert_type=System alert_exec=/usr/libexec/netdata/plugins.d/alarm-notify.sh alert_recipient=silent alert_duration=0 alert_value=1.2378378 alert_value_old=null alert_status=CLEAR alert_value_old=UNINITIALIZED alert_units=% alert_summary="Disk nvme3n1 utilization" alert_info="Average percentage of time nvme3n1 disk was busy over the last 10 minutes" alert_notification_timestamp=2024-10-06T18:50:42+00:00 msg="ALERT '10min_disk_utilization' of instance 'disk_util.nvme3n1' on node 'netdata.turtletony.net', transitioned from UNINITIALIZED to CLEAR"`

Unfortunately I do not see any charts in the UI. Can somebody explain what I'm missing here? Why aren't the charts showing up?

![image](https://github.com/user-attachments/assets/f7a1ba4b-42a9-4013-bfda-53b497c21659)

Kind regards,
Tristan
