### ISSUE TITLE
Netdata process crash after high system load

### ISSUE THREAD

**Issue by DominikTrenz** [netdata/netdata#10413]
Hello,
i'm expiriencing crashes of netdata while the machine it is running on is under stress. The netdata process is running as docker container and working fine for weeks but as soon as the ram is at 100% for a few minutes it crashes and the docker deamon looses control. It switches to state "Up (unhealthy)" and can't be stopped or restarted. I can force remove the container and it's network, kill the process and recreate the container. The last log files from the container before it crashes:

```netdata    | 2020-12-22 09:00:16: netdata ERROR : PLUGINSD[go.d] : read failed: end of file (errno 22, Invalid argument)
netdata    | 2020-12-22 09:00:16: netdata INFO  : PLUGINSD[go.d] : PARSER ended
netdata    | 2020-12-22 09:00:16: netdata ERROR : PLUGINSD[go.d] : '/usr/libexec/netdata/plugins.d/go.d.plugin' (pid 181) disconnected after 0 successful data collections (ENDs). (errno 22, Invalid argument)
netdata    | 2020-12-22 09:00:16: netdata ERROR : PLUGINSD[go.d] : child pid 181 killed by signal 9.
netdata    | 2020-12-22 09:00:16: netdata INFO  : PLUGINSD[go.d] : '/usr/libexec/netdata/plugins.d/go.d.plugin' (pid 181) was killed with SIGTERM. Disabling it.
netdata    | 2020-12-22 09:00:16: netdata INFO  : PLUGINSD[go.d] : thread with task id 151 finished
netdata    | 2020-12-22 09:00:16: netdata ERROR : PLUGINSD[apps] : read failed: end of file (errno 22, Invalid argument)
netdata    | 2020-12-22 09:00:16: netdata INFO  : PLUGINSD[apps] : PARSER ended
netdata    | 2020-12-22 09:00:16: netdata ERROR : PLUGINSD[apps] : '/usr/libexec/netdata/plugins.d/apps.plugin' (pid 155) disconnected after 33311730 successful data collections (ENDs). (errno 22, Invalid argument)
netdata    | 2020-12-22 09:00:16: netdata ERROR : PLUGINSD[apps] : child pid 155 killed by signal 9.
netdata    | 2020-12-22 09:00:16: netdata INFO  : PLUGINSD[apps] : '/usr/libexec/netdata/plugins.d/apps.plugin' (pid 155) was killed with SIGTERM. Disabling it.
netdata    | 2020-12-22 09:00:16: netdata INFO  : PLUGINSD[apps] : thread with task id 144 finished
netdata    | 2020-12-22 09:00:16: netdata INFO  : MAIN : EOF found in spawn pipe.
netdata    | 2020-12-22 09:00:16: netdata ERROR : PLUGIN[tc] : child pid 24626 killed by signal 9.
netdata    | 2020-12-22 09:00:18: tc-qos-helper.sh: WARNING: FireQoS is not installed on this system. Use FireQoS to apply traffic QoS and expose the class names to netdata. Check https://github.com/netdata/netdata/tree/master/collectors/tc.plugin#tcplugin
netdata    | 2020-12-22 09:00:18: tc-qos-helper.sh: WARNING: Cannot find file '/usr/lib/netdata/conf.d/tc-qos-helper.conf'.
netdata    | 2020-12-22 09:00:18: tc-qos-helper.sh: WARNING: Cannot find file '/etc/netdata/tc-qos-helper.conf'.
netdata    | 2020-12-22 09:00:19: netdata INFO  : PLUGIN[cgroups] : Deleting chart 'net.veth76c6b57' ('net.veth76c6b57') from disk...
netdata    | 2020-12-22 09:00:19: netdata ERROR : PLUGIN[cgroups] : Cannot read left-over chart directory to be deleted '/var/cache/netdata/net.veth76c6b57' (errno 2, No such file or directory)
netdata    | 2020-12-22 09:00:19: netdata INFO  : PLUGIN[cgroups] : Deleting chart 'net.veth46fedff' ('net.veth46fedff') from disk...
netdata    | 2020-12-22 09:00:19: netdata ERROR : PLUGIN[cgroups] : Cannot read left-over chart directory to be deleted '/var/cache/netdata/net.veth46fedff' (errno 2, No such file or directory)
netdata    | 2020-12-22 09:00:19: netdata INFO  : PLUGIN[cgroups] : Deleting chart 'net_packets.vethf85c76d' ('net_packets.vethf85c76d') from disk...
netdata    | 2020-12-22 09:00:19: netdata ERROR : PLUGIN[cgroups] : Cannot read left-over chart directory to be deleted '/var/cache/netdata/net_packets.vethf85c76d' (errno 2, No such file or directory)
netdata    | 2020-12-22 09:00:19: netdata INFO  : PLUGIN[cgroups] : Deleting chart 'net.vethf85c76d' ('net.vethf85c76d') from disk...
netdata    | 2020-12-22 09:00:19: netdata ERROR : PLUGIN[cgroups] : Cannot read left-over chart directory to be deleted '/var/cache/netdata/net.vethf85c76d' (errno 2, No such file or directory)
netdata    | 2020-12-22 09:00:19: netdata INFO  : PLUGIN[cgroups] : Deleting chart 'net_packets.vethd848b50' ('net_packets.vethd848b50') from disk...
netdata    | 2020-12-22 09:00:19: netdata ERROR : PLUGIN[cgroups] : Cannot read left-over chart directory to be deleted '/var/cache/netdata/net_packets.vethd848b50' (errno 2, No such file or directory)
netdata    | 2020-12-22 09:00:19: netdata INFO  : PLUGIN[cgroups] : Deleting chart 'net.vethd848b50' ('net.vethd848b50') from disk...
netdata    | 2020-12-22 09:00:19: netdata ERROR : PLUGIN[cgroups] : Cannot read left-over chart directory to be deleted '/var/cache/netdata/net.vethd848b50' (errno 2, No such file or directory)
netdata    | 2020-12-22 09:00:25: netdata ERROR : PLUGIN[tc] : child pid 27922 killed by signal 9.
```

The issue appears on several separated machines with the latest docker image. All the netdata processes are configured to gather data only and replicate them to a master netdata instance. The last information on the master netdata is that cpu and ram are used 100%.

```
[global]
    memory mode = none

[web]
    mode = none
    accept a streaming request every seconds = 0

[backend]
    enabled = no
```
docker-compose.yml
```
version: "2.4"
services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: ${netdata-hostname}
    restart: unless-stopped
    depends_on:
      - proxy
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    environment:
      - DOCKER_HOST=proxy:2375
      - DO_NOT_TRACK=1
    volumes:
      - ./netdata.conf:/etc/netdata/netdata.conf
      - ./stream.conf:/etc/netdata/stream.conf
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
  proxy:
    image: tecnativa/docker-socket-proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1

volumes:
  netdatalib:
  netdatacache:

```
