### ISSUE TITLE
health monitoring stops working for slave hosts after some time

### ISSUE THREAD

**Issue by razielin** [netdata/netdata#10548]
##### Bug report summary

I have one netdata master server and about 10 slave netdata servers that are streaming metrics to the master server.
All health configuration files are configured at the master server only. But after a while (about 2-7 days, but it rather nondeterministic), periodic checks for all alarms of a particular slave host are stopped from being executing on the master server. Active alarms stay forever in their current states.
```
curl http://netdata_master:19999/host/slave_host1/api/v1/alarms?all
{
      "hostname": "slave_host1",
      "latest_alarm_log_unique_id": 1611136189,
      "status": false,
      "now": 1611328438, // "2021-01-22 15:13:58"
	"alarms": {
		"system.ram.ram_in_use": {
                        "id": 1611136034,
                        "name": "ram_in_use",
                        "chart": "system.ram",
                         …
			"last_updated": 1611145396, // "2021-01-20 12:23:16"
                        "next_update": 1611145406, // "2021-01-20 12:23:26"
                        "update_every": 10,
}
```
As you can see `"last_updated"` and `"next_update"` are two days ago in the past compared to `“now”`. The `"last_updated"` value is the same for all alarms of the slave host. 
This situation occurs for the rest of the slave hosts after some time. Streaming of metrics to the master keeps working properly.
I haven't found anything strange in the log. If you need some part of it, let me know, please.
##### OS / Environment
The netdata master service works inside a docker container from the official netdata image v1.28.0.
Configuration of the host system:
- Ubuntu 18.04.1 LTS
- Linux 4.15.0-122-generic
- Docker version 19.03.6.
`cat docker-compose.yml:`
```
version: '2'
services:
  netdata_master:
    image: netdata_master
    build:
      context: netdata_master
      dockerfile: Dockerfile
    restart: always
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdata_cache:/var/cache/netdata
      - netdata_lib:/var/lib/netdata
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run:/var/run/host_run:ro
    networks:
      - monitoring
      ...
```

##### Netdata version

 v1.28.0
But this problem also occurred in the previous versions as well ( v1.26 and some older ones).

##### Component Name

health

##### Steps To Reproduce

I don't know. It is non-deterministic.

##### Expected behavior

Health monitoring keeps working properly for the streamed slave hosts.
