### ISSUE TITLE
Curl SSL verification failed with Let's Encrypt generated certificates

### ISSUE THREAD

**Issue by GrumpyMetalGuy** [netdata/netdata#11056]
##### Bug report summary

When running netdata from a docker image pulled from docker hub, the docker container is failing a health check around curl SSL certificate validation after securing the server with SSL certificates issued by Let's Encrypt. Health check error is listed as:

```
curl: (60) SSL certificate problem: unable to get local issuer certificate More details here: https://curl.se/docs/sslcerts.html curl failed to verify the legitimacy of the server and therefore could not establish a secure connection to it. To learn more about this situation and how to fix it, please visit the web page mentioned above. 
```

The SSL certificates are working fine for the web frontend. 

##### OS / Environment

```
uname -a; grep -Hv "^#" /etc/*release
Linux core.the9thcircle.com 5.10.0-0.bpo.5-amd64 #1 SMP Debian 5.10.24-1~bpo10+1 (2021-03-29) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"
```

Running in a docker container. Server runs OpenMediaVault 5.

##### Netdata version

netdata -W buildinfo
Version: netdata v1.30.1-90-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-lws=externaldeps/libwebsockets' '--with-libJudy=externaldeps/libJudy' 'CFLAGS=' 'LDFLAGS='
Features:
    dbengine:                YES
    Native HTTPS:            YES
    Netdata Cloud:           YES 
    Cloud Implementation:    Legacy
    TLS Host Verification:   YES
Libraries:
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES static v3.2.2
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES

##### Installation method

Installed using a docker compose file as follows:

```
---
version: '3'
services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: core.the9thcircle.com
    network_mode: host
    ports:
      - 19999:19999
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdata_config:/etc/netdata
      - netdata_lib:/var/lib/netdata
      - netdata_cache:/var/cache/netdata
      - /var/lib/dehydrated/certs/core.the9thcircle.com:/certs
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    environment:
        DOCKER_HOST: proxy:2375

  proxy:
    image: tecnativa/docker-socket-proxy
    container_name: netdata_proxy
    network_mode: host
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1

volumes:
  netdata_config:
    external: true
  netdata_lib:
    external: true
  netdata_cache:
    external: true
```

##### Component Name

Not entirely sure!

##### Steps To Reproduce

1. Use docker compose file outlined above.
2. Set SSL configuration in [web] portion of netdata.conf
3. Verify that web dashboards are visible from https secured connection.
4. Examine docker status and see that heath checks fail.

##### Expected behavior

No health check failures, and no need to disable MITM checks in config.
