### ISSUE TITLE
Non-root Docker -> no Docker containers CPU+Memory

### ISSUE THREAD

**Issue by schklom** [netdata/netdata#11069]
##### Bug report summary
The webpage doesn't include any information on Docker containers

##### OS / Environment

```
$ uname -a; grep -Hv "^#" /etc/*release
Linux <REDACTED> 5.10.0-0.bpo.5-arm64 #1 SMP Debian 5.10.24-1~bpo10+1 (2021-03-29) aarch64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"
```

##### Netdata version

```
netdata v1.30.1-112-nightly
```
##### Installation method

Docker
##### Component Name

CPUs
Memory

I can see the CPU utilization of Docker processes, but there is no general list of containers where I can see CPU and Memory use.
##### Steps To Reproduce

1. Install [Rootless Docker](https://docs.docker.com/engine/security/rootless/#install) without packages
2. docker-compose.yml
```
  netdata:
    image: netdata/netdata
    container_name: netdata
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    environment:
      - TZ=${TZ}
      - DOCKER_USR=root
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERDATA}/netdata/config:/etc/netdata
      - ${DOCKERDATA}/netdata/lib:/var/lib/netdata
      - ${DOCKERDATA}/netdata/cache:/var/cache/netdata
      - /etc/os-release:/host/etc/os-release:ro
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /run/user/1001/docker.sock:/var/run/docker.sock
    ports:
      - 19999:19999
```

##### Expected behavior

As with regular (Rootful) Docker, I expect to see the list of containers along with their CPU and Memory use.
