### ISSUE TITLE
mysql go client autodetection_retry doesn't seem to work

### ISSUE THREAD

**Issue by lucasRolff** [netdata/netdata#11131]
##### Bug report summary

I use Netdata extensively and recently made the switch from the python MySQL client to the Golang MySQL client in netdata.

However, whenever MySQL restarts (during upgrade or maintenance), it quite often results in the monitoring of MySQL stops (because of no metrics).

I've configured `autodetection_retry` to 60 in the `mysql.conf`, sadly I never see retry messages in the log, and monitoring of MySQL stays down for hours.

##### OS / Environment

```
/etc/cloudlinux-release:CloudLinux release 8.3 (Pavel Belyayev)
/etc/os-release:NAME="CloudLinux"
/etc/os-release:VERSION="8.3 (Pavel Belyayev)"
/etc/os-release:ID="cloudlinux"
/etc/os-release:ID_LIKE="rhel fedora centos"
/etc/os-release:VERSION_ID="8.3"
/etc/os-release:PLATFORM_ID="platform:el8"
/etc/os-release:PRETTY_NAME="CloudLinux 8.3 (Pavel Belyayev)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:cloudlinux:cloudlinux:8.3:GA:server"
/etc/os-release:HOME_URL="https://www.cloudlinux.com/"
/etc/os-release:BUG_REPORT_URL="https://www.cloudlinux.com/support"
/etc/redhat-release:CloudLinux release 8.3 (Pavel Belyayev)
/etc/system-release:CloudLinux release 8.3 (Pavel Belyayev)
```

##### Netdata version

```
Version: netdata v1.30.1
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--disable-ebpf' '--enable-plugin-freeipmi' '--with-bundled-lws=externaldeps/libwebsockets' '--with-libJudy=externaldeps/libJudy' 'CFLAGS=-O2' 'LDFLAGS='
Features:
    dbengine:                YES
    Native HTTPS:            YES
    Netdata Cloud:           YES
    Cloud Implementation:    Legacy
    TLS Host Verification:   YES
Libraries:
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES static v3.2.2
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

##### Installation method

```
bash <(curl -Ss https://my-netdata.io/kickstart.sh)
```

##### Component Name

MySQL Golang

##### Steps To Reproduce

1. Configure autodetection_retry to 60 seconds (or lower)
2. Kill MySQL after monitoring has started, wait a bit, start MySQL again
3. Netdata won't pick up monitoring MySQL again

##### Expected behavior

The retry mechanism should work.

##### Additional info

config:
```
# netdata go.d.plugin configuration for mysql
#
# This file is in YAML format. Generally the format is:
#
# name: value
#
# There are 2 sections:
#  - GLOBAL
#  - JOBS
#
#
# [ GLOBAL ]
# These variables set the defaults for all JOBs, however each JOB may define its own, overriding the defaults.
#
# The GLOBAL section format:
# param1: value1
# param2: value2
#
# Currently supported global parameters:
#  - update_every
#    Data collection frequency in seconds. Default: 1.
#
#  - autodetection_retry
#    Re-check interval in seconds. Attempts to start the job are made once every interval.
#    Zero means not to schedule re-check. Default: 0.
#
#  - priority
#    Priority is the relative priority of the charts as rendered on the web page,
#    lower numbers make the charts appear before the ones with higher numbers. Default: 70000.
#
#
# [ JOBS ]
# JOBS allow you to collect values from multiple sources.
# Each source will have its own set of charts.
#
# IMPORTANT:
#  - Parameter 'name' is mandatory.
#  - Jobs with the same name are mutually exclusive. Only one of them will be allowed running at any time.
#
# This allows autodetection to try several alternatives and pick the one that works.
# Any number of jobs is supported.
#
# The JOBS section format:
#
# jobs:
#   - name: job1
#     param1: value1
#     param2: value2
#
#   - name: job2
#     param1: value1
#     param2: value2
#
#   - name: job2
#     param1: value1
#
#
# [ List of JOB specific parameters ]:
#  - dsn
#    Data Source Name.
#    Format: [username[:password]@][protocol[(address)]]/dbname[?param1=value1&...&paramN=valueN]
#    Except for the databasename, all values are optional. So the minimal DSN is: /dbname
#    If you do not want to preselect a database, leave dbname empty: /
#    Full description: https://github.com/go-sql-driver/mysql#dsn-data-source-name
#    Syntax:
#     dsn: netdata@tcp(127.0.0.1:3306)/
#
#  - my.cnf
#    Specifies my.cnf file to read connection parameters from under the [client] section
#    Syntax:
#     my.cnf: '/etc/my.cnf'
#
#
# [ JOB defaults ]:
#  No parameters
#
#
# [ JOB mandatory parameters ]:
#  - name
#  - dsn
# ------------------------------------------------MODULE-CONFIGURATION--------------------------------------------------
# [ GLOBAL ]
# update_every: 1
autodetection_retry: 60
# priority: 70000
#
#
# [ JOBS ]
jobs:
  # netdata
  - name: local
    dsn: netdata@unix(/var/run/mysqld/mysqld.sock)/

  - name: local
    dsn: netdata@unix(/var/run/mysqld/mysql.sock)/

  - name: local
    dsn: netdata@unix(/var/lib/mysql/mysql.sock)/

  - name: local
    dsn: netdata@unix(/tmp/mysql.sock)/

  - name: local
    dsn: netdata@tcp(127.0.0.1:3306)/

  - name: local
    dsn: netdata@tcp([::1]:3306)/
```
