### ISSUE TITLE
Qnap - MD5 stats for two raids is missleading

### ISSUE THREAD

**Issue by groenator** [netdata/netdata#11180]
##### Bug report summary

I am running the netdata agent inside a docker container on my QNAP.

 I have two alerts from the mdstats about my raid. It does seem that the two raids in question are in use and they bypass the threshold.

This is my mdStat stats:

```
[~] # cat /proc/mdstat
Personalities : [linear] [raid0] [raid1] [raid10] [raid6] [raid5] [raid4] [multipath]
md1 : active raid5 sda3[4] sdd3[7] sdc3[6] sdb3[5]
      17551703040 blocks super 1.0 level 5, 512k chunk, algorithm 2 [4/4] [UUUU]

md322 : active raid1 sdd5[3](S) sdc5[2](S) sdb5[1] sda5[0]
      7235136 blocks super 1.0 [2/2] [UU]
      bitmap: 0/1 pages [0KB], 65536KB chunk

md256 : active raid1 sdd2[3](S) sdc2[2](S) sdb2[1] sda2[0]
      530112 blocks super 1.0 [2/2] [UU]
      bitmap: 0/1 pages [0KB], 65536KB chunk

md13 : active raid1 sda4[26] sdd4[27] sdb4[24] sdc4[25]
      458880 blocks super 1.0 [24/4] [UUUU____________________]
      bitmap: 1/1 pages [4KB], 65536KB chunk

md9 : active raid1 sda1[26] sdd1[27] sdb1[24] sdc1[25]
      530048 blocks super 1.0 [24/4] [UUUU____________________]
      bitmap: 1/1 pages [4KB], 65536KB chunk
```

This is a screenshot from netdata:

![Screenshot 2021-05-24 at 12 42 01](https://user-images.githubusercontent.com/5445030/119343076-dbdc7180-bc8d-11eb-9e16-1bac6b1e44b7.png)

I have the same alert on both Raids. 

##### OS / Environment
Qnap TS453-A

The Netdata agent is running inside a docker container. 

docker-compose details:
```
version: '3'
services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: qnap.inf.wonkypaw.org
    environment:
      - DO_NOT_TRACK=1
      - PGID=999
    ports:
      - 19999:19999
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /share/Download/netdata:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /share/Media:/share/Media
      - /share/Download:/share/Download
      - /share/gDrive:/share/gDrive
      - /share/Container:/share/Container
      - /etc/os-release:/host/etc/os-release:ro
volumes:
  netdatalib:
  netdatacache:
```
To get this information, execute the following commands based on your operating system:
```
[~] # uname -a
Linux NAS05D11F 4.14.24-qnap #1 SMP Sat May 15 08:34:14 CST 2021 x86_64 GNU/Linux
```

Can someone please advise why am I seeing these alerts? I checked my qnap and I don't see any issues with the raids, the HDDs are all healthy. Is this a false/positive alert?

Thank you!
<!--

**Comment by ilyam8** [comment]
Hi @groenator 

```cmd
530048 blocks super 1.0 [24/4] [UUUU____________________]
```

That line means:
 - ideally, the array would have 24 devices.
 - currently, 4 devices are in use.
 - 4 devices are in the `up` state (U).
 - 20 devices are in the `down` state (_).

=> the array is degraded (wants 24 devices, got 4).

**Comment by groenator** [comment]
When you said 24 devices do you mean 24 HDDs? My array has only 4 hard disks.

**Comment by groenator** [comment]
I think I know why is showing the devices down. I've looked at that array with mdam command and I see a lot of devices removed. 

```
mdadm -D /dev/md13
/dev/md13:
        Version : 1.0
  Creation Time : Sun Apr  5 20:54:56 2015
     Raid Level : raid1
     Array Size : 458880 (448.20 MiB 469.89 MB)
  Used Dev Size : 458880 (448.20 MiB 469.89 MB)
   Raid Devices : 24
  Total Devices : 4
    Persistence : Superblock is persistent

  Intent Bitmap : Internal

    Update Time : Mon May 24 16:16:42 2021
          State : clean, degraded
 Active Devices : 4
Working Devices : 4
 Failed Devices : 0
  Spare Devices : 0

           Name : 13
           UUID : beb48324:55d219cf:fbdc83bd:684867e7
         Events : 616035

    Number   Major   Minor   RaidDevice State
      26       8        4        0      active sync   /dev/sda4
      25       8       36        1      active sync   /dev/sdc4
      24       8       20        2      active sync   /dev/sdb4
      27       8       52        3      active sync   /dev/sdd4
       8       0        0        8      removed
      10       0        0       10      removed
      12       0        0       12      removed
      14       0        0       14      removed
      16       0        0       16      removed
      18       0        0       18      removed
      20       0        0       20      removed
      22       0        0       22      removed
      24       0        0       24      removed
      26       0        0       26      removed
      28       0        0       28      removed
      30       0        0       30      removed
      32       0        0       32      removed
      34       0        0       34      removed
      36       0        0       36      removed
      38       0        0       38      removed
      40       0        0       40      removed
      42       0        0       42      removed
      44       0        0       44      removed
      46       0        0       46      removed
```
If these devices are removed why netstat doesn't ignore them?

**Comment by ilyam8** [comment]
Hey, @mailinglists35 👋 Can you help with the issue? You seem to have a good experience with MD arrays.

### My test

#### setup 3 devices level 1 raid

<details>
<summary>cli [Click]</summary>

```cmd
dd if=/dev/zero of=/loopbackfile1.img bs=100M count=10
dd if=/dev/zero of=/loopbackfile2.img bs=100M count=10
dd if=/dev/zero of=/loopbackfile3.img bs=100M count=10
losetup  /dev/loop1 /loopbackfile1.img
losetup  /dev/loop2 /loopbackfile2.img
losetup  /dev/loop3 /loopbackfile3.img
mdadm --create --verbose /dev/md0 /dev/loop1 /dev/loop2 /dev/loop3 --level=1 --raid-devices=3
```

</details>

```cmd
# mdstat
Personalities : [raid1]
md0 : active raid1 loop3[2] loop2[1] loop1[0]
      1022976 blocks super 1.2 [3/3] [UUU]
```

#### remove 1 device from the array

<details>
<summary>cli [Click]</summary>

```cmd
mdadm /dev/md0 --fail /dev/loop1
mdadm /dev/md0 --remove /dev/loop1
```

</details>

```cmd
# mdstat
Personalities : [raid1]
md0 : active raid1 loop3[2] loop2[1]
      1022976 blocks super 1.2 [3/2] [_UU]

unused devices: <none>
```

---

How do we handle this situation properly?

**Comment by ilyam8** [comment]
Ok, I see, there is `mdadm grow ...` that allows shrinking the array

After **remove 1 device from the array** step I need to 

> mdadm --grow /dev/md0 --raid-devices=2

=>

```cmd
Personalities : [raid1]
md0 : active raid1 loop3[2] loop2[1]
      1022976 blocks super 1.2 [2/2] [UU]
```

---

@groenator that alarm is correct, you've removed some devices, but the number of active devices in the array (`--raid-devices`) values hasn't been changed.

**Comment by groenator** [comment]
I havent removed anything, QTS QNAP OS did. 

For now I just have to ignore it. I don't want to touch the raid and break it.

**Comment by ilyam8** [comment]
> QTS QNAP OS did.

Then I suggest you ask for their support, the arrays are in a degraded state. Just removing a disk is not enough, you need to shrink the array if you are not going to add another disk.

---

> I don't want to touch the raid and break it.

I understand your point. You can tune the alarm

```yaml
 template: mdstat_disks
       on: md.disks
    class: System
component: RAID
     type: Errors
    units: failed devices
    every: 10s
     calc: $down
     crit: $this > 0
     info: number of devices in the down state for the $family array. \
           Any number > 0 indicates that the array is degraded.
       to: sysadmin
```

=>

```yaml
 template: mdstat_disks
       on: md.disks
    class: System
component: RAID
     type: Errors
 families: !md9* !md13* *
    units: failed devices
    every: 10s
     calc: $down
     crit: $this > 0
     info: number of devices in the down state for the $family array. \
           Any number > 0 indicates that the array is degraded.
       to: sysadmin
```
