### ISSUE TITLE
Netdata Docker/Docker-compose installs fail to see attached Volumes/contents of /var/lib/netdata/registry/netdata.public.unique.id

### ISSUE THREAD

**Issue by Veeedka** [netdata/netdata#11933]
##### OS / Environment

```
Docker Host: 

Linux dockerhost01 3.10.0-1160.41.1.el7.x86_64 #1 SMP Tue Aug 31 14:52:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 7.7.1908 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:HOME_URL="https://www.centos.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.centos.org/"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.7.1908 (Core)
/etc/system-release:CentOS Linux release 7.7.1908 (Core)

Inside Docker container: 

```cmd
Linux dockerhost01 3.10.0-1160.41.1.el7.x86_64 #1 SMP Tue Aug 31 14:52:47 UTC 2021 x86_64 Linux
/etc/alpine-release:3.15.0
/etc/os-release:NAME="Alpine Linux"
/etc/os-release:ID=alpine
/etc/os-release:VERSION_ID=3.15.0
/etc/os-release:PRETTY_NAME="Alpine Linux v3.15"
/etc/os-release:HOME_URL="https://alpinelinux.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

AND 

```cmd
Linux hassio 4.15.0-163-generic #171-Ubuntu SMP Fri Nov 5 11:55:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.2 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.2 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

Inside container: 

```cmd
Linux 48e0b85df119 4.15.0-163-generic #171-Ubuntu SMP Fri Nov 5 11:55:11 UTC 2021 x86_64 Linux
/etc/alpine-release:3.15.0
/etc/os-release:NAME="Alpine Linux"
/etc/os-release:ID=alpine
/etc/os-release:VERSION_ID=3.15.0
/etc/os-release:PRETTY_NAME="Alpine Linux v3.15"
/etc/os-release:HOME_URL="https://alpinelinux.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.alpinelinux.org/"

```

##### Netdata version

```cmd
Version: netdata v1.32.1-30-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--without-bundled-protobuf' '--with-bundled-lws' '--with-bundled-libJudy' 'CFLAGS=' 'LDFLAGS='
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                YES
    TLS Host Verification:      YES
    Machine Learning:           YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES static v3.2.2
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
```

##### Installation method

Docker, docker-compose (using the auto-generated "Add Node" docker and docker-compose strings)

##### Component Name

Netdata Cloud token claim process - When attempting to use either the docker or docker-compose script to start Netdata with the environment variables in place, the process fails with:

```cmd
"netdata.public.unique.id is not readable. Please make sure you have rights to read it (Filename: /var/lib/netdata/registry/netdata.public.unique.id)."
```

##### Steps To Reproduce

1. Install Netdata using docker-compose or docker with tokens in environment variables intact
2. Note constant cycling of "netdata.public.unique.id is not readable. Please make sure you have rights to read it (Filename: /var/lib/netdata/registry/netdata.public.unique.id)." in logs. 
3. (PARTIAL SUCCESS): If installing Netdata via Docker/Docker-compose **without** environment variables in place, installation works correctly but node is not claimed. 
4. If installing without environment variables in-place and trying to claim using the netdata-claim.sh script, note the same errors. Execution line: 

```cmd
docker exec -it netdata netdata-claim.sh -token=<token_removed> -rooms=<room-id-removed> -url=https://app.netdata.cloud
```

##### Expected behavior

1.) Expecting script to run successfully as per video example here: https://youtu.be/tMRHc9r2Jw4?t=30 or for install process to claim during node installation. 

2.) Not to see this:

```cmd
[root@dockerhost01 docker-compose]# docker exec -it netdata netdata-claim.sh -token=<token_removed> -rooms=<room_id_removed> -url=https://app.netdata.cloud
netdata.public.unique.id is not readable. Please make sure you have rights to read it (Filename: /var/lib/netdata/registry/netdata.public.unique.id).
```

3.) Connecting to the container console shows that the volume exists, the file exists, is in the correct location, has correct permissions and is readable: 

```cmd
bash-5.1# cat /var/lib/netdata/registry/netdata.public.unique.id 
619f5772-<REMOVED>-<REMOVED>-ca8628aa2ede
bash-5.1#

bash-5.1# cd /var/lib/netdata/registry/
bash-5.1# ls -la
total 12
drwxr-xr-x    2 root     root          4096 Dec 30 06:33 .
drwxrwx---    6 netdata  root          4096 Dec 30 06:58 ..
-rw-r--r--    1 root     root            36 Dec 30 06:33 netdata.public.unique.id
bash-5.1# pwd
/var/lib/netdata/registry
bash-5.1#
```

**Comment by chemist777** [comment]
Confirm. Have faced the same behavior.

**Comment by chemist777** [comment]
It can be related
```bash
csrv:~ # curl https://app.netdata.cloud -v
* Rebuilt URL to: https://app.netdata.cloud/
* Hostname was NOT found in DNS cache
*   Trying 35.196.244.138...
* Connected to app.netdata.cloud (35.196.244.138) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs/
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS alert, Server hello (2):
* SSL certificate problem: certificate has expired
* Closing connection 0
curl: (60) SSL certificate problem: certificate has expired
```

**Comment by ilyam8** [comment]
@chemist777, hi. Can you show your docker run command or docker-compose file?

The following command works for me (a note: had no `netdatalib`, `netdataconfig`, `netdatacache` volumes before, there were created during docker run). 

```bash
docker run -d --name=netdata \
  -p 19998:19999 \
  -v netdataconfig:/etc/netdata \
  -v netdatalib:/var/lib/netdata \
  -v netdatacache:/var/cache/netdata \
  -v /etc/passwd:/host/etc/passwd:ro \
  -v /etc/group:/host/etc/group:ro \
  -v /proc:/host/proc:ro \
  -v /sys:/host/sys:ro \
  -v /etc/os-release:/host/etc/os-release:ro \
  --restart unless-stopped \
  --cap-add SYS_PTRACE \
  --security-opt apparmor=unconfined \
  -e NETDATA_CLAIM_TOKEN=XXXX \
  -e NETDATA_CLAIM_URL=https://app.netdata.cloud \
  -e NETDATA_CLAIM_ROOMS=XXXX \
  netdata/netdata
```

**Comment by ilyam8** [comment]
> netdata.public.unique.id is not readable. Please make sure you have rights to read it (Filename: /var/lib/netdata/registry/netdata.public.unique.id).

comes from https://github.com/netdata/netdata/blob/5671a0c6359b643c4c725e167ae2702d9292e0fd/claim/netdata-claim.sh.in#L174-L176

**Comment by chemist777** [comment]
I use the following docker-compose file:

```yaml
version: '3.7'

services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: X.X.X.X
    ports:
      - "19999:19999"
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - {{ nd_path }}/data/etc:/etc/netdata
      - {{ nd_path }}/data/lib:/var/lib/netdata
      - {{ nd_path }}/data/cache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    environment:
      - NETDATA_CLAIM_TOKEN=XXX
      - NETDATA_CLAIM_URL=https://app.netdata.cloud
      - NETDATA_CLAIM_ROOMS=XXX
```

I tried to create nd_path with all possible rights (up to 0777) and owners. It didn't help.


```bash
csrv:/opt # openssl version
OpenSSL 1.0.1i-fips 6 Aug 2014
```

```bash
csrv:/opt # cat /etc/os-release 
NAME="openSUSE Leap"
VERSION="42.1"
VERSION_ID="42.1"
PRETTY_NAME="openSUSE Leap 42.1 (x86_64)"
ID=opensuse
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:opensuse:42.1"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://opensuse.org/"
ID_LIKE="suse"
```

**Comment by ilyam8** [comment]
@chemist777 hey. What is the reason you are using [bind mounts](https://docs.docker.com/storage/bind-mounts/) and not [volumes](https://docs.docker.com/storage/volumes/) for `/var/lib/netdata` and `/var/cache/netdata`?

**Comment by chemist777** [comment]
> @chemist777 hey. What is the reason you are using [bind mounts](https://docs.docker.com/storage/bind-mounts/) and not [volumes](https://docs.docker.com/storage/volumes/) for `/var/lib/netdata` and `/var/cache/netdata`?

Initially, I tried with the standard config with volumes. The error was the same. Then I switched to mounts to have more control and it didn't help.

**Comment by chemist777** [comment]
```
csrv:~ # docker --version
Docker version 20.10.1, build 831ebea
```

**Comment by ilyam8** [comment]
> Initially, I tried with the standard config with volumes.

@chemist777 Can you share your docker-compose file (with edited cloud token/rooms)? Having permissions errors when using docker volumes is not expected and I can't reproduce it.

**Comment by ilyam8** [comment]
> Install Netdata using docker-compose or docker with tokens in environment variables intact

@Veeedka if you are still interested in having this fixed, share the docker-compose file (if it differs from https://learn.netdata.cloud/docs/agent/claim#using-docker-compose).

**Comment by chemist777** [comment]
Sure. I cleaned up everything, also removed old volumes `docker-compose down -v`.

Created the following docker compose:
```yaml
version: '3'

services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: x.x.x.x
    ports:
      - "19999:19999"
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    environment:
      - NETDATA_CLAIM_TOKEN=xxx
      - NETDATA_CLAIM_URL=https://app.netdata.cloud
      - NETDATA_CLAIM_ROOMS=xxx
volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
```

Started it via `docker-compose up -d`.

And fetched logs `docker-compose logs`.

The results are:
```
csrv:/opt/ch/netdata # docker-compose logs
Attaching to netdata
netdata    | ls: /var/run/balena.sock: No such file or directory
netdata    | ls: /var/run/docker.sock: No such file or directory
netdata    | Unable to communicate with Netdata daemon, querying config from disk instead.
netdata    | Unable to communicate with Netdata daemon, querying config from disk instead.
netdata    | Token: ****************
netdata    | Base URL: https://app.netdata.cloud
netdata    | Id: xxx
netdata    | Rooms: xxx
netdata    | Hostname: x.x.x.x
netdata    | Proxy: 
netdata    | Netdata user: netdata
netdata    | No write permission in claiming working directory /var/lib/netdata/cloud.d
netdata    | ls: /var/run/balena.sock: No such file or directory
netdata    | ls: /var/run/docker.sock: No such file or directory
netdata    | Unable to communicate with Netdata daemon, querying config from disk instead.
netdata    | Unable to communicate with Netdata daemon, querying config from disk instead.
netdata    | netdata.public.unique.id is not readable. Please make sure you have rights to read it (Filename: /var/lib/netdata/registry/netdata.public.unique.id).
netdata    | ls: /var/run/balena.sock: No such file or directory
netdata    | ls: /var/run/docker.sock: No such file or directory
netdata    | Unable to communicate with Netdata daemon, querying config from disk instead.
netdata    | Unable to communicate with Netdata daemon, querying config from disk instead.
netdata    | netdata.public.unique.id is not readable. Please make sure you have rights to read it (Filename: /var/lib/netdata/registry/netdata.public.unique.id).
```
