### ISSUE TITLE
[Bug]: Strange behaviour very high use of storage at the start of the container

### ISSUE THREAD

**Issue by Whisper40** [netdata/netdata#12189]
### Bug description

I have 4 servers, on which Netdata is installed.
Today I got an alert from netdata:
disk_space._var_lib_netdata (/var/lib/netdata), disk space usage = 100%.
disk_space._var_cache_netdata (/var/cache/netdata), disk space usage = 100%.
disk_space._etc_netdata (/etc/netdata), disk space usage = 100%

Following this alert, I was noticed, and I saw that the / was complete, (its size is 30Gb, and there was 15Gb free just before the problem!)

To identify the problem, I looked for who was using so much storage and netdata turned out to be the container concerned.
I shut down the container and found that I had recovered the space.
When I restarted the container, a few minutes later, same problem, the storage filled up.
I don't understand what is causing this behaviour.
A few minutes after starting the container, the space used starts to slowly decrease!
![image](https://user-images.githubusercontent.com/30440458/154844515-a18e3e20-3fb6-4d32-8ced-04245b811bda.png)
![image](https://user-images.githubusercontent.com/30440458/154844527-8fef6145-5e61-41b0-bba4-e991dd1cd0b3.png)
![image](https://user-images.githubusercontent.com/30440458/154844531-c34a5563-7400-42b2-bd70-e1bf486fb842.png)

### Expected behavior

It should not fill the filesystem ( 15GB ! )

### Steps to reproduce

1. No idea..

### Installation method

docker

### System info

```shell

bash-5.1# uname -a; grep -HvE "^#|URL" /etc/*release
Linux s1 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 Linux
/etc/alpine-release:3.15.0
/etc/os-release:NAME="Alpine Linux"
/etc/os-release:ID=alpine
/etc/os-release:VERSION_ID=3.15.0
/etc/os-release:PRETTY_NAME="Alpine Linux v3.15"
bash-5.1# 


Version : 
netdata/netdata:stable
sha256:a6bb5b1856243fa62c8ffdd6baad282778c5705f0333f418a68afd9db6ecd566
```

### Netdata build info

```shell
bash-5.1# $(ps aux | grep -m1 -E -o "[a-zA-Z/]+netdata ") -W buildinfo
Version: netdata v1.33.1
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--without-bundled-protobuf' '--with-bundled-libJudy' 'CFLAGS=' 'LDFLAGS='
Install type: unknown
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
```

### Additional info
```
netdata:
    image: netdata/netdata:stable
    container_name: netdata
    restart: unless-stopped
    hostname: "${SERVER_BASE_URL}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.netdata-router.entrypoints=websecure"
      - "traefik.http.routers.netdata-router.service=netdata-service"
      - "traefik.http.routers.netdata-router.rule=Host(`${NETDATA_BASE_URL}-${SERVER_BASE_URL}.${DOMAIN_URL}`) "
      - "traefik.http.routers.netdata-router.tls=true"
      - "traefik.http.services.netdata-service.loadbalancer.server.port=19999"
      - "traefik.http.routers.netdata-router.middlewares=netdata-auth"
      - "traefik.http.middlewares.netdata-auth.basicauth.users=admin:${passwd_admin}"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - $CONFIG_DIR/netdata/config:/etc/netdata
      - $CONFIG_DIR/netdata/lib:/var/lib/netdata
      - $CONFIG_DIR/netdata/cache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /home:/data:ro
    environment:
      - TZ=${TZ}
      - NETDATA_CLAIM_TOKEN=${NETDATA_CLAIM_TOKEN}
      - NETDATA_CLAIM_URL=${NETDATA_CLAIM_URL}
      - NETDATA_CLAIM_ROOMS=${NETDATA_CLAIM_ROOMS}
    networks:
      - proxy
    ```
