### ISSUE TITLE
[Bug]: node.d snmp to go.d snmp doesn't work properly

### ISSUE THREAD

**Issue by Famku** [netdata/netdata#12860]
### Bug description

Hi,

I try to change my snmp config for my Mikrotik switch to go.d.

My old config for node.d worked perfectly for years:

```
{
    "enable_autodetect": false,
    "update_every": 10,
    "servers": [
        {
            "hostname": "192.168.1.21",
            "community": "public",
            "update_every": 2,
            "options": { "timeout": 20000, "version": 1 },
            "charts": {
                "snmp_switch.bandwidth_port": {
                    "title": "bandwidth for port ",
                    "titleoid": ".1.3.6.1.2.1.31.1.1.1.18.",
                    "units": "kilobits/s",
                    "type": "area",
                    "priority": 1,
                    "family": "ports",
                    "multiply_range": [ 1, 24 ],
                    "dimensions": {
                        "in": {
                            "oid": "1.3.6.1.2.1.2.2.1.10.",
                            "algorithm": "incremental",
                            "multiplier": 8,
                            "divisor": 1024,
                            "offset": 0
                        },
                        "out": {
                            "oid": "1.3.6.1.2.1.2.2.1.16.",
                            "algorithm": "incremental",
                            "multiplier": -8,
                            "divisor": 1024,
                            "offset": 0
                        }
                    }
                }
            }
        }
    ]
}
```

For go.d my config looks like this:

```
jobs:
  - name: switch
    update_every: 5
    hostname: "192.168.1.21"
    community: public
    options:
      version: 2
      timeout: 20
    charts:
      - id: "bandwidth_port"
        title: "Switch Bandwidth for port"
        titleoid": "1.3.6.1.2.1.31.1.1.1.18"
        units: "kilobits/s"
        type: "area"
        family: "ports"
        multiply_range: [1, 24]
        dimensions:
          - name: "in"
            oid: "1.3.6.1.2.1.2.2.1.10"
            algorithm: "incremental"
            multiplier: 8
            divisor: 1024
            offset: 0
          - name: "out"
            oid: "1.3.6.1.2.1.2.2.1.16"
            multiplier: -8
            divisor: 1024
            offset: 0
```

I checked this with ./go.d.plugin -d -m snmp and I can see all ports in the dashboard.

But units shows as "ports" with values that not make sense.

Can someone give me a hint what I doing wrong?

### Expected behavior

go.d snmp work the same way as node.d snmp 

### Steps to reproduce

sudo ./edit-config go.d/snmp.conf

enter config template from https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/modules/snmp)

change values

### Installation method

kickstart.sh

### System info

```shell
Linux docker2 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.4 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.4 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

### Netdata build info

```shell
Version: netdata v1.34.0-124-nightly
```
