### ISSUE TITLE
[Bug]: Not able to gather data from Unbound installed on a RasPi along with Pihole

### ISSUE THREAD

**Issue by jinetjose** [netdata/netdata#13079]
### Bug description

Unbound installed on a RasPi along with Pihole

pihole data is pulled correctly

followed this guide for setup (https://learn.netdata.cloud/guides/collect-unbound-metrics) , tried both manual and copy methods

still not able to plot the data 

unbound remote control working and "sudo unbound-control -c /etc/unbound/unbound.conf stats_noreset" returns 

```
thread0.num.queries=516
thread0.num.queries_ip_ratelimited=0
thread0.num.cachehits=189
thread0.num.cachemiss=327
thread0.num.prefetch=103
thread0.num.zero_ttl=97
thread0.num.recursivereplies=327
thread0.requestlist.avg=3.62558
thread0.requestlist.max=54
thread0.requestlist.overwritten=0
thread0.requestlist.exceeded=0
thread0.requestlist.current.all=0
thread0.requestlist.current.user=0
thread0.recursion.time.avg=1.441454
thread0.recursion.time.median=0.402749
thread0.tcpusage=0
thread1.num.queries=487
thread1.num.queries_ip_ratelimited=0
thread1.num.cachehits=218
thread1.num.cachemiss=269
thread1.num.prefetch=127
thread1.num.zero_ttl=125
thread1.num.recursivereplies=269
thread1.requestlist.avg=2.32071
thread1.requestlist.max=33
thread1.requestlist.overwritten=0
thread1.requestlist.exceeded=0
thread1.requestlist.current.all=0
thread1.requestlist.current.user=0
thread1.recursion.time.avg=1.479761
thread1.recursion.time.median=0.361873
thread1.tcpusage=0
total.num.queries=1003
total.num.queries_ip_ratelimited=0
total.num.cachehits=407
total.num.cachemiss=596
total.num.prefetch=230
total.num.zero_ttl=97
total.num.recursivereplies=596
total.requestlist.avg=3
total.requestlist.max=54
total.requestlist.overwritten=0
total.requestlist.exceeded=0
total.requestlist.current.all=0
total.requestlist.current.user=0
total.recursion.time.avg=1.458744
total.recursion.time.median=0.382311
total.tcpusage=0
time.now=1654524354.448339
time.up=2689.072960
time.elapsed=2689.072960
```

pi-hole shows unbound at 5335

![image](https://user-images.githubusercontent.com/67271356/172177680-d467657d-2b2f-4ded-9c27-fe83707b8519.png)

![image](https://user-images.githubusercontent.com/67271356/172179818-c0914855-fe31-46ae-ba9d-4d611550336d.png)

Netdata unbound.conf has

```yaml
jobs:
  - name: unbound
    address: 127.0.0.1:5335
    cumulative_stats: no
    use_tls: yes
    tls_skip_verify: yes
    tls_cert: /etc/unbound/unbound_control.pem
    tls_key: /etc/unbound/unbound_control.key

name: local
    address: 127.0.0.1:5335
    cumulative: yes
    use_tls: no
```

What am i doing wrong >?  Please help

### Expected behavior

Plot Unbound stats

https://user-images.githubusercontent.com/1153921/69659974-93160f00-103c-11ea-88e6-27e9efcf8c0d.png

### Steps to reproduce

1.Normal install 
2.
3.
...

### Installation method

from git

### System info

```shell
Ras pi running Debian Raspi Os
```

### Netdata build info

```shell
netdata
v1.34.0-279-nightly
```

### Additional info

Running on Ras pi with pihole using unbound and unbound configured using "/etc/unbound/unbound.conf.d/pi-hole.conf"

resolvconf for unbound running in the background .

**Comment by ilyam8** [comment]
Hi, @jinetjose. Can you try the [debug mode](https://github.com/netdata/go.d.plugin/tree/master/modules/unbound#troubleshooting)?

Netdata `unbound.conf` looks wrong: I think you need to delete

```yaml
name: local
    address: 127.0.0.1:5335
    cumulative: yes
    use_tls: no
```
