### ISSUE TITLE
[Bug]: Docker: stock config files location broken 

### ISSUE THREAD

**Issue by mmattel** [netdata/netdata#13389]
### Bug description

Just installed netdata via docker compose (using portainer) on a RPi using RaspOS64. Things are running fine but two issues occured.

* I was not able to start the container without setting in the compose file the DOCKER_USR/GRP info.
* The `netdataconfig` folder on the host contains an `orig` folder which linked to `orig -> /usr/lib/netdata/conf.d`, but orig is empty, no conf files are present and the link looks broken.

Taking a further look, I enabled in the compose file console access and found out, that when listing `/etc/netdata/orig --> /usr/lib/netdata/conf.d`, all required files are present.

As a next step, I additionally mounted via compose `/usr/lib/netdata/conf.d` to a local folder inside my home directory. The folder gets mounted on startup, but again the contents is empty. In addition, when accessing `/etc/netdata/orig` inside the container, no conf files were listed - just empty. Removing the conf.d mount from the compose file made all files reappear in `/etc/netdata/orig`.

Maybe I have done something wrong, but this looks strange to me.

### Expected behavior

Config stock files should appear in `orig` folder on the host.

### Steps to reproduce

See above

### Installation method

docker

### System info

```shell
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=debian
```

### Netdata build info

```shell
1.35.0-189-nightly
```

**Comment by ilyam8** [comment]
Hi, @mmattel. What are you trying to achieve? Can you show your docker-compose file?

> As a next step, I additionally mounted via compose /usr/lib/netdata/conf.d to a local folder inside my home directory.

If you want to overwrite stock use /etc/netdata.

**Comment by mmattel** [comment]
To answer the question about the reason why configuration changes are needed, simply add [temperature monitoring](https://learn.netdata.cloud/guides/monitor/pi-hole-raspberry-pi) to my RPi as described by netdata in the link.

I have found the solution and sorry to say, the documenttion has a lot of room for improvement...

**What is causing the problem**
The problem of two issues:

* There is a symlink  _inside_ the netdata container from `/etc/netdata/orig` --> `/usr/lib/netdata/conf.d`. When you mount as describe in the compose file on top `<your-host-path>/netdataconfig:/etc/netdata`, the symlink in that path still points to `/usr/lib/netdata/conf.d` which is not present on the host and therefore broken/inaccessible.

* When trying to additionally mount `/usr/lib/netdata/conf.d:/usr/lib/netdata/conf.d`, there is still no content inside `/usr/lib/netdata/conf.d` on the host (note that the symlinked orig directory resolves now)

**Solution**
The description in [Host Editable Configuration](https://learn.netdata.cloud/docs/agent/packaging/docker#host-editable-configuration) as linked above is wrong.
You have to do following steps to complete successfully.

Note that:
* the path to be created is `/usr/lib/netdata` and not `/usr/lib/netdata/conf.d`. Else your base directory is conf.d
* it is important to chown the netdata directory, else docker can`t write into it
* there is no changed composer file necessary, the one described on top is correct (beside other issues)
```
sudo mkdir -p /usr/lib/netdata
sudo chown <your-user>:<your-user> /usr/lib/netdata
docker run -d --name netdata_tmp netdata/netdata
docker cp netdata_tmp:/usr/lib/netdata/conf.d /usr/lib/netdata/
docker rm -f netdata_tmp
```
Post you have followed the steps and the container is up, you have a working orig symlink containing all the content necessary.

For reference, here is my compose file and as you can see, identical as described in your docker description (added the necessary environment: entry)

```
version: '3'
services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: <my-hostname> # set to fqdn of host
    # stdin_open: true     # comment if you do not need
    # tty: true            # comment if you do not need
    ports:
      - 19999:19999
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /home/<your-user>/netdata/netdataconfig:/etc/netdata
      - /home/<your-user>/netdata/netdatalib:/var/lib/netdata
      - /home/<your-user>/netdata/netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    environment:
      - DOCKER_USR=1000
      - DOCKER_GRP=1000
      - DO_NOT_TRACK=1
volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
```
