### ISSUE TITLE
[Bug]: `netdata` can not start with `containerd` configured as `LimitNOFILE=infinity`

### ISSUE THREAD

**Issue by zzvara** [netdata/netdata#13468]
### Bug description

Running Kubernetes sprayed using `kubespray` release `2.19`, that is, running Kubernetes `1.23.7` and `containerd` `1.6.6`.

`netdata` containers can not start up and the provide no logs.

However, changing `LimitNOFILE=Infinite` to `2000000` as follows:

```
[Unit]
Description=containerd container runtime
Documentation=https://containerd.io
After=network.target local-fs.target

[Service]
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/opt/bin/containerd

Type=notify
Delegate=yes
KillMode=process
Restart=always
RestartSec=5
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNPROC=infinity
LimitCORE=infinity
LimitNOFILE=20000000 // it was `infinity` before
# Comment TasksMax if your systemd version does not supports it.
# Only systemd 226 and above support this version.
TasksMax=infinity
OOMScoreAdjust=-999

[Install]
WantedBy=multi-user.target
```

and then `systemctl daemon-reload && systemctl restart containerd` on all nodes, then deleting all `netdata` Pods will fix the problem.

Netdata is installed as follows:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netdata
  namespace: system
spec:
  chart:
    spec:
      chart: netdata
      sourceRef:
        kind: HelmRepository
        name: netdata
      version: '3.7.22'
  interval: 30m0s
  suspend: false
  values:
    image:
      tag: latest
    ingress:
      enabled: false
    sd:
      child:
        enabled: false
    child:
      resources:
        requests:
          memory: 1200Mi
          cpu: 200m
        limits:
          memory: 1500Mi
          cpu: 800m
      configs:
        [...]
    parent:
      resources:
        requests:
          memory: 2500Mi
          cpu: 200m
        limits:
          memory: 3000Mi
          cpu: 800m
      database:
        storageclass: local
      alarms:
        storageclass: local
      configs:
        [...]
```

### Expected behavior

Netdata to start up.

### Steps to reproduce

See bug description.

### Installation method

helmchart (kubernetes)

### System info

```shell
sigma01 /etc/systemd/system # uname -a; grep -HvE "^#|URL" /etc/*release
Linux sigma01 5.15.55-flatcar #1 SMP Tue Jul 19 11:52:08 -00 2022 x86_64 Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz GenuineIntel GNU/Linux
/etc/lsb-release:DISTRIB_ID="Flatcar Container Linux by Kinvolk"
/etc/lsb-release:DISTRIB_RELEASE=3227.2.0
/etc/lsb-release:DISTRIB_CODENAME="Oklo"
/etc/lsb-release:DISTRIB_DESCRIPTION="Flatcar Container Linux by Kinvolk 3227.2.0 (Oklo)"
/etc/os-release:NAME="Flatcar Container Linux by Kinvolk"
/etc/os-release:ID=flatcar
/etc/os-release:ID_LIKE=coreos
/etc/os-release:VERSION=3227.2.0
/etc/os-release:VERSION_ID=3227.2.0
/etc/os-release:BUILD_ID=2022-07-19-1220
/etc/os-release:SYSEXT_LEVEL=1.0
/etc/os-release:PRETTY_NAME="Flatcar Container Linux by Kinvolk 3227.2.0 (Oklo)"
/etc/os-release:ANSI_COLOR="38;5;75"
/etc/os-release:FLATCAR_BOARD="amd64-usr"
/etc/os-release:CPE_NAME="cpe:2.3:o:flatcar-linux:flatcar_linux:3227.2.0:*:*:*:*:*:*:*"
```

### Netdata build info

```shell
See Helm chart version.
```
