### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by AvMavs** [netdata/netdata#13709]
### Bug description

I cannot deploy the Netdata container on docker.

Here's my docker compose:

```yaml
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: ${HOSTNAME}
    ports:
      - 19999:19999
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - ${CONFDIR}/netdata/config:/etc/netdata
      - ${CONFDIR}/netdata/config2:/var/lib/netdata
      - ${CACHEDIR}/netdata:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/host/etc/os-release:ro
```

It does not create all the files needed. I thought it might be permissions issue, so I tweaked around with that, but it still didn't work.

### Expected behavior

The container works and the web UI loads.

### Steps to reproduce

1. Use the docker compose file mentioned. (${} are mapped folders in the .env)
2. Launch the docker container.

### Installation method

docker

### System info

```shell
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=22.04
/etc/lsb-release:DISTRIB_CODENAME=jammy
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
/etc/os-release:PRETTY_NAME="Ubuntu 22.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="22.04"
/etc/os-release:VERSION="22.04.1 LTS (Jammy Jellyfish)"
/etc/os-release:VERSION_CODENAME=jammy
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=jammy
```

### Netdata build info

```shell
Netdata does not launch, so there is no build info.
```

### Additional info

Here are the logs:
```yaml
21/09/2022 10:12:29 pm2022-09-21 16:42:29: netdata INFO  : MAIN : EXIT: netdata prepares to exit with code 1...
21/09/2022 10:12:29 pm2022-09-21 16:42:29: netdata INFO  : MAIN : EXIT: cleaning up the database...
21/09/2022 10:12:29 pm2022-09-21 16:42:29: netdata INFO  : MAIN : Cleaning up database [0 hosts(s)]...
21/09/2022 10:12:29 pm2022-09-21 16:42:29: netdata INFO  : MAIN : EXIT: all done - netdata is now exiting - bye bye...
21/09/2022 10:12:55 pm2022-09-21 16:42:55: netdata INFO  : MAIN : CONFIG: cannot load cloud config '/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults.
21/09/2022 10:12:55 pm2022-09-21 16:42:55: netdata INFO  : MAIN : Using host prefix directory '/host'
21/09/2022 10:12:55 pm2022-09-21 16:42:55: netdata INFO  : MAIN : TIMEZONE: using strftime(): 'UTC'
21/09/2022 10:12:55 pm2022-09-21 16:42:55: netdata INFO  : MAIN : TIMEZONE: fixed as 'UTC'
21/09/2022 10:12:55 pm2022-09-21 16:42:55: netdata INFO  : MAIN : SIGNAL: Enabling reaper
21/09/2022 10:12:55 pm2022-09-21 16:42:55: netdata INFO  : MAIN : process tracking enabled.
21/09/2022 10:12:55 pm2022-09-21 16:42:55: netdata INFO  : MAIN : resources control: allowed file descriptors: soft = 1048576, max = 1048576
21/09/2022 10:12:55 pm2022-09-21 16:42:55: netdata INFO  : MAIN : Out-Of-Memory (OOM) score is already set to the wanted value 0
21/09/2022 10:12:55 pm2022-09-21 16:42:55: netdata ERROR : MAIN : Cannot adjust netdata scheduling policy to batch (3), with priority 0. Falling back to nice. (errno 38, Function not implemented)
21/09/2022 10:12:55 pm2022-09-21 16:42:55: netdata ERROR : MAIN : Cannot get my current process scheduling policy. (errno 38, Function not implemented)
21/09/2022 10:12:55 pm2022-09-21 16:42:55: netdata INFO  : MAIN : netdata started on pid 1.
21/09/2022 10:12:55 pm2022-09-21 16:42:55: netdata FATAL : netdata : Cannot create directory '/var/lib/netdata/registry'. # : Invalid argument
21/09/2022 10:12:55 pm
21/09/2022 10:12:55 pm2022-09-21 16:42:55: netdata INFO  : MAIN : EXIT: netdata prepares to exit with code 1...
21/09/2022 10:12:55 pm2022-09-21 16:42:55: netdata INFO  : MAIN : EXIT: cleaning up the database...
21/09/2022 10:12:55 pm2022-09-21 16:42:55: netdata INFO  : MAIN : Cleaning up database [0 hosts(s)]...
21/09/2022 10:12:55 pm2022-09-21 16:42:55: netdata INFO  : MAIN : EXIT: all done - netdata is now exiting - bye bye...
```
