### ISSUE TITLE
[Bug]: Unable to resolve Docker container names with socket proxy tcp

### ISSUE THREAD

**Issue by AmusingMallard** [netdata/netdata#14135]
### Bug description

I've set up Netdata as a Docker container on my Unraid server following the [documentation](https://learn.netdata.cloud/docs/agent/packaging/docker). 

I have a Docker socket proxy set up in a separate container that exposes the socket over a Docker network as `tcp://socket-proxy:2375`. This works for all other containers that requires access to the socket, but Netdata does not resolve Docker container names with this solution. It only shows the container ID's. This is my compose file:
```yaml
networks:
  socket-proxy:
    external: true
    name: socket-proxy
  reverse-proxy:
    external: true
    name: reverse-proxy
services:
  netdata:
    container_name: netdata
    image: netdata/netdata
    restart: unless-stopped
    hostname: #removed
    cap_add:
      - SYS_PTRACE
    networks:
      - socket-proxy
      - reverse-proxy
    ports:
      - 19999:19999
    security_opt:
      - apparmor:unconfined
    environment:
      - DOCKER_HOST=tcp://socket-proxy:2375
    volumes:
      - /mnt/user/appdata/netdata:/etc/netdata
      - /mnt/user/appdatanetdatalib:/var/lib/netdata
      - /mnt/user/appdatanetdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
```

The socket proxy compose contains the `CONTAINERS=1` environment variable as described in the documentation:
```yaml
networks:
  socket-proxy:
    external: true
    name: socket-proxy
services:
  socket-proxy:
    container_name: socket-proxy
    image: tecnativa/docker-socket-proxy
    restart: unless-stopped    
    privileged: true
    networks:
      - socket-proxy  
    ports:
      - 127.0.0.1:2375:2375
    environment:
      - CONTAINERS=1
      # removed rest of env variables
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

However, if I expose the socket directly, as described as the less secure solution in the documentation, it seems to work fine:
```yaml
networks:
  reverse-proxy:
    external: true
    name: reverse-proxy
services:
  netdata:
    container_name: netdata
    image: netdata/netdata
    restart: unless-stopped
    hostname: #removed
    cap_add:
      - SYS_PTRACE
    networks:
      - reverse-proxy
    ports:
      - 19999:19999
    security_opt:
      - apparmor:unconfined
    environment:
      - PGID=281
    volumes:
      - /mnt/user/appdata/netdata:/etc/netdata
      - /mnt/user/appdatanetdatalib:/var/lib/netdata
      - /mnt/user/appdatanetdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
```

### Expected behavior

I would expect Netdata to show container names instead of ID's.

### Steps to reproduce

1. Deploy Netdata and Docker socket proxy with provided Docker Compose files.
2. Open http://[IP]:19999
3. Observe that no container names are being resolved.

### Installation method

docker

### System info

```shell
Linux Tower 5.19.17-Unraid #2 SMP PREEMPT_DYNAMIC Wed Nov 2 11:54:15 PDT 2022 x86_64 AMD Ryzen 9 5900X 12-Core Processor AuthenticAMD GNU/Linux
/etc/os-release:NAME=Slackware
/etc/os-release:VERSION="15.0"
/etc/os-release:ID=slackware
/etc/os-release:VERSION_ID=15.0
/etc/os-release:PRETTY_NAME="Slackware 15.0 x86_64 (post 15.0 -current)"
/etc/os-release:ANSI_COLOR="0;34"
/etc/os-release:CPE_NAME="cpe:/o:slackware:slackware_linux:15.0"
/etc/os-release:VERSION_CODENAME=current
```

### Netdata build info

```shell
Version: netdata v1.37.0-42-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--without-bundled-protobuf' '--disable-dependency-tracking' '--disable-ebpf' 'CFLAGS=-O2 -pipe' 'LDFLAGS='
Install type: oci
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```
