### ISSUE TITLE
[Bug]: docker based netdata behind traefik not loading dashboard

### ISSUE THREAD

**Issue by kapuett** [netdata/netdata#14709]
### Bug description

Hi,

I am having an issue where only the background page is loaded and no dashboard is visible. I am using the latest nightly of netdata running via a docker compose file:
```
cat netdata.yaml 
version: "3"
services:
  netdata:
    container_name: netdata
    hostname: netdata
    image: netdata/netdata
    volumes:
      - "netdataconfig:/etc/netdata"
      - "netdatalib:/var/lib/netdata"
      - "netdatacache:/var/cache/netdata"
      - "/etc/passwd:/host/etc/passwd:ro"
      - "/etc/group:/host/etc/group:ro"
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/etc/os-release:/host/etc/os-release:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.netdata.rule=Host(`netdata.$myserver`)"
      - "traefik.http.services.netdata.loadbalancer.server.port=19999"
      - "traefik.http.routers.netdata.entrypoints=http"
      - "traefik.docker.network=proxy"
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    networks:
      - proxy
volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
networks:
  proxy:
    external: true
```
As you can see, I intend to use this behind a traefik reverse proxy. The setup is the same for e.g. pihole or nextcloud, both of which are working fine with similiar configs.

The issue I am seeing with netdata is when I am calling `http://netdata.$myserver` that no dashboard is visible, only the background:

![netdata_no_dash](https://user-images.githubusercontent.com/44997918/224483312-cf7587ea-17dd-49cd-8561-eb4fc4d6b791.png)
Checking developer settings in Firefox reveal the following message:
```
Loading failed for the <script> with source “http://netdata.$myserver/dashboard-react.js”. [netdata.$myserver:16:1](http://netdata.$myserver/)
Uncaught ReferenceError: NETDATA is not defined
    225 main.js:435
    p (index):16
    566 main.7d1bdca1.chunk.js:2
    p (index):16
    324 main.7d1bdca1.chunk.js:2
    p (index):16
    f (index):16
    e (index):16
    <anonymous> main.7d1bdca1.chunk.js:2
```
I am running this on a local server in my network and am trying to connect to it from a workstation on the same network:
```
user@workstation:~$ dig +short netdata.$myserver
10.0.0.111
```
I am not entirely sure whether this is a bug in itself, but I cannot find any info in the docs on how to run this behind traefik. And since it seems that the connection can be established, hence the background image, it is not entirely a traefik config issue?

### Expected behavior

Dashboards being visible, not only background image.

### Steps to reproduce

1. Run netdata in docker-compose.
2. Add traefik labels for local http connection
3. Connect to host set in HTTP router of respective traefik label

### Installation method

docker

### System info

```shell
Linux $myserver 5.15.0-48-generic #54~20.04.1-Ubuntu SMP Thu Sep 1 16:17:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=LinuxMint
/etc/lsb-release:DISTRIB_RELEASE=20.1
/etc/lsb-release:DISTRIB_CODENAME=ulyssa
/etc/lsb-release:DISTRIB_DESCRIPTION="Linux Mint 20.1 Ulyssa"
/etc/os-release:NAME="Linux Mint"
/etc/os-release:VERSION="20.1 (Ulyssa)"
/etc/os-release:ID=linuxmint
/etc/os-release:ID_LIKE=ubuntu
/etc/os-release:PRETTY_NAME="Linux Mint 20.1"
/etc/os-release:VERSION_ID="20.1"
/etc/os-release:VERSION_CODENAME=ulyssa
/etc/os-release:UBUNTU_CODENAME=focal
```

### Netdata build info

```shell
netdata:/# netdata -W buildinfo
Version: netdata v1.38.0-228-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--without-bundled-protobuf' '--disable-dependency-tracking' '--disable-ebpf' 'CFLAGS=-O2 -pipe' 'LDFLAGS='
Install type: oci
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```
