### ISSUE TITLE
[Feat]: Enhance the Alert Configurations to accept multiple lookups

### ISSUE THREAD

**Issue by sashwathn** [netdata/netdata#14913]
### Problem

Our Alert Configurations are complex and we need to find a way to simplify them.

### Description

We have a specific case where a user can use the results of an alert definition in another and this is extremely complex for users and also for us to create a meaningful UI on the Cloud.
As discussed with @ktsaou , @MrZammler can you please take a look at this and simplify our solution by:

- Accepting multiple lookups in an alert configuration
- The "lookup" tag to be used as is currently and the result to be available in $this
- The additional lookups to be accessible as variables

Eg:

```json
 template: inbound_packets_dropped_ratio
       on: net.packets
    class: Errors
     type: System
component: Network
       os: linux
    hosts: *
 families: !wl* *
   lookup: sum -10m unaligned absolute of received
   inbound_packets_dropped: sum -10m unaligned absolute of inbound
     calc: (($inbound_packets_dropped != nan AND $this > 10000) ? ($inbound_packets_dropped * 100 / $this) : (0))
    units: %
    every: 1m
     warn: $this >= 2
    delay: up 1m down 1h multiplier 1.5 max 2h
     info: ratio of inbound dropped packets for the network interface ${label:device} over the last 10 minutes
       to: sysadmin
```

### Importance

really want

### Value proposition

1. Simplifying Alert Configurations
2. Enabling the creation of a simple UI on the Cloud

...

**Comment by ralphm** [comment]
I support this idea in general. On the specific suggestion, I'd avoid introducing variable names as keys next to the other directives, as in the example. If we are moving towards YAML as a configuration format anyway, what about something like this:

```yaml
templates:
  - name: inbound_packets_dropped_ratio
    on: net.packets
    # ...
    lookups:
      this: sum -10m unaligned absolute of received
      inbound_packets_dropped: sum -10m unaligned absolute of inbound
    calc: (($inbound_packets_dropped != nan AND $this > 10000) ? ($inbound_packets_dropped * 100 / $this) : (0))
    # ...
```

This also makes `$this` explicit, and probably it should be `$inbound_packets_received` instead. Instead of `lookups` it could also be `vars` maybe.
