### ISSUE TITLE
Netdata w/ Docker Container not show Disk space utilization for mounts on https://app.netdata.cloud

### ISSUE THREAD

**Issue by allanext** [netdata/netdata#15202]
### Bug description

Using netdata official docker container (netdata/netdata) a partition mounted under /mnt/<name> is correctly mounted by netdata but the disk space utilization of those mounted volumes on https://app.netdata.cloud is not reported. The other metrics from the same server are reported.

The host runs Ubuntu 22.04.2 LTS and the same configuration works on Amazon Linux2.

I've looked at the issues #5071, #11498, #2408

The docker-compose.yml file:
```
version: '3'
services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: centaur.domain.org # set to fqdn of host
    ports:
      - 19999:19999
    restart: unless-stopped
    pid: host
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./netdata.conf:/etc/netdata/netdata.conf
      # Add the following if you want to monitor disk space of the host
      - /:/mnt/root:ro
      - /media/centaur-lcp-ssd:/mnt/centaur-lcp-ssd:ro
      - /media/centaur-krd-ssd:/mnt/centaur-krd-ssd:ro
      - /media/centaur-ltrhf-ssd:/mnt/centaur-ltrhf-ssd:ro
      - /media/centaur-data-ltrhf:/mnt/centaur-data-ltrhf:ro
      - /media/centaur-drl-ssd:/mnt/centaur-drl-ssd:ro
      - /media/centaur-data-tok:/mnt/centaur-data-tok:ro
      - /media/centaur-data:/mnt/centaur-data:ro
      - /media/centaur-data-drl:/mnt/centaur-data-drl:ro
      - /media/centaur-bckp:/mnt/centaur-bckp:ro
    environment:
      - PGID=133 #Set this from:  grep docker /etc/group | cut -d ':' -f 3
      # - DOCKER_USR=root
      - NETDATA_CLAIM_TOKEN=[TOKEN REMOVED]
      - NETDATA_CLAIM_URL=https://app.netdata.cloud
      - NETDATA_CLAIM_ROOMS=
volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
```

The netdata.conf file:
```
[plugin:proc:diskspace:/mnt/root]
  space usage = yes
[plugin:proc:diskspace:/mnt/centaur-lcp-ssd]
  space usage = yes
[plugin:proc:diskspace:/mnt/centaur-krd-ssd]
  space usage = yes
[plugin:proc:diskspace:/mnt/centaur-ltrhf-ssd]
  space usage = yes
[plugin:proc:diskspace:/mnt/centaur-data-ltrhf]
  space usage = yes
[plugin:proc:diskspace:/mnt/centaur-drl-ssd]
  space usage = yes
[plugin:proc:diskspace:/mnt/centaur-data-tok]
  space usage = yes
[plugin:proc:diskspace:/mnt/centaur-data]
  space usage = yes
[plugin:proc:diskspace:/mnt/centaur-data-drl]
  space usage = yes
[plugin:proc:diskspace:/mnt/centaur-bckp]
  space usage = yes
[plugin:proc:diskspace:/mnt/centaur-drl-ssd]
  space usage = yes
```
The configuration from the container related to diskspace:
```
centaur:/# curl -Ss 'http://localhost:19999/netdata.conf' | sed -n -e '/\[.*diskspace.*]/,/^$/p'

[plugin:proc:diskspace:/mnt/root]
	space usage = yes

[plugin:proc:diskspace:/mnt/centaur-lcp-ssd]
	space usage = yes
	# inodes usage = auto

[plugin:proc:diskspace:/mnt/centaur-krd-ssd]
	space usage = yes
	# inodes usage = auto

[plugin:proc:diskspace:/mnt/centaur-ltrhf-ssd]
	space usage = yes
	# inodes usage = auto

[plugin:proc:diskspace:/mnt/centaur-data-ltrhf]
	space usage = yes
	# inodes usage = auto

[plugin:proc:diskspace:/mnt/centaur-drl-ssd]
	space usage = yes
	# inodes usage = auto

[plugin:proc:diskspace:/mnt/centaur-data-tok]
	space usage = yes
	# inodes usage = auto

[plugin:proc:diskspace:/mnt/centaur-data]
	space usage = yes
	# inodes usage = auto

[plugin:proc:diskspace:/mnt/centaur-data-drl]
	space usage = yes
	# inodes usage = auto

[plugin:proc:diskspace:/mnt/centaur-bckp]
	space usage = yes
	# inodes usage = auto

[plugin:proc:diskspace]
	# remove charts of unmounted disks = yes
	# update every = 1
	# check for new mount points every = 15
	# exclude space metrics on paths = /proc/* /sys/* /var/run/user/* /run/user/* /snap/* /var/lib/docker/*
	# exclude space metrics on filesystems = *gvfs *gluster* *s3fs *ipfs *davfs2 *httpfs *sshfs *gdfs *moosefs fusectl autofs
	# exclude inode metrics on filesystems = msdosfs msdos vfat overlayfs aufs* *unionfs
	# space usage for all disks = auto
	# inodes usage for all disks = auto
...
```

### Expected behavior

I would expect to see on app.netdata.cloud the reporting of the disk space usage of the mounted volumes. It's working on the Amazon Linux 2 instances. I would consider a network issue if the other metrics from the same server were not being reported.

### Steps to reproduce

Run `docker compose up -d` with the above configuration

### Installation method

docker

### System info

```shell
Linux centaur 5.15.0-73-generic #80-Ubuntu SMP Mon May 15 15:18:26 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=22.04
/etc/lsb-release:DISTRIB_CODENAME=jammy
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
/etc/os-release:PRETTY_NAME="Ubuntu 22.04.2 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="22.04"
/etc/os-release:VERSION="22.04.2 LTS (Jammy Jellyfish)"
/etc/os-release:VERSION_CODENAME=jammy
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=jammy
```

### Netdata build info

```shell
centaur:/# netdata -W buildinfo
Version: netdata v1.38.0-342-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--without-bundled-protobuf' '--disable-dependency-tracking' '--disable-ebpf' 'CFLAGS=-O2 -pipe' 'LDFLAGS='
Install type: oci
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```
