### ISSUE TITLE
[Feat]: Request for `custom_numeric_fields`

### ISSUE THREAD

**Issue by ScottHelme** [netdata/netdata#16017]
### Description

The `custom_fields` feature counts patterns matches, but it can't be used with numeric values, and the `custom_time_fields` does work with numeric values, but it is only for timing values.

I might have an Nginx log format like: `'[$time_local] "$request" request_length=$request_length magic_number=$http_magic_number`

I would like to graph the `$request_length` and `$http_magic_number` values but neither `custom_fields` or `custom_time_fields` quite work.

### Importance

really want

### Value proposition

It would allow for logging and graphing of other numeric units than time (millis).

**Comment by ilyam8** [comment]
I added min/avg/max values for custom numeric fields in netdata/go.d.plugin#1343. Both `name` and `units` required:

```yaml
    custom_numeric_fields:
      - name: 'request_length'
        units: bytes
      - name: 'http_magic_number'
        units: number
```
