### ISSUE TITLE
[Bug]: Cannot run netdata on kubernetes

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#16151]
### Bug description

I want to deploy a netdata instance to play the role of parent for some of my VMs streaming to this parent, here is the statefulset manifest:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: netdata
  labels:
    app: netdata
    chart: netdata-3.7.73
    release: netdata-parent-c1
spec:
  serviceName: netdata
  replicas: 1
  selector:
    matchLabels:
      app: netdata
  template:
    metadata:
      labels:
        app: netdata
      annotations:
        checksum/config: 2934520b628fd17d675d749c951928f204fa5e82d6b9bbe3d9f3cea5ab3e89a7
    spec:
      containers:
      - name: netdata
        image: "netdata/netdata:v1.42.4"
        imagePullPolicy: Always
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - name: http
          containerPort: 19999
        livenessProbe:
          httpGet:
            path: /api/v1/info
            port: http
          initialDelaySeconds: 0
          failureThreshold: 3
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /api/v1/info
            port: http
          initialDelaySeconds: 0
          failureThreshold: 3
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
          - name: configmap
            mountPath: /etc/netdata/health_alarm_notify.conf
            subPath: health
          - name: configmap
            mountPath: /etc/netdata/netdata.conf
            subPath: netdata
          - name: configmap
            mountPath: /etc/netdata/stream.conf
            subPath: stream
          - name: netdata-database
            mountPath: /var/cache/netdata
          - name: netdata-alarms
            mountPath: /var/lib/netdata
        resources:
          limits:
            cpu: 4
            memory: 4096Mi
          requests:
            cpu: 4
            memory: 4096Mi

      volumes:
      - name: configmap
        configMap:
          name: netdata-conf
  volumeClaimTemplates:
  - metadata:
      name: netdata-database
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 7Gi
  - metadata:
      name: netdata-alarms
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Mi
```
But when I deploy this manifest, the pod keeps crashing with this error:
```
chmod: /: Operation not permitted
```
I don't have admin access on this cluster and pods cannot run as admin user or any other user id or group id below `1002660000`

### Expected behavior

it is OK if the netdata instance cannot monitor all metrics of itself, its primary goal is to host a few child instances

### Steps to reproduce

1. deploy netdata pod

### Installation method

other

### System info

```shell
pod is deployed on okd4
```

### Netdata build info

```shell
netdata version: v1.42.4
```
