### ISSUE TITLE
[Bug]: proposed Docker Swarm configuration is buggy

### ISSUE THREAD

**Issue by UnclePhil** [netdata/netdata#16307]
### Bug description

When we apply your docker-swarm proposed configuration for a specific agent, we have some warning  during the load, and  missing information about running containers. 

Due to this,  containers are not restarting on failure, and data are "unreadable"  

### Expected behavior

no warning, and readable data

### Steps to reproduce

1. have a working docker swarm cluster 
2. load your proposed configuration
3. check loading logs (you see many "not allowed" )
4. check data for container  ( you get the id of the container but not the complet id with service name)

### Installation method

docker

### System info

```shell
uname -a; grep -HvE "^#|URL" /etc/*release
Linux dlc06 5.10.0-26-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=debian

Server: Docker Engine - Community
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:32:16 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Netdata build info

```shell
The container is netdata/netdata:stable
4:51:14 > dk exec 92604db9b380 netdata -W buildinfo
Packaging:
    Netdata Version ____________________________________________ : v1.43.1
    Installation Type __________________________________________ : oci
    Package Architecture _______________________________________ : x86_64
    Package Distro _____________________________________________ : unknown

Problems in your proposed docker swarm stack
- "container_name: netdata"   is not allowed in swarm stack
- "restart: unless-stopped"   is not allowed in swarm stack 
- "SYS_ADMIN"  capabilities is missing
- access to the docker socker is missing
```

### Additional info

My working configuration

```
version: '3'
services:
  netdata:
    image: netdata/netdata:stable
    hostname: "{{.Node.Hostname}}" 
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /etc/hostname:/etc/hostname:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NETDATA_CLAIM_TOKEN=thetoken
      - NETDATA_CLAIM_URL=theurl
      - NETDATA_CLAIM_ROOMS=theroomid
      - DOCKER_USR=root
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:

```
