### ISSUE TITLE
[Feat]: Enable netdata configuration with environment variables

### ISSUE THREAD

**Issue by bluepuma77** [netdata/netdata#16491]
### Problem

I started with with netdata many years ago, it always has been a simple copy & play solution to use with Docker.

Now I simply want to run my netdata container, but need to set a config like `cleanup obsolete charts after secs`. Currently this is not possible without creating a config file, which needs extra handling, especially in a multi node environment.

### Description

It would be great if I can set a configuration by using the commonly used Docker method of env vars:
```
NETDATA_CONFIG_db_cleanup_obsolete_charts_after_secs=600
```

Full example:
```
docker run -d --name=netdata \
  -p $IP:19999:19999 \
  -v netdataconfig:/etc/netdata \
  -v netdatalib:/var/lib/netdata \
  -v netdatacache:/var/cache/netdata \
  -v /etc/passwd:/host/etc/passwd:ro \
  -v /etc/group:/host/etc/group:ro \
  -v /proc:/host/proc:ro \
  -v /sys:/host/sys:ro \
  -v /etc/os-release:/host/etc/os-release:ro \
  -v /var/run/docker.sock:/var/run/docker.sock:ro \
  -e DISABLE_TELEMETRY=0 \
  -e NETDATA_CLAIM_TOKEN=q3ZUOF...ssfBPQ  \
  -e NETDATA_CONFIG_db_cleanup_obsolete_charts_after_secs=600
  --hostname $(hostname) \
  --restart unless-stopped \
  --cap-add SYS_PTRACE \
  --security-opt apparmor=unconfined \
  --memory=4096m \
  --memory-swap=4096m \
  netdata/netdata:$V
```

### Importance

really want

### Value proposition

1. Enable simple configuration on the usual simple netdata container copy & play.

### Proposed implementation

The env var name could start with something like `NETDATA_CONFIG`, then use a separator like `_` or `___`, then the category name like `db`, then the separator again, then the config name, spaces replaced with `_`.

So it could be
`
NETDATA_CONFIG_db_cleanup_obsolete_charts_after_secs=600
`
or
 `
NETDATA_CONFIG___db___cleanup_obsolete_charts_after_secs=600
`

There are a few exceptions for which the underscore to space will not work, like
```
[plugin:proc:/proc/net/softnet_stat]
	# softnet_stat per core = yes
	# filename to monitor = /host/proc/net/softnet_stat
```
Maybe this can be disregarded as the main settings can be handled by the proposed solution.

**Comment by tkatsoulas** [comment]
I like the idea but I think the most straightforward way is to have everything in strict/uniform yaml format and an overwrite mechanism. It's on our TODO (the uniform yaml format, still a lot of work need to be done)

**Comment by bluepuma77** [comment]
Just to state again: this is about no (additional) config files, just plain config in the docker run or compose.

**Comment by bluepuma77** [comment]
I have another issue [here](https://github.com/netdata/netdata/issues/16412) and want to change a single config item. When looking at the documentation "Configure Agent containers" ([doc](https://learn.netdata.cloud/docs/installing/docker#configure-agent-containers)), its a laughable multi-step process, that doesn't even persist across container upgrades. 
```
docker exec -it netdata bash
cd /etc/netdata
./edit-config netdata.conf
```
And currently its even broken ([issue](https://github.com/netdata/netdata/issues/16557)) ;-)

So it would really be helpful to enable netdata configuration with environment variables, like
```
docker run -d --name=netdata \
  --pid=host \
  --network=host \
  -v $(pwd)/netdataconfig/netdata:/etc/netdata \
  -v netdatalib:/var/lib/netdata \
  -v netdatacache:/var/cache/netdata \
  -v /etc/passwd:/host/etc/passwd:ro \
  -v /etc/group:/host/etc/group:ro \
  -v /etc/localtime:/etc/localtime:ro \
  -v /proc:/host/proc:ro \
  -v /sys:/host/sys:ro \
  -v /etc/os-release:/host/etc/os-release:ro \
  -v /var/log:/host/var/log:ro \
  -v /var/run/docker.sock:/var/run/docker.sock:ro \
  -e NETDATA_CONFIG___db___cleanup_obsolete_charts_after_secs=600 \   <<<===
  --restart unless-stopped \
  --cap-add SYS_PTRACE \
  --cap-add SYS_ADMIN \
  --security-opt apparmor=unconfined \
  netdata/netdata
```

**Comment by bluepuma77** [comment]
One more thing about the env vars: the idea is to just be able to add a single parameter. Which should overwrite the existing one from the config file.

I tried to use a single parameter in a config file before, but `netdata` wouldn't let me have a config file with a single value, it wants the full thing. But that again is harder to maintain with, especially if it changes (adds new parameters) over time.

**Comment by ilyam8** [comment]
> wouldn't let me have a config file with a single value

What config? You can have a single value `netdata.conf`

**Comment by ilyam8** [comment]
Our current focus is to make Netdata configurable using UI. This is a nice request and I think it should be implemented, but I think it won't happen any time soon.

**Comment by ilyam8** [comment]
Closing because there is no plan to implement this 😞

**Comment by morgaesis** [comment]
Like @bluepuma77, I love Netdata and have used it for many years, but the "let's make deployment magic" is sometimes a bit too much. Like, does there even exist an official config file, with all the known configuration options? I don't want to `curl http://NODE:19999/netdata.conf ` or use a shonky `./edit-config` script inside a container exec.

Anyways, I wanted to limit public access to the web interface (which IMO should not be accessible by default). I think I found a workaround using the [Docker compose config-maps](https://docs.docker.com/reference/cli/docker/compose/config/)...


From the [Netdata docs](https://github.com/netdata/netdata/blob/4b4c22c388297af09e6862b0ff54d887eba9bb2c/packaging/docker/README.md#-using-the-docker-compose-command), modified to use static -- declarative config:

```yaml
services:
  netdata:
    image: netdata/netdata:stable
    container_name: netdata
    pid: host
    network_mode: host
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      # - netdataconfig:/etc/netdata # MODIFIED - Using 'configs' mount instead
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /:/host/root:ro,rslave
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /run/dbus:/run/dbus:ro
    environment: # MODIFIED - Don't put your secrets in your deployment config, load via `.env` file
      - NETDATA_CLAIM_TOKEN
      - NETDATA_CLAIM_URL
      - NETDATA_CLAIM_ROOMS
    configs: # MODIFIED - Mounting as config-map instead of volume/host mount
      - source: netdata.conf
        target: /etc/netdata/netdata.conf

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:

configs: # MODIFIED - Added config-map "mounts"
  netdata.conf:
    content: |
      [web]
          bind to = localhost:19999
```
