### ISSUE TITLE
Test for existing http response header

### ISSUE THREAD

**Issue by kingfisher77** [netdata/netdata#16662]
### Problem

We would like to test for the existence of a http response header.

### Description

http response header like "x-robots-tag: noindex,nofollow" could be tested e.g. for websites which should not be indexed by search engines.

### Importance

Important to have

### Value proposition

The quality of an automated application deployment also depends on the existence of http response headers. With this function in Netdata, this quality level can be better measured.

### Proposed implementation

Feature could be implemented as an addition to HTTP Endpoints.

**Comment by ilyam8** [comment]
Implemented in netdata/go.d.plugin#1451

<details>
<summary>Example configurations</summary>

```yaml
# "value" is a pattern, syntax: https://github.com/netdata/go.d.plugin/tree/master/pkg/matcher#supported-format


jobs:
    # The "X-Robots-Tag" header must be present in the HTTP response header,
    # but the value of the header does not matter.
    # This config checks for the presence of the header regardless of its value.
  - name: local
    url: http://127.0.0.1:8080
    header_match:
      - key: X-Robots-Tag

    # The "X-Robots-Tag" header must be present in the HTTP response header
    # only if its value is equal to "noindex, nofollow".
    # This config checks both the presence of the header and its value.
  - name: local
    url: http://127.0.0.1:8080
    header_match:
      - key: X-Robots-Tag
        value: '= noindex,nofollow'

    # The "X-Robots-Tag" header must not be present in the HTTP response header
    # but the value of the header does not matter.
    # This config checks for the presence of the header regardless of its value.
  - name: local
    url: http://127.0.0.1:8080
    header_match:
      - key: X-Robots-Tag
        exclude: yes

    # The "X-Robots-Tag" header must not be present in the HTTP response header
    # only if its value is equal to "noindex, nofollow".
    # This config checks both the presence of the header and its value.
  - name: local
    url: http://127.0.0.1:8080
    header_match:
      - key: X-Robots-Tag
        exclude: yes
        value: '= noindex,nofollow'

```

</details>

If you think I need to adjust something, feel free to comment.

**Comment by kingfisher77** [comment]
Hey, this is really cool. Can't wait to test it! We will report.

**Comment by ilyam8** [comment]
Should be available in today's nightly release (tomorrow).

**Comment by kingfisher77** [comment]
Thank you - is the new feature part of httpcheck? Should the config go into httpcheck.conf?

**Comment by ilyam8** [comment]
Yes, see configuration examples in https://github.com/netdata/netdata/issues/16662#issuecomment-1876023678.

**Comment by kingfisher77** [comment]
@ilyam8 It works, but without alert notification.

www-example-com does not have a x-robot--tag header.

```
# TEST: www.example.com shall expose a x-robots-tag
  - name: www-example-com-x-robots-tag
    url: https://www.example.com
    header_match:
      - key: X-Robots-Tag
        value: '= noindex,nofollow'
```
```
netdata@hostname:/usr/libexec/netdata/plugins.d$ ./go.d.plugin -d -m httpcheck
BEGIN 'httpcheck_www-example-com-x-robots-tag.request_status' 4999913
SET 'success' = 0
SET 'no_connection' = 0
SET 'timeout' = 0
SET 'redirect' = 0
SET 'bad_content' = 0
SET 'bad_status' = 0
SET 'bad_header' = 1
END
```

The chart shows a line and the 0 level. Expectation is to receive an alter notification. What do you think?

**Comment by ilyam8** [comment]
@kingfisher77 you are right, I forgot to add the alert. Added in #16736.

**Comment by kingfisher77** [comment]
Hi @ilyam8 The change in health.d/httpcheck.conf did not yet arrived. We are on v1.44.0-148-nightly. health.d/httpcheck.conf is still from 28.11. Do we miss something?

**Comment by ilyam8** [comment]
Are you using custom `health.d/httpcheck.conf`? Do you have it in `/etc/netdadta/`? Netdata prefers user configuration over stock: it ignores `/usr/lib/netdata/conf.d/health.d/httpcheck.conf` (updated version) if `/etc/netdadta/health.d/httpcheck.conf` is available. If so, you need to modify your `/etc/netdadta/health.d/httpcheck.conf`.

**Comment by kingfisher77** [comment]
I understand. Sorry for not thinking twice. I did indeed have a health.d/httpcheck.conf with no changes of my own. Maybe to try something out. Will keep an eye on the new feature now!

**Comment by kingfisher77** [comment]
Hi @ilyam8
is it possible to use HTTP authentication with header match also?

```
  - name: example-com-x-robots-tag
    url: https://example.com
    username: user
    password: password
    header_match:
      - key: X-Robots-Tag
        value: '= noindex,nofollow'
```

**Comment by kingfisher77** [comment]
The blank between the "=" and the value "noindex,nofollow" was to much in our case. Removing it started to work:

```
  - name: example-com-x-robots-tag
    url: https://example.com
    username: user
    password: password
    header_match:
      - key: X-Robots-Tag
        value: '=noindex,nofollow'
```

And: in our case ther eis no space between noindex and nofollow.

**Comment by kingfisher77** [comment]
Hi @ilyam8 
we believe we have some "ghost warnings" triggered by the new header_match function.

The job runs every 60 seconds. There is another job for the same URL. Is there possibly a connection with two jobs on the same URL?

```
  - name: www-example-com
    url: https://www.example.com
    headers:
      Server: Apache
    status_accepted:
      - 200
    update_every: 60
    timeout: 3
```
```
# www.example.com shall not expose a x-robots-tag
  - name: www-example-com-x-robots-tag
    url: https://www.example-com
    update_every: 60
    header_match:
      - key: X-Robots-Tag
        exclude: yes
```

Debug:
```
DBG module/job.go:251 skip the tick due to previous run hasn't been finished collector=httpcheck job=www-example-com
DBG module/job.go:251 skip the tick due to previous run hasn't been finished collector=httpcheck job=www-example-com-x-robots-tag
DBG httpcheck/collect.go:48 Get "https://www.exemple.com": context deadline exceeded (Client.Timeout exceeded while awaiting headers) collector=httpcheck job=www-example-com-x-robots-
tag
```


Alert email:
```
Alert: httpcheck_web_service_timeouts
Chart: httpcheck_www-example-com-x-robots-tag.request_status
Raised to warning, for 0 second
```
