### ISSUE TITLE
[Feat]: linux-systems/filesystem/zfs/zfs-pools: faulted device should raise warning

### ISSUE THREAD

**Issue by Finkregh** [netdata/netdata#18359]
### Problem

When a non-essential device on a ZFS pool fails it does not raise a warning

### Description

This is the current pool state:

```text
  pool: poolname
 state: ONLINE
status: One or more devices are faulted in response to persistent errors.
	Sufficient replicas exist for the pool to continue functioning in a
	degraded state.
action: Replace the faulted device, or use 'zpool clear' to mark the device
	repaired.
  scan: scrub repaired 0B in 06:08:51 with 0 errors on Mon Aug 12 06:39:14 2024
config:

	NAME                                          STATE     READ WRITE CKSUM
	poolname                                   ONLINE       0     0     0
	 mirror-0                                     ONLINE       0     0     0
	   ata-x-part2                              ONLINE       0     0     0
	   wwn-y-part2                           ONLINE       0     0     0
	logs	
	 mirror-1                                    ONLINE       0     0     0
	   wwn-z-part1                           ONLINE       0     0     0
	   wwn-a-part1                          FAULTED      3 2.71K     0  too many errors
	cache
	 wwn-z-part2                            ONLINE       0     0     0
	 wwn-a-part2                            ONLINE       5    85     0
```

This sould be an alert, as a disk has some issues.

### Importance

must have

### Value proposition

1. failing disks should be an alert, no matter the current impact

**Comment by ilyam8** [comment]
@Finkregh hey can you share

> `/usr/bin/zpool list -p -v`

**Comment by Finkregh** [comment]
@ilyam8 over night zfs detected that the device went away, so the output does not match anymore :/

```text
~ ❯ zpool list -p -v
NAME                                                   SIZE          ALLOC           FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
store                                         9981503995904  3045506252800  6935997743104        -         -      9     30   1.00  DEGRADED  -
  mirror-0                                    9981503995904  3045506252800  6935997743104        -         -      9     30      -    ONLINE
    ata-a-part2  9998683602944      -      -        -         -      -      -      -    ONLINE
    wwn-b-part2              9998683602944      -      -        -         -      -      -      -    ONLINE
logs                                              -      -      -        -         -      -      -      -         -
  mirror-1                                    17716740096  282624  17716457472        -         -      0      0      -  DEGRADED
    wwn-c-part1              17951621120      -      -        -         -      -      -      -    ONLINE
    wwn-d-part1              17951621120      -      -        -         -      -      -      -   UNAVAIL
cache                                             -      -      -        -         -      -      -      -         -
  wwn-c-part2                99000254464  87147356160  11848175616        -         -      0     88      -    ONLINE
  wwn-d-part2                99000254464  86305377280  12690158080        -         -      0     87      -    ONLINE
zroot                                          246960619520   186195750912    60764868608        -         -     67     75   1.00    ONLINE  -
  nvme0n1p2                                   249058820096  186195750912  60764868608        -         -     67     75      -    ONLINE
```

**Comment by ilyam8** [comment]
What are `logs` and `cache`? Asking because they don't have HEALTH.

**Comment by ilyam8** [comment]
Netdata doesn't collect vdev stats, only pools by executing `zpool list -p`. 

This issue is a request to collect the health status of vdevs. We can list vdevs by adding `-v`:

> [-v](https://openzfs.github.io/openzfs-docs/man/master/8/zpool-list.8.html#v)
Verbose statistics. Reports usage statistics for individual vdevs within the pool, in addition to the pool-wide statistics.

But I need to understand the output with `-v` to parse it. An alternative it to use [zpool-status](https://openzfs.github.io/openzfs-docs/man/master/8/zpool-status.8.html) but same problem.

**Comment by Finkregh** [comment]
```text
~ ❯ zpool list -p store
NAME            SIZE          ALLOC           FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
store  9981503995904  3046188658688  6935315337216        -         -      9     30   1.00  DEGRADED  -
~ ❯ zpool list -v -p -L store
NAME                                     SIZE          ALLOC           FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
store                           9981503995904  3046188658688  6935315337216        -         -      9     30   1.00  DEGRADED  -
  mirror-0                      9981503995904  3046188658688  6935315337216        -         -      9     30      -    ONLINE
    sdc2                        9998683602944      -      -        -         -      -      -      -    ONLINE
    sdd2                        9998683602944      -      -        -         -      -      -      -    ONLINE
logs                                -      -      -        -         -      -      -      -         -
  mirror-1                      17716740096  393216  17716346880        -         -      0      0      -  DEGRADED
    sdb1                        17951621120      -      -        -         -      -      -      -    ONLINE
    14807975228228307538            -      -      -        -         -      -      -      -   UNAVAIL
cache                               -      -      -        -         -      -      -      -         -
  sdb2                          99000254464  98755866624  239665152        -         -      0     99      -    ONLINE
  wwn-0x500151795954c095-part2      -      -      -        -         -      -      -      -   UNAVAIL
  ```
  
  As I said, it's _propery_ degraded now, so I dont know how much this will help :/

**Comment by Finkregh** [comment]
Ah, no problem :)

I don't get why the indentation is different with `zpool list -v -p -L` vs `zpool status`. The cache and log belong to the pool and are using a mirror.

I'd get the pools from something like `find /proc/spl/kstat/zfs/ -maxdepth 1 -type d` or `zpool list -H`, then `zpool list -v -p -L ${pool}`. That way, you know you see everything for each individual pool.

Full output:

```text
~ ❯ zpool list -p
NAME            SIZE          ALLOC           FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
store  9981503995904  3046184919040  6935319076864        -         -      9     30   1.00  DEGRADED  -
zroot   246960619520   187805274112    59155345408        -         -     67     76   1.00    ONLINE  -


~ ❯ /usr/lib/zfs/zpool_influxdb -n
zpool_stats,name=store,state=DEGRADED,vdev=root alloc=3046184919040u,free=6935319076864u,size=9981503995904u,read_bytes=6112837632u,read_errors=0u,read_ops=62786u,write_bytes=26905219072u,write_errors=0u,write_ops=639336u,checksum_errors=0u,fragmentation=0u 1724148803937595823
zpool_stats,name=store,state=ONLINE,vdev=root/mirror-0 alloc=3046184919040u,free=6935319076864u,size=9981503995904u,read_bytes=6112354304u,read_errors=0u,read_ops=62779u,write_bytes=26901913600u,write_errors=0u,write_ops=639244u,checksum_errors=0u,fragmentation=9u 1724148803937595823
zpool_stats,name=store,state=ONLINE,path=/dev/disk/by-id/ata-WDC_WD101EFBX-68B0AN0_VCHPR56P-part2,vdev=root/mirror-0/disk-0 alloc=0u,free=0u,size=0u,read_bytes=3057537024u,read_errors=0u,read_ops=31523u,write_bytes=13450956800u,write_errors=0u,write_ops=320025u,checksum_errors=0u,fragmentation=0u 1724148803937595823
zpool_stats,name=store,state=ONLINE,path=/dev/disk/by-id/wwn-0x5000cca0b0d7dea5-part2,vdev=root/mirror-0/disk-1 alloc=0u,free=0u,size=0u,read_bytes=3054817280u,read_errors=0u,read_ops=31256u,write_bytes=13450956800u,write_errors=0u,write_ops=319219u,checksum_errors=0u,fragmentation=0u 1724148803937595823
zpool_stats,name=store,state=DEGRADED,vdev=root/mirror-1 alloc=393216u,free=17716346880u,size=17716740096u,read_bytes=483328u,read_errors=0u,read_ops=7u,write_bytes=3305472u,write_errors=0u,write_ops=92u,checksum_errors=0u,fragmentation=0u 1724148803937595823
zpool_stats,name=store,state=ONLINE,path=/dev/disk/by-id/wwn-0x55cd2e414e0dc49b-part1,vdev=root/mirror-1/disk-0 alloc=0u,free=0u,size=0u,read_bytes=483328u,read_errors=0u,read_ops=7u,write_bytes=3305472u,write_errors=0u,write_ops=92u,checksum_errors=0u,fragmentation=0u 1724148803937595823
zpool_stats,name=store,state=UNAVAIL,path=/dev/disk/by-id/wwn-0x500151795954c095-part1,vdev=root/mirror-1/disk-1 alloc=0u,free=0u,size=0u,read_bytes=0u,read_errors=0u,read_ops=0u,write_bytes=0u,write_errors=0u,write_ops=0u,checksum_errors=0u,fragmentation=0u 1724148803937595823
zpool_vdev_stats,name=store,vdev=root sync_r_active_queue=0u,sync_w_active_queue=0u,async_r_active_queue=0u,async_w_active_queue=0u,async_scrub_active_queue=0u,rebuild_active_queue=0u,sync_r_pend_queue=0u,sync_w_pend_queue=0u,async_r_pend_queue=0u,async_w_pend_queue=0u,async_scrub_pend_queue=0u,rebuild_pend_queue=0u 1724148803937595823
zpool_scan_stats,function=scrub,name=store,state=finished end_ts=1724047650u,errors=0u,examined=3043960807424u,skipped=184233984u,issued=3043776573440u,pass_examined=1u,pass_issued=0u,paused_ts=0u,paused_t=0u,pct_done=99.96,processed=0u,rate=1u,remaining_t=0u,start_ts=1724025636u,to_examine=3045246664704u 1724148803937595823
zpool_stats,name=zroot,state=ONLINE,vdev=root alloc=187801116672u,free=59159502848u,size=246960619520u,read_bytes=8413913088u,read_errors=0u,read_ops=181737u,write_bytes=91937923072u,write_errors=0u,write_ops=3845541u,checksum_errors=0u,fragmentation=0u 1724148803938511878
zpool_stats,name=zroot,state=ONLINE,path=/dev/nvme0n1p2,vdev=root/disk-0 alloc=187801116672u,free=59159502848u,size=246960619520u,read_bytes=8413913088u,read_errors=0u,read_ops=181737u,write_bytes=91937923072u,write_errors=0u,write_ops=3845541u,checksum_errors=0u,fragmentation=67u 1724148803938511878
zpool_vdev_stats,name=zroot,vdev=root sync_r_active_queue=0u,sync_w_active_queue=0u,async_r_active_queue=0u,async_w_active_queue=0u,async_scrub_active_queue=0u,rebuild_active_queue=0u,sync_r_pend_queue=0u,sync_w_pend_queue=0u,async_r_pend_queue=0u,async_w_pend_queue=0u,async_scrub_pend_queue=0u,rebuild_pend_queue=0u 1724148803938511878
zpool_scan_stats,function=scrub,name=zroot,state=finished end_ts=1724027980u,errors=0u,examined=185831608320u,skipped=11808768u,issued=185819799552u,pass_examined=1u,pass_issued=0u,paused_ts=0u,paused_t=0u,pct_done=99.99,processed=0u,rate=1u,remaining_t=0u,start_ts=1724027770u,to_examine=185856024576u 1724148803938511878
```

**Comment by Finkregh** [comment]
Via https://github.com/openzfs/zfs/issues/2626

you might want to have a look at what the underlying code is: https://github.com/openzfs/zfs/blob/014265f4e6fa32b0a990525a0967b52164a94752/cmd/zpool/zpool_main.c#L2290

And this for proper structured output to get the pool structure:
```
~ ❯ zdb -C
store:
    version: 5000
    name: 'store'
    state: 0
    txg: 7234152
    pool_guid: 14462676634310329861
    errata: 0
    hostname: 'saturn'
    com.delphix:has_per_vdev_zaps
    vdev_children: 2
    vdev_tree:
        type: 'root'
        id: 0
        guid: 14462676634310329861
        create_txg: 4
        children[0]:
            type: 'mirror'
            id: 0
            guid: 2454726008370575413
            metaslab_array: 256
            metaslab_shift: 34
            ashift: 12
            asize: 9998678884352
            is_log: 0
            create_txg: 4
            com.delphix:vdev_zap_top: 129
            children[0]:
                type: 'disk'
                id: 0
                guid: 4736947967424156717
                path: '/dev/disk/by-id/ata-WDC_WD101EFBX-68B0AN0_VCHPR56P-part2'
                DTL: 83532
                create_txg: 4
                com.delphix:vdev_zap_leaf: 130
            children[1]:
                type: 'disk'
                id: 1
                guid: 4443630387662102480
                path: '/dev/disk/by-id/wwn-0x5000cca0b0d7dea5-part2'
                DTL: 83531
                create_txg: 4
                com.delphix:vdev_zap_leaf: 131
        children[1]:
            type: 'mirror'
            id: 1
            guid: 4740700489572691953
            metaslab_array: 77340
            metaslab_shift: 29
            ashift: 12
            asize: 17946902528
            is_log: 1
            create_txg: 2247055
            com.delphix:vdev_zap_top: 77028
            children[0]:
                type: 'disk'
                id: 0
                guid: 8783083823540766932
                path: '/dev/disk/by-id/wwn-0x55cd2e414e0dc49b-part1'
                whole_disk: 0
                DTL: 153963
                create_txg: 2247055
                com.delphix:vdev_zap_leaf: 77029
            children[1]:
                type: 'disk'
                id: 1
                guid: 14807975228228307538
                path: '/dev/disk/by-id/wwn-0x500151795954c095-part1'
                whole_disk: 0
                DTL: 153962
                create_txg: 2247055
                com.delphix:vdev_zap_leaf: 77030
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
zroot:
    version: 5000
    name: 'zroot'
    state: 0
    txg: 8826417
    pool_guid: 13894294399726042361
    errata: 0
    hostname: 'archlinux'
    com.delphix:has_per_vdev_zaps
    vdev_children: 1
    vdev_tree:
        type: 'root'
        id: 0
        guid: 13894294399726042361
        create_txg: 4
        children[0]:
            type: 'disk'
            id: 0
            guid: 4777259651286273977
            path: '/dev/nvme0n1p2'
            whole_disk: 0
            metaslab_array: 256
            metaslab_shift: 31
            ashift: 12
            asize: 249054101504
            is_log: 0
            DTL: 3397
            create_txg: 4
            com.delphix:vdev_zap_leaf: 129
            com.delphix:vdev_zap_top: 130
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
```
