### ISSUE TITLE
[Bug]: No CPU Temperature in Netdata Cloud UI

### ISSUE THREAD

**Issue by cacraig** [netdata/netdata#18396]
### Bug description

A recent update removed CPU temperatures from the netdata cloud UI. 

### Expected behavior

Should show CPU temperature chart.

### Steps to reproduce

1. Login. Select any monitor -> No CPU Temperature.

### Installation method

kickstart.sh

### System info

```shell
Linux redacted_server_name123 6.5.0-25-generic #25~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Feb 20 16:09:15 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=22.04
/etc/lsb-release:DISTRIB_CODENAME=jammy
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 22.04.4 LTS"
/etc/os-release:PRETTY_NAME="Ubuntu 22.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="22.04"
/etc/os-release:VERSION="22.04.4 LTS (Jammy Jellyfish)"
/etc/os-release:VERSION_CODENAME=jammy
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=jammy
```

### Netdata build info

```shell
Packaging:
    Netdata Version ____________________________________________ : v1.46.3
    Installation Type __________________________________________ : binpkg-deb
    Package Architecture _______________________________________ : x86_64
    Package Distro _____________________________________________ : ubuntu 22.04
    Configure Options __________________________________________ : dummy-configure-command
Default Directories:
    User Configurations ________________________________________ : /etc/netdata
    Stock Configurations _______________________________________ : /usr/lib/netdata/conf.d
    Ephemeral Databases (metrics data, metadata) _______________ : /var/cache/netdata
    Permanent Databases ________________________________________ : /var/lib/netdata
    Plugins ____________________________________________________ : /usr/libexec/netdata/plugins.d
    Static Web Files ___________________________________________ : /usr/share/netdata/web
    Log Files __________________________________________________ : /var/log/netdata
    Lock Files _________________________________________________ : /var/lib/netdata/lock
    Home _______________________________________________________ : /var/lib/netdata
Operating System:
    Kernel _____________________________________________________ : Linux
    Kernel Version _____________________________________________ : 6.5.0-25-generic
    Operating System ___________________________________________ : Ubuntu
    Operating System ID ________________________________________ : ubuntu
    Operating System ID Like ___________________________________ : debian
    Operating System Version ___________________________________ : 22.04.4 LTS (Jammy Jellyfish)
    Operating System Version ID ________________________________ : none
    Detection __________________________________________________ : /etc/os-release
Hardware:
    CPU Cores __________________________________________________ : 128
    CPU Frequency ______________________________________________ : 3720000000
    RAM Bytes __________________________________________________ : 270072205312
    Disk Capacity ______________________________________________ : 12802494652416
    CPU Architecture ___________________________________________ : x86_64
    Virtualization Technology __________________________________ : none
    Virtualization Detection ___________________________________ : systemd-detect-virt
Container:
    Container __________________________________________________ : none
    Container Detection ________________________________________ : systemd-detect-virt
    Container Orchestrator _____________________________________ : none
    Container Operating System _________________________________ : none
    Container Operating System ID ______________________________ : none
    Container Operating System ID Like _________________________ : none
    Container Operating System Version _________________________ : none
    Container Operating System Version ID ______________________ : none
    Container Operating System Detection _______________________ : none
Features:
    Built For __________________________________________________ : Linux
    Netdata Cloud ______________________________________________ : YES
    Health (trigger alerts and send notifications) _____________ : YES
    Streaming (stream metrics to parent Netdata servers) _______ : YES
    Back-filling (of higher database tiers) ____________________ : YES
    Replication (fill the gaps of parent Netdata servers) ______ : YES
    Streaming and Replication Compression ______________________ : YES (zstd lz4 gzip)
    Contexts (index all active and archived metrics) ___________ : YES
    Tiering (multiple dbs with different metrics resolution) ___ : YES (5)
    Machine Learning ___________________________________________ : YES
Database Engines:
    dbengine (compression) _____________________________________ : YES (zstd lz4)
    alloc ______________________________________________________ : YES
    ram ________________________________________________________ : YES
    none _______________________________________________________ : YES
Connectivity Capabilities:
    ACLK (Agent-Cloud Link: MQTT over WebSockets over TLS) _____ : YES
    static (Netdata internal web server) _______________________ : YES
    h2o (web server) ___________________________________________ : YES
    WebRTC (experimental) ______________________________________ : NO
    Native HTTPS (TLS Support) _________________________________ : YES
    TLS Host Verification ______________________________________ : YES
Libraries:
    LZ4 (extremely fast lossless compression algorithm) ________ : YES
    ZSTD (fast, lossless compression algorithm) ________________ : YES
    zlib (lossless data-compression library) ___________________ : YES
    Brotli (generic-purpose lossless compression algorithm) ____ : NO
    protobuf (platform-neutral data serialization protocol) ____ : YES (system)
    OpenSSL (cryptography) _____________________________________ : YES
    libdatachannel (stand-alone WebRTC data channels) __________ : NO
    JSON-C (lightweight JSON manipulation) _____________________ : YES
    libcap (Linux capabilities system operations) ______________ : NO
    libcrypto (cryptographic functions) ________________________ : YES
    libyaml (library for parsing and emitting YAML) ____________ : YES
Plugins:
    apps (monitor processes) ___________________________________ : YES
    cgroups (monitor containers and VMs) _______________________ : YES
    cgroup-network (associate interfaces to CGROUPS) ___________ : YES
    proc (monitor Linux systems) _______________________________ : YES
    tc (monitor Linux network QoS) _____________________________ : YES
    diskspace (monitor Linux mount points) _____________________ : YES
    freebsd (monitor FreeBSD systems) __________________________ : NO
    macos (monitor MacOS systems) ______________________________ : NO
    statsd (collect custom application metrics) ________________ : YES
    timex (check system clock synchronization) _________________ : YES
    idlejitter (check system latency and jitter) _______________ : YES
    bash (support shell data collection jobs - charts.d) _______ : YES
    debugfs (kernel debugging metrics) _________________________ : YES
    cups (monitor printers and print jobs) _____________________ : YES
    ebpf (monitor system calls) ________________________________ : YES
    freeipmi (monitor enterprise server H/W) ___________________ : YES
    nfacct (gather netfilter accounting) _______________________ : YES
    perf (collect kernel performance events) ___________________ : YES
    slabinfo (monitor kernel object caching) ___________________ : YES
    Xen ________________________________________________________ : YES
    Xen VBD Error Tracking _____________________________________ : NO
    Logs Management ____________________________________________ : NO
Exporters:
    AWS Kinesis ________________________________________________ : NO
    GCP PubSub _________________________________________________ : NO
    MongoDB ____________________________________________________ : YES
    Prometheus (OpenMetrics) Exporter __________________________ : YES
    Prometheus Remote Write ____________________________________ : YES
    Graphite ___________________________________________________ : YES
    Graphite HTTP / HTTPS ______________________________________ : YES
    JSON _______________________________________________________ : YES
    JSON HTTP / HTTPS __________________________________________ : YES
    OpenTSDB ___________________________________________________ : YES
    OpenTSDB HTTP / HTTPS ______________________________________ : YES
    All Metrics API ____________________________________________ : YES
    Shell (use metrics in shell scripts) _______________________ : YES
Debug/Developer Features:
    Trace All Netdata Allocations (with charts) ________________ : NO
    Developer Mode (more runtime checks, slower) _______________ : NO
```

**Comment by ilyam8** [comment]
Hi. It is Hardware->Sensors.

**Comment by cacraig** [comment]
Hi. @ilyam8  - It is not there. 

<img width="285" alt="Screenshot 2024-08-23 at 3 51 12 PM" src="https://github.com/user-attachments/assets/f367f545-ead7-4863-a04f-46e044a264b1">

It's not there on any monitors. Is there some other place where you have to enable these?

**Comment by ilyam8** [comment]
Try https://learn.netdata.cloud/docs/collecting-metrics/hardware-devices-and-sensors/linux-sensors-lm-sensors#troubleshooting

**Comment by cacraig** [comment]
@ilyam8 - Can you be a little more specific? Is it a requirement now to install lm-sensors / and run the sensor detection command? I tried running these, and it still doesn't work. CPU temperature was showing up perfectly fine as of about a week ago. Now it doesn't show up in any monitor... I really don't think you guys should close tickets without verifying if there is actually an issue...

**Comment by cacraig** [comment]
I'm not sure what version this broke - we have auto updates enabled. 

I tried changing the date range, and the only thing I could find was "Sensors (obsolete)". 
<img width="1334" alt="Screenshot 2024-08-28 at 4 33 42 PM" src="https://github.com/user-attachments/assets/de45feaf-f87d-4ea0-9646-0e7f45b08eea">

But I don't think this is it. I remember it being pretty clearly: CPU -> Temperature. 

Either way, the fact is that there is no chart for CPU temperature on any of our current 13 monitors. There most certainly was one, and there should be one now. I'm not sure if there is some lever we need to pull to make this work, but it really should be automatic. CPU temperature is pretty important to monitor.

**Comment by cacraig** [comment]
Additionally, the Sensors -> Temperature chart shows a temperature, but it is certainly not CPU temperature. 
<img width="1366" alt="Screenshot 2024-08-28 at 4 39 16 PM" src="https://github.com/user-attachments/assets/0b4847df-9089-47b7-a65a-f445f95b92b9">

the output of sensors command: 
```
sensors
k10temp-pci-00c3
Adapter: PCI adapter
Tctl:         +47.0°C
Tccd1:        +43.8°C
Tccd2:        +41.8°C
Tccd3:        +40.5°C
Tccd4:        +46.0°C
Tccd5:        +45.8°C
Tccd6:        +42.5°C
Tccd7:        +42.0°C
Tccd8:        +45.0°C

nvme-pci-0100
Adapter: PCI adapter
Composite:    +46.9°C  (low  = -273.1°C, high = +74.8°C)
                       (crit = +79.8°C)
Sensor 1:     +50.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 2:     +46.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 3:     +42.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 4:     +43.9°C  (low  = -273.1°C, high = +65261.8°C)

nct6779-isa-0290
Adapter: ISA adapter
Vcore:                 568.00 mV (min =  +0.00 V, max =  +1.74 V)
in1:                   216.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
AVCC:                    3.39 V  (min =  +2.98 V, max =  +3.63 V)
+3.3V:                   3.38 V  (min =  +2.98 V, max =  +3.63 V)
in4:                     1.79 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in5:                   880.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
in6:                     2.04 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
3VSB:                    3.39 V  (min =  +2.98 V, max =  +3.63 V)
Vbat:                    3.26 V  (min =  +2.70 V, max =  +3.63 V)
in9:                     0.00 V  (min =  +0.00 V, max =  +0.00 V)
in10:                  848.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
in11:                  768.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
in12:                    1.70 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in13:                  896.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
in14:                  720.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
fan1:                     0 RPM  (min =    0 RPM)
fan2:                     0 RPM  (min =    0 RPM)
fan3:                     0 RPM  (min =    0 RPM)
fan5:                     0 RPM  (min =    0 RPM)
SYSTIN:                 +31.0°C  (high =  +0.0°C, hyst =  +0.0°C)  ALARM  sensor = thermistor
CPUTIN:                 +40.0°C  (high = +80.0°C, hyst = +75.0°C)  sensor = thermistor
AUXTIN0:                -62.0°C    sensor = thermistor
AUXTIN1:                +34.0°C    sensor = thermistor
AUXTIN2:                +39.0°C    sensor = thermistor
AUXTIN3:                +42.0°C    sensor = thermistor
PCH_CHIP_CPU_MAX_TEMP:   +0.0°C
PCH_CHIP_TEMP:           +0.0°C
PCH_CPU_TEMP:            +0.0°C
PCH_MCH_TEMP:            +0.0°C
intrusion0:            ALARM
intrusion1:            ALARM
beep_enable:           disabled
```

**Comment by ilyam8** [comment]
@cacraig I believe we didn't have a dedicated CPU temperature collector. Netdata gathers various system sensor statistics, such as temperature, voltage, current, and power. These sensors might include CPU temperature readings, though it is not always clear from the sensor names (e.g., [k10temp](https://docs.kernel.org/hwmon/k10temp.html)). The data collection methods include:

1. [sensors](https://linux.die.net/man/1/sensors) binary **or**
2. scanning [sysfs](https://www.kernel.org/doc/Documentation/hwmon/sysfs-interface)

The chart displays the maximum temperature across all sensors. You can change Goup By: select "label: chip" and "label: feature" to get statistics for each sensor:

<img width="1369" alt="Screenshot 2024-08-30 at 13 01 32" src="https://github.com/user-attachments/assets/af1705db-a527-4add-8806-7ec3d16f3d31">

Additionally, I added a table with sensors stats to simplify viewing:

<img width="1232" alt="Screenshot 2024-08-30 at 13 04 17" src="https://github.com/user-attachments/assets/9ee6bbf8-83eb-4a15-8034-1a4efe2c0e10">

**Comment by ilyam8** [comment]
I know you can relabel sensors (change a name to something more meaningful) but I never did it myself. @Ferroin did you do it?

**Comment by ilyam8** [comment]
@cacraig btw can you please share `sensors -A -u` output?

**Comment by cacraig** [comment]
@ilyam8 - 
```
sensors -A -u
k10temp-pci-00c3
Tctl:
  temp1_input: 41.000
Tccd1:
  temp3_input: 40.750
Tccd2:
  temp4_input: 37.500
Tccd3:
  temp5_input: 37.250
Tccd4:
  temp6_input: 37.750
Tccd5:
  temp7_input: 39.500
Tccd6:
  temp8_input: 39.000
Tccd7:
  temp9_input: 40.000
Tccd8:
  temp10_input: 38.000

nvme-pci-0100
Composite:
  temp1_input: 46.850
  temp1_max: 74.850
  temp1_min: -273.150
  temp1_crit: 79.850
  temp1_alarm: 0.000
Sensor 1:
  temp2_input: 50.850
  temp2_max: 65261.850
  temp2_min: -273.150
Sensor 2:
  temp3_input: 46.850
  temp3_max: 65261.850
  temp3_min: -273.150
Sensor 3:
  temp4_input: 43.850
  temp4_max: 65261.850
  temp4_min: -273.150
Sensor 4:
  temp5_input: 43.850
  temp5_max: 65261.850
  temp5_min: -273.150

nct6779-isa-0290
Vcore:
  in0_input: 0.592
  in0_min: 0.000
  in0_max: 1.744
  in0_alarm: 0.000
  in0_beep: 0.000
in1:
  in1_input: 0.216
  in1_min: 0.000
  in1_max: 0.000
  in1_alarm: 1.000
  in1_beep: 0.000
AVCC:
  in2_input: 3.392
  in2_min: 2.976
  in2_max: 3.632
  in2_alarm: 0.000
  in2_beep: 0.000
+3.3V:
  in3_input: 3.376
  in3_min: 2.976
  in3_max: 3.632
  in3_alarm: 0.000
  in3_beep: 0.000
in4:
  in4_input: 1.800
  in4_min: 0.000
  in4_max: 0.000
  in4_alarm: 1.000
  in4_beep: 0.000
in5:
  in5_input: 0.888
  in5_min: 0.000
  in5_max: 0.000
  in5_alarm: 1.000
  in5_beep: 0.000
in6:
  in6_input: 2.040
  in6_min: 0.000
  in6_max: 0.000
  in6_alarm: 1.000
  in6_beep: 0.000
3VSB:
  in7_input: 3.392
  in7_min: 2.976
  in7_max: 3.632
  in7_alarm: 0.000
  in7_beep: 0.000
Vbat:
  in8_input: 3.248
  in8_min: 2.704
  in8_max: 3.632
  in8_alarm: 0.000
  in8_beep: 0.000
in9:
  in9_input: 0.000
  in9_min: 0.000
  in9_max: 0.000
  in9_alarm: 0.000
  in9_beep: 0.000
in10:
  in10_input: 0.880
  in10_min: 0.000
  in10_max: 0.000
  in10_alarm: 1.000
  in10_beep: 0.000
in11:
  in11_input: 0.768
  in11_min: 0.000
  in11_max: 0.000
  in11_alarm: 1.000
  in11_beep: 0.000
in12:
  in12_input: 1.704
  in12_min: 0.000
  in12_max: 0.000
  in12_alarm: 1.000
  in12_beep: 0.000
in13:
  in13_input: 0.896
  in13_min: 0.000
  in13_max: 0.000
  in13_alarm: 1.000
  in13_beep: 0.000
in14:
  in14_input: 0.728
  in14_min: 0.000
  in14_max: 0.000
  in14_alarm: 1.000
  in14_beep: 0.000
fan1:
  fan1_input: 0.000
  fan1_min: 0.000
  fan1_alarm: 0.000
  fan1_beep: 0.000
  fan1_pulses: 2.000
fan2:
  fan2_input: 0.000
  fan2_min: 0.000
  fan2_alarm: 0.000
  fan2_beep: 0.000
  fan2_pulses: 2.000
fan3:
  fan3_input: 0.000
  fan3_min: 0.000
  fan3_alarm: 0.000
  fan3_beep: 0.000
  fan3_pulses: 2.000
fan5:
  fan5_input: 0.000
  fan5_min: 0.000
  fan5_alarm: 0.000
  fan5_beep: 0.000
  fan5_pulses: 2.000
SYSTIN:
  temp1_input: 30.000
  temp1_max: 0.000
  temp1_max_hyst: 0.000
  temp1_alarm: 1.000
  temp1_type: 4.000
  temp1_offset: 0.000
  temp1_beep: 0.000
CPUTIN:
  temp2_input: 36.500
  temp2_max: 80.000
  temp2_max_hyst: 75.000
  temp2_alarm: 0.000
  temp2_type: 4.000
  temp2_offset: 0.000
  temp2_beep: 0.000
AUXTIN0:
  temp3_input: -62.000
  temp3_type: 4.000
  temp3_offset: 0.000
AUXTIN1:
  temp4_input: 33.000
  temp4_type: 4.000
  temp4_offset: 0.000
AUXTIN2:
  temp5_input: 38.000
  temp5_type: 4.000
  temp5_offset: 0.000
AUXTIN3:
  temp6_input: 41.000
  temp6_type: 4.000
  temp6_offset: 0.000
PCH_CHIP_CPU_MAX_TEMP:
  temp7_input: 0.000
PCH_CHIP_TEMP:
  temp8_input: 0.000
PCH_CPU_TEMP:
  temp9_input: 0.000
PCH_MCH_TEMP:
  temp10_input: 0.000
PCH_DIM0_TEMP:
  temp11_input: 0.000
PCH_DIM1_TEMP:
  temp12_input: 0.000
intrusion0:
  intrusion0_alarm: 1.000
  intrusion0_beep: 0.000
intrusion1:
  intrusion1_alarm: 1.000
  intrusion1_beep: 0.000
beep_enable:
  beep_enable: 0.000
```
