### ISSUE TITLE
[Bug]: go.d/snmp error msg="check failed: no system name"

### ISSUE THREAD

**Issue by djrm05** [netdata/netdata#18969]
### Bug description

some snmp jobs stopped working for me after update to latest stable v2.0.
I have isolated the job which is failing and debugging snmp it is saying "check failed: no system name" but not sure why is this. See below:
```
DBG jobmgr/manager.go:293 creating snmp[nas] job, config: map[__provider__:file reader __source__:discoverer=file_reader,file=/etc/netdata/go.d/snmp.conf __source_type__:user autodetection_retry:10 charts:[map[dimensions:[map[name:cpu-temp oid:1.3.6.1.4.1.55062.1.12.10.0] map[name:system-temp oid:1.3.6.1.4.1.55062.1.12.11.0]] family:Temp id:temp title:Temp type:line units:Celcius] map[dimensions:[map[name:uso oid:1.3.6.1.4.1.55062.1.12.12.0]] family:CPU usage id:cpu_usage title:CPU usage type:gauge units:percentage] map[dimensions:[map[name:rpm oid:1.3.6.1.4.1.24681.1.3.15.1.3.1]] family:System fan id:system_fan_rpm title:System Fan rpm type:line units:rpm] map[dimensions:[map[name:iops oid:1.3.6.1.4.1.24681.1.4.1.11.5.6.2.1.3.1] map[name:latency oid:1.3.6.1.4.1.24681.1.4.1.11.5.6.2.1.4.1]] family:IO id:disk_iops title:iops Discos type:line units:iops] map[dimensions:[map[algorithm:absolute divisor:100 name:seconds oid:1.3.6.1.4.1.55062.1.12.21.0]] family:Up time id:uptime title:NAS up time type:line units:seconds]] hostname:10.55.5.2 module:snmp name:nas options:map[timeout:30000 version:3] priority:1000 update_every:2 user:map[auth_key:password auth_proto:sha level:authPriv name:user priv_key:password priv_proto:des]] component="job manager"
INF snmp/init.go:67 hostname='10.55.5.2',port='161',snmp_version='3',security_level='3,user=user,engine=(),auth=sha,authPass=password,priv=DES,privPass=password' collector=snmp job=nas
INF pipeline/pipeline.go:118 instance is started component="service discovery" pipeline=docker
INF dockerd/docker.go:101 instance is started component="service discovery" discoverer=docker
ERR module/job.go:237 check failed: no system name collector=snmp job=nas
HOST ''

CONFIG go.d:collector:snmp:nas status failed
```
this is the piece of configuration for the job:

```
update_every: 2
autodetection_retry: 10
priority: 1000
jobs:
  - name: nas
    hostname: 10.55.5.2
    options:
      version: 3
      timeout: 30000
    user:
      name: user
      level: authPriv
      auth_proto: sha
      auth_key: password
      priv_proto: des
      priv_key: password
    charts:
      - id: "temp"
        title: "Temp"
        units: "Celcius"
        type: "line"
        family: "Temp"
        dimensions:
          - name: "cpu-temp"
            oid: "1.3.6.1.4.1.55062.1.12.10.0"
          - name: "system-temp"
            oid: "1.3.6.1.4.1.55062.1.12.11.0"
      - id: "cpu_usage"
        title: "CPU usage"
        units: "percentage"
        type: "gauge"
        family: "CPU usage"
        dimensions:
          - name: "uso"
            oid: "1.3.6.1.4.1.55062.1.12.12.0"
      - id: "system_fan_rpm"
        title: "System Fan rpm"
        units: "rpm"
        type: "line"
        family: "System fan"
        dimensions:
          - name: "rpm"
            oid: "1.3.6.1.4.1.24681.1.3.15.1.3.1"
      - id: "disk_iops"
        title: "iops Discos"
        units: "iops"
        type: "line"
        family: "IO"
        dimensions:
          - name: "iops"
            oid: "1.3.6.1.4.1.24681.1.4.1.11.5.6.2.1.3.1"
          - name: "latency"
            oid: "1.3.6.1.4.1.24681.1.4.1.11.5.6.2.1.4.1"
      - id: "uptime"
        title: "NAS up time"
        units: "seconds"
        type: "line"
        family: "Up time"
        dimensions:
          - name: "seconds"
            oid: "1.3.6.1.4.1.55062.1.12.21.0"
            algorithm: "absolute"
            divisor: 100
```

### Expected behavior

snmp collector get the expected data as in previous versions.

### Steps to reproduce

1. Set the above snmp conf file and restart netdata,
2.
3.
...

### Installation method

kickstart.sh

### System info

```shell
Linux tvh 6.8.0-48-generic #48~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  7 11:24:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=22.04
/etc/lsb-release:DISTRIB_CODENAME=jammy
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 22.04.5 LTS"
/etc/os-release:PRETTY_NAME="Ubuntu 22.04.5 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="22.04"
/etc/os-release:VERSION="22.04.5 LTS (Jammy Jellyfish)"
/etc/os-release:VERSION_CODENAME=jammy
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=jammy
```

### Netdata build info

```shell
Packaging:
    Netdata Version ____________________________________________ : v2.0.0
    Installation Type __________________________________________ : binpkg-deb
    Package Architecture _______________________________________ : x86_64
    Package Distro _____________________________________________ : ubuntu 22.04
    Configure Options __________________________________________ : dummy-configure-command
Default Directories:
    User Configurations ________________________________________ : /etc/netdata
    Stock Configurations _______________________________________ : /usr/lib/netdata/conf.d
    Ephemeral Databases (metrics data, metadata) _______________ : /var/cache/netdata
    Permanent Databases ________________________________________ : /var/lib/netdata
    Plugins ____________________________________________________ : /usr/libexec/netdata/plugins.d
    Static Web Files ___________________________________________ : /usr/share/netdata/web
    Log Files __________________________________________________ : /var/log/netdata
    Lock Files _________________________________________________ : /var/lib/netdata/lock
    Home _______________________________________________________ : /var/lib/netdata
Operating System:
    Kernel _____________________________________________________ : Linux
    Kernel Version _____________________________________________ : 6.8.0-48-generic
    Operating System ___________________________________________ : Ubuntu
    Operating System ID ________________________________________ : ubuntu
    Operating System ID Like ___________________________________ : debian
    Operating System Version ___________________________________ : 22.04.5 LTS (Jammy Jellyfish)
    Operating System Version ID ________________________________ : none
    Detection __________________________________________________ : /etc/os-release
Hardware:
    CPU Cores __________________________________________________ : 12
    CPU Frequency ______________________________________________ : 2401000000
    RAM Bytes __________________________________________________ : 33005510656
    Disk Capacity ______________________________________________ : 500107862016
    CPU Architecture ___________________________________________ : x86_64
    Virtualization Technology __________________________________ : none
    Virtualization Detection ___________________________________ : systemd-detect-virt
Container:
    Container __________________________________________________ : none
    Container Detection ________________________________________ : systemd-detect-virt
    Container Orchestrator _____________________________________ : none
    Container Operating System _________________________________ : none
    Container Operating System ID ______________________________ : none
    Container Operating System ID Like _________________________ : none
    Container Operating System Version _________________________ : none
    Container Operating System Version ID ______________________ : none
    Container Operating System Detection _______________________ : none
Features:
    Built For __________________________________________________ : Linux
    Netdata Cloud ______________________________________________ : YES
    Health (trigger alerts and send notifications) _____________ : YES
    Streaming (stream metrics to parent Netdata servers) _______ : YES
    Back-filling (of higher database tiers) ____________________ : YES
    Replication (fill the gaps of parent Netdata servers) ______ : YES
    Streaming and Replication Compression ______________________ : YES (zstd lz4 gzip)
    Contexts (index all active and archived metrics) ___________ : YES
    Tiering (multiple dbs with different metrics resolution) ___ : YES (5)
    Machine Learning ___________________________________________ : YES
Database Engines:
    dbengine (compression) _____________________________________ : YES (zstd lz4)
    alloc ______________________________________________________ : YES
    ram ________________________________________________________ : YES
    none _______________________________________________________ : YES
Connectivity Capabilities:
    ACLK (Agent-Cloud Link: MQTT over WebSockets over TLS) _____ : YES
    static (Netdata internal web server) _______________________ : YES
    h2o (web server) ___________________________________________ : YES
    WebRTC (experimental) ______________________________________ : NO
    Native HTTPS (TLS Support) _________________________________ : YES
    TLS Host Verification ______________________________________ : YES
Libraries:
    LZ4 (extremely fast lossless compression algorithm) ________ : YES
    ZSTD (fast, lossless compression algorithm) ________________ : YES
    zlib (lossless data-compression library) ___________________ : YES
    Brotli (generic-purpose lossless compression algorithm) ____ : NO
    protobuf (platform-neutral data serialization protocol) ____ : YES (system)
    OpenSSL (cryptography) _____________________________________ : YES
    libdatachannel (stand-alone WebRTC data channels) __________ : NO
    JSON-C (lightweight JSON manipulation) _____________________ : YES
    libcap (Linux capabilities system operations) ______________ : NO
    libcrypto (cryptographic functions) ________________________ : YES
    libyaml (library for parsing and emitting YAML) ____________ : YES
    libmnl (library for working with netfilter) ________________ : YES
Plugins:
    apps (monitor processes) ___________________________________ : YES
    cgroups (monitor containers and VMs) _______________________ : YES
    cgroup-network (associate interfaces to CGROUPS) ___________ : YES
    proc (monitor Linux systems) _______________________________ : YES
    tc (monitor Linux network QoS) _____________________________ : YES
    diskspace (monitor Linux mount points) _____________________ : YES
    freebsd (monitor FreeBSD systems) __________________________ : NO
    macos (monitor MacOS systems) ______________________________ : NO
    statsd (collect custom application metrics) ________________ : YES
    timex (check system clock synchronization) _________________ : YES
    idlejitter (check system latency and jitter) _______________ : YES
    bash (support shell data collection jobs - charts.d) _______ : YES
    debugfs (kernel debugging metrics) _________________________ : YES
    cups (monitor printers and print jobs) _____________________ : YES
    ebpf (monitor system calls) ________________________________ : YES
    freeipmi (monitor enterprise server H/W) ___________________ : YES
    nfacct (gather netfilter accounting) _______________________ : YES
    perf (collect kernel performance events) ___________________ : YES
    slabinfo (monitor kernel object caching) ___________________ : YES
    Xen ________________________________________________________ : YES
    Xen VBD Error Tracking _____________________________________ : NO
Exporters:
    AWS Kinesis ________________________________________________ : NO
    GCP PubSub _________________________________________________ : NO
    MongoDB ____________________________________________________ : YES
    Prometheus (OpenMetrics) Exporter __________________________ : YES
    Prometheus Remote Write ____________________________________ : YES
    Graphite ___________________________________________________ : YES
    Graphite HTTP / HTTPS ______________________________________ : YES
    JSON _______________________________________________________ : YES
    JSON HTTP / HTTPS __________________________________________ : YES
    OpenTSDB ___________________________________________________ : YES
    OpenTSDB HTTP / HTTPS ______________________________________ : YES
    All Metrics API ____________________________________________ : YES
    Shell (use metrics in shell scripts) _______________________ : YES
Debug/Developer Features:
    Trace All Netdata Allocations (with charts) ________________ : NO
    Developer Mode (more runtime checks, slower) _______________ : NO
```
