### ISSUE TITLE
[Feat]: Prometheus collector customization

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#19795]
### Problem

Today our OpenMetrics collector suffers from the following:

1. No ability to provide a friendlier names for contexts
2. No ability to provide a friendlier title
3. No ability to set the unit of the chart
4. No ability to set the chart type
5. No ability to provide multi-dimensional charts, so all charts always have a single dimension and all unique combinations of labels define the instances.

All these limitations make OpenMetrics sections on the dashboard look "ugly", or "raw".

### Description

We need a way to customize all the above.

So, for each OpenMetrics metric family found in a data source, we need to have some basic configuration, to define the following:

1. Name the context sent to Netdata
2. Define the title of the Netdata chart
3. Define the unit of the Netdata chart
4. Define the kind of chart (`area`, `line`, `stacked`, `heatmap`)
5. Define the labels which combined define the dimensions - the remaining should uniquely identify the instance

### Importance

blocker

### Value proposition

If we don't bring OpenMetrics charts closer to Netdata charts, we will have to rewrite all the collectors found out there. Our users and customers will demand a better experience and the only way we have currently is to port the prometheus exporter to Netdata. This is a tremendous amount of work.

It is by far simpler and faster, to have a way for modifying OpenMetrics and OTEL metrics in order to have a pleasant experience in Netdata.

### Proposed implementation

Our go.d.plugin prometheus module should support context configurations in `/etc/netdata/go.d/prometheus.d/contexts.d`. Each file in that directory should provide a configuration like:

```yaml
- match: "regex pattern to match the OpenMetrics metric family"
  context: "the Netdata context to assign to the chart"
  title: "the Netdata title to set to the chart"
  unit: "the Netdata unit to set to the chart"
  type: enum of line, area, stacked, heatmap
  dimensions: "string with variable substitution on the OpenMetrics labels"
```

The `dimensions` could be:

- a fixed string, like `foo`, in which case the dimension will be named `foo` and all the labels will be used to uniquely identify the chart instance for Netdata.
- a dynamic string, like `foo-${label1}-${label2}-bar`, in which case the dimension will be named `foo-value1-value2-bar` (after replacing `${label1}` and `${label2}` with their values) and the `label1` and `label2` should be excluded from the chart instance identification (so that multiple OpenMetrics metrics will now be a single chart instance for Netdata).
