### ISSUE TITLE
Simple way to monitor lan network services availability?

### ISSUE THREAD

**Issue by partoneoftwo** [netdata/netdata#2921]
I have a simple question. Sorry if it's too simple.

I would like to use Netdata to build a dashboard that shows
the status, UP or DOWN for 70 different IP's and related network ports.

All I am trying to do is to somehow feed information to Netdata, that (examples); 
192.168.1.2 port 8006 is REACHABLE or UNREACHABLE
192.168.1.25 port 80 is REACHABLE or UNREACHABLE
192.168.1.125 port 123 is REACHABLE or UNREACHABLE

Is there a simple way to achieve this?
I don't need any historical data or persistence of these stats, so therefore I thought Netdata could be the perfect tool for the job!

I found a way to test whether it is reachable or not:
```
portping() { python <<<"import socket; socket.setdefaulttimeout(1); socket.socket().connect(('$1', $2))" 2> /dev/null && echo OPEN || echo CLOSED; }

portping 192.168.1.2 8006

```

**Comment by ktsaou** [comment]
Hi,

we don't have a plugin for this, but it is a nice request.

Ideally, we should have a plugin to accept jobs like this:

```yaml
name:
   url: 'http://ip:port/path' or 'https://ip:port/path' or 'tcp://ip:port' or 'udp://ip:port',
   request: 'payload to send',
   valid_response: 'regex to match on the response',
   check_every_ms: 500,
   connect_timeout_ms: 500,
   response_timeout_ms: 1000
```

All jobs of this plugin should produce a set of charts for the same app (e.g. `service_check`, so that the dashboard will not be flooded with apps - I will do this at `index.html`), and `name` should also be the `family` (i.e. the submenu on the dashboard and also shared variables for alarms).

4 charts should be created per job:

1. `service_check_NAME.connect` with dimensions:

   - `requests` (number of requests made),
   - `connected` (number of requests connected),
   - `timeout` (number of times we timed out while waiting for connection establishment),

2. `service_check_NAME.response` with dimensions:

   - `valid` (number of times we received a response matching the regex)
   - `invalid` (number of times we received a response not matching the regex)
   - `timeout` (number of times we timed out waiting for a response)

3. `service_check_NAME.connect_time` (the time it took to be connected), with dimensions:

   - `min`
   - `average`
   - `max`

4. `service_check_NAME.response_time` (the time it took to receive the response, including connection time), with dimensions:

   - `min`
   - `average`
   - `max`

Then we could add 2 alarms:

1. `service_check_status` (up/down, will check the 2 `timeout` and the `invalid`)
2. `service_check_slow` (adaptive, to trigger warning 2x and critical 4x).

@l2isbad what do you think?
