### ISSUE TITLE
NetdataForAtlassian

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#3057]
@wjkennedy I think you are the author of https://bitbucket.org/wkennedy/netdataforatlassian/wiki/Home

I run jira and I monitor it with netdata, so I have a few suggestions to make for your wiki:

1. Enable systemd services monitoring for debian: https://github.com/firehol/netdata/wiki/monitoring-systemd-services#how-to-enable-cgroup-accounting-on-systemd-systems-that-is-by-default-disabled

2. Add Atlassian applications for apps.plugin. Now your wiki provides screenshots for java applications. You can add all Atlassian apps at `/etc/netdata/apps_groups.conf`. On my system I have these (add them **before `java`**):

```
jira: */opt/atlassian/jira*
```

If we add such patterns, netdata will be able to provide separate chart dimensions for each of the atlassian apps, even when they run on the same server (without these patterns, netdata will group them together as `java`).

3. Using the latest version of netdata (like you do), you can press ALT on the keyboard and then select an area of interest at a chart. netdata will highlight that area on all charts of the dashboard, like this:

![screenshot from 2017-11-23 22-11-41](https://user-images.githubusercontent.com/2662304/33187575-6760182a-d09b-11e7-80d8-2be944d61393.png)

4. On my installation I chose to proxy jira through an nginx running on the same host. This provided an `access.log` file, which was automatically picked up by netdata and allowed me to have charts like these:

![screenshot from 2017-11-23 22-37-10](https://user-images.githubusercontent.com/2662304/33188010-e4bc73a6-d09e-11e7-9f39-3f9e70349e5a.png)

The best part is that I can get jira API timings:

![screenshot from 2017-11-23 22-38-12](https://user-images.githubusercontent.com/2662304/33188063-536b7f0e-d09f-11e7-8beb-6c98cfa9c031.png)

and with a bit of netdata customization, I can get a real-time view of which jira API methods are called:

![screenshot from 2017-11-23 22-40-04](https://user-images.githubusercontent.com/2662304/33188078-7400e984-d09f-11e7-99cc-5bdf46c4429c.png)

For this customization I edited `/etc/netdata/python.d/web_log.conf`, removed the default jobs and added this one:

```
jira_nginxlog:
  path: '/var/log/nginx/access.log'
  categories:
    tempo: '.*[Tt][Ee][Mm][Pp][Oo].*'
    download: '.*/download/.*'
    images: '.*/images/.*'
    gadget: '.*/gadgets?/.*'
    scriptrunner: '.*/scriptrunner/.*'
    analytics: '.*/analytics/.*'
    slack: '.*/slack/.*'
    hipchat: '.*/hipchat/.*'
    raven: '.*/raven/.*'
    servicedesk: '.*/servicedesk/.*'
    issue: '^/jira/rest/api/2/issue/.*'
    stub_status: '.*stub_status.*'
    search: '.*/jira/rest/api/2/search.*'
    webresources: '.*/rest/webResources/1.0/resources.*'
    avatar: '.*/jira/secure/(user|view)avatar.*'
    comment_template: '.*/comment-templates/.*'
    other: '.*'
```

It would be best if we could have an official list of all the interesting jira patterns.
