### ISSUE TITLE
Ubuntu 17.10: systemd-journal cpu usage at 50% when idling with netdata on

### ISSUE THREAD

**Issue by tomholub** [netdata/netdata#3502]
This may be the culprit: https://github.com/systemd/systemd/issues/5820 as my ubuntu ships with systemd v234. I think the fix got into v235.

Is there any way to mitigate this / any sort of workaround?

**Comment by tomholub** [comment]
I should add, I'm running netdata in a docker container using docker-compose:
```
  netdata:
    image: titpetric/netdata:latest
    cap_add:
     - SYS_PTRACE
    volumes:
     - /proc:/host/proc:ro
     - /sys:/host/sys:ro
```
