### ISSUE TITLE
Delayed Start for Netdata

### ISSUE THREAD

**Issue by vrst37** [netdata/netdata#3623]
Hello all,
Netdata is working very well for us here.

I am using it to monitor my mongoDB instance and the mongo instance is launched about 2 to 3 seconds after the boot.

For now I am editing the /etc/systemd/system/netdata.service file to add a short delay before starting netdata daemon so it can detect the mongoDB instance (netdata is launched after the mongoDB instance is up and running). 

Is there a standard option that can be set in the configuration file to add a delay at boot?

If not, I think we should add it.

**Comment by l2isbad** [comment]
> Is there a standard option that can be set in the configuration file to add a delay at boot?

For all python modules
https://github.com/firehol/netdata/blob/master/conf.d/python.d/mongodb.conf#L36-L40

**Comment by l2isbad** [comment]
```yaml
local:
    name : 'local'
    host : '127.0.0.1'
    port : 27017
    autodetection_retry: 10
```
