### ISSUE TITLE
Memory leak in python.d.plugin

### ISSUE THREAD

**Issue by fdurand** [netdata/netdata#3817]
Hi,
We are using netdata in PacketFence and we encounter a huge memory consumption with python.d.plugin process.
After a while, it can be few hours or few days, the python.d.plugin process start to consume more and more memory on each iteration.

I tried to debug the issue but i wasn't able to point where in the code it happen and which module is causing the issue.

To 'fix' the issue i added gc in the code (https://stackoverflow.com/questions/1316767/how-can-i-explicitly-free-memory-in-python).

```
diff --git a/plugins.d/python.d.plugin b/plugins.d/python.d.plugin
index 957d7e26..ca39cce8 100755
--- a/plugins.d/python.d.plugin
+++ b/plugins.d/python.d.plugin
@@ -11,6 +11,7 @@ echo "ERROR python IS NOT AVAILABLE IN THIS SYSTEM")" "$0" "$@" # '''
 import os
 import sys
 import threading
+import gc
 
 from re import sub
 from sys import version_info, argv
@@ -343,6 +344,7 @@ class Plugin(object):
                 run_and_exit(Logger.info)('FINISHED')
 
             sleep(self.sleep_time)
+           gc.collect()
             self.cleanup()
             self.autodetect_retry()
```
It looks that it works, the process is running since 6 days, but it's a dirty fix.

I am open to test anything that will fix the issue properly.

Thanks!

**Comment by ktsaou** [comment]
It would help a lot if you could post the modules your run.

**Comment by l2isbad** [comment]
> Memory leak in python.d.plugin

I saw this some time ago on manjaro. The problem modules were modules that starts new threads on every iteration (`dns_query_time`, `elasticsearch` etc). And it was fixed after the nex `python` upgrade.

Another thing is memory consumption very depends on `python` version. it was +40MB of ram after `import yaml` on some versions :cry:

**Comment by fdurand** [comment]
For the list of modules:
- apache

```
httpd_aaa:
  name : 'httpd.aaa'
  url  : 'http://localhost:7070/apache_status/?auto'

httpd_webservices:
  name : 'httpd.webservices'
  url  : 'http://localhost:9090/apache_status/?auto'

httpd_portal:
  name : 'httpd.portal'
  url  : 'http://10.0.0.40:1444/modstatus/?auto'

```
- chrony with the default config

- cpufreq with the dwfault config

- dns_query_time (the file is there but not configured yet)

- freeradius

```
radiusauth:
  name: 'Freeradius Auth'
  host: 'localhost'
  port: '18121'
  secret: 'adminsecret'

radiusacct:
  name: 'Freeradius Acct'
  host: 'localhost'
  port: '18122'
  secret: 'adminsecret'
  acct: yes
  proxy_auth: yes
  proxy_acct: yes

radiusloadbalancer:
  name: 'Freeradius LoadBalancer'
  host: 'localhost'
  port: '18123'
  secret: 'adminsecret'
  proxy_auth: yes
  proxy_acct: yes

radiuseduroam:
  name: 'Freeradius Eduroam'
  host: 'localhost'
  port: '18124'
  secret: 'adminsecret'
  proxy_auth: yes

```
- go_expvar (the file is there but not configured yet)
- haproxy 
```
haproxy-portal:
 name : haproxy-portal
 url : 'http://10.0.0.40:1025/stats;csv;norefresh'
 user : 'admin'
 pass : 'packetfence'

haproxy-db:
 name : haproxy-db
 url : 'http://10.0.0.40:1026/stats;csv;norefresh'
 user : 'admin'
 pass : 'packetfence'
```
- mysql
```
pfdb:
  name : 'PacketFence Database'
  user : 'pf'
  pass : 'ZaymeIsMyName'
  host : 'localhost'
```
- postfix (default config)
- redis
```
redis_cache:
  name : 'redis cache'
  host : '127.0.0.1'
  port : 6379

redis_queue:
  name : 'redis queue'
  host : '127.0.0.1'
  port : 6380
```
- web_log
```
autodetection_retry: 10
portal_log:
  name: 'apache portal log'
  path: '/usr/local/pf/logs/httpd.portal.access'

webservices_log:
  name: 'apache webservices log'
  path: '/usr/local/pf/logs/httpd.webservices.access'

aaa_log:
  name: 'apache aaa log'
  path: '/usr/local/pf/logs/httpd.aaa.access'

admin_log:
  name: 'apache admin log'
  path: '/usr/local/pf/logs/httpd.admin.access'
```
An example when the issue occur (python.d.plugin memory and cpu)

![python](https://user-images.githubusercontent.com/1553962/41324494-ca89a3f0-6e82-11e8-8616-5015f928ec36.png)

I am running it on Centos 7 and actually the memory used is 130508 Kb
I also use it on debian Jessie but i have another issue about the initial memory used by python.d.plugin (1157168 Kb with the same config) but it's another problem and i need to investigate.
