### ISSUE TITLE
General issue

### ISSUE THREAD

**Issue by zet694** [netdata/netdata#4670]
##### Question summary

1) I have set up a telegram notification and a full scan message comes to me, but how to do that would be all the same when the event also came notification? (Why the silence when comes threshold)

Example my config:
```
$ sh edit-config health.d/disks.conf 

template: disk_space_usage            
      on: disk.space                  
      os: linux freebsd               
   hosts: *               
families: *               
    calc: $used * 100 / ($avail + $used)
   units: %                             
   every: 1m                            
    warn: $this > (($status >= $WARNING ) ? (5) : (10)) 
    crit: $this > (($status == $CRITICAL) ? (90) : (98))
   delay: up 1m down 15m multiplier 1.5 max 1h          
    info: current disk space usage                      
      to: sysadmin  
```

2) How to save all settings if I use docker? (Each time they are reset)
3) How do I add location tracking to specific drives?
4) How can I remove kernel information? (On my server 96 cores, that's too much for one page)
5) I've read about roles, but where can I create or edit them? What are they responsible for?
6) Where can I edit the list of disks that are displayed in the panel?
![image](https://user-images.githubusercontent.com/16643155/48567974-6a2e4a80-e90f-11e8-85f2-b75474d4e3ae.png)
7) Can I store data on my hard drive instead of in RAM? (Let's say a week or two)

##### OS / Environment

System: Linux(ubuntu )
Run netdata in docker container

p.s. Excuse me for my English and possibly stupid questions, but I did read the instructions a few times and did not find the answer to these questions, I will be grateful for possible examples. Thank you!

**Comment by paulfantom** [comment]
One by one:
> I have set up a telegram notification and a full scan message comes to me, but how to do that would be all the same when the event also came notification? (Why the silence when comes threshold)

I don't understand, could you explain a bit more what do you want to achieve?

> How to save all settings if I use docker? (Each time they are reset)

You can mount `/etc/netdata` with configuration files inside a docker container



For others @ktsaou please jump in.

**Comment by zet694** [comment]
@paulfantom 

> I don't understand, could you explain a bit more what do you want to achieve?

Sure, i want to get notified from telegram bot.  My steps: 

1) Create docker-compose. Example: 
```
    netdata:
        image: netdata/netdata
        hostname: zet694_host
        container_name: netdata
        ports:
          - 19999:19999
        cap_add:
          - SYS_PTRACE
        security_opt:
          - apparmor:unconfined
        volumes:
          - ./netdata:/etc/netdata
          - /proc:/host/proc:ro
          - /sys:/host/sys:ro
          - /var/run/docker.sock:/var/run/docker.sock:ro
```

2) I created health_alarm_notify.conf and add TELEGRAM_BOT_TOKEN and DEFAULT_RECIPIENT_TELEGRAM

3) Execute command:
```
/usr/libexec/netdata/plugins.d/alarm-notify.sh test
```
Its worked. 

Now I would like to be notified when the space on my hard drive is 95% occupied+. My steps:
1) Create folder ''health.d", create file "disks.conf" and change percent for example:

```
   template: disk_space_usage
   on: disk.space
   os: linux freebsd
   hosts: *
   families: *
   calc: $used * 100 / ($avail + $used)
   units: %
   every: 1m
   warn: $this > (($status >= $WARNING ) ? (30) : (90)) <<<<---- CHANGE 30 percent. Current percent - 52%
   crit: $this > (($status == $CRITICAL) ? (90) : (98))
   delay: up 1m down 15m multiplier 1.5 max 1h
   info: current disk space usage
   to: sysadmin
```

2) My current percent for disk(52%+). Restart container. 

3) I do not get the message to a telegram.

Questions:
1) What is my mistake?
2) How do I add notifications for a specific drive and not all ?
