### ISSUE TITLE
sendmail - not RFC 5322 compliant

### ISSUE THREAD

**Issue by salehi** [netdata/netdata#5016]
Hi

##### Net data is unable to send email to gmail server because of FROM header.
I did the following but it doesn't work.

docker-compose.yml:
```
version: '3.7'
services:
  netdata:
    build:
      context: ./build
    restart: always
    hostname: netdata.snappfood.ir
    environment:
      - SMTPHOST=192.168.100.51
#      - NETDATA_ALARM_NOTIFY_DEBUG=1
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./netdata.conf:/etc/netdata/netdata.conf:ro
      - ./stream.conf:/etc/netdata/stream.conf:ro
      - ./health_alarm_notify.conf:/etc/netdata/health_alarm_notify.conf
      - shared:/var/run

  ngx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - shared:/var/run
    environment:
      - VIRTUAL_HOST=netdata.snappfood.ir


networks:
  default:
    external: true
    name: shared

volumes:
  shared:
```

global notification options in `health_alarm_notify.conf`
```
#------------------------------------------------------------------------------
# email global notification options

# multiple recipients can be given like this:
#              "admin1@example.com admin2@example.com ..."

# the email address sending email notifications
# the default is the system user netdata runs as (usually: netdata)
# The following formats are supported:
# EMAIL_SENDER="user@domain"
# EMAIL_SENDER="User Name <user@domain>"
# EMAIL_SENDER="'User Name' <user@domain>"
# EMAIL_SENDER="\"User Name\" <user@domain>"
EMAIL_SENDER="netdata@snappfood.ir"

# enable/disable sending emails
SEND_EMAIL="YES"

# if a role recipient is not configured, an email will be send to:
DEFAULT_RECIPIENT_EMAIL="muhammad.salehi@zoodfood.com"
# to receive only critical alarms, set it to "root|critical"

# Optionally specify the encoding to list in the Content-Type header.
# This doesn't change what encoding the e-mail is sent with, just what
# the headers say it was encoded as.
# This shouldn't need to be changed as it will almost always be
# autodetected from the environment.
EMAIL_CHARSET="UTF-8"

# You can also have netdata add headers to the message that will
# cause most e-mail clients to treat all notifications for a given
# chart+alarm+host combination as a single thread.  This can help
# simplify tracking of alarms, as it provides an easy wway for scripts
# to corelate messages and also will cause most clients to group all the
# messages together.  This is enabled by default, uncomment the line
# below if you want to disable it.
#EMAIL_THREADING="NO"


#------------------------------------------------------------------------------

```
But the postfix says:
```
Dec 17 17:48:57 db1 postfix/smtp[7375]: 65EB269BE06: to=<muhammad.salehi@zoodfood.com>, relay=aspmx.l.google.com[66.102.1.27]:25, delay=1.9, delays=0.01/0/1.6/0.32, dsn=5.7.1, status=bounced (host aspmx.l.google.com[66.102.1.27] said: 550-5.7.1 [xxx.xxx.xxx.xxx      11] Our system has detected that this message is 550-5.7.1 not RFC 5322 compliant: 550-5.7.1 'From' header is missing. 550-5.7.1 To reduce the amount of spam sent to Gmail, this message has been 550-5.7.1 blocked. Please visit 550-5.7.1  https://support.google.com/mail/?p=RfcMessageNonCompliant 550 5.7.1 and review RFC 5322 specifications for more information. x196si9199299wme.179 - gsmtp (in reply to end of DATA command))

```

I've been also tried these as the value of EMAIL_SENDER: `Netdata <netdata@snappfood.ir>` , `"Netdata" "<netdata@snappfood.ir>"`.
I guess there is should be problem with busybox sendmail when a remote postfix is available because it does not appeared in the non-docker installations.
I Add the following line to [1305 in template section](https://github.com/netdata/netdata/blob/4172f7fdd14d574e365d9a7005f20a35c294926e/plugins.d/alarm-notify.sh#L1305) and email has been sent, seems there is should be sth with busybox sendmail and EOF template .
```
From: Netdata <netdata@snappfood.ir>
```
