### ISSUE TITLE
Netdata w/ Docker Container not show Disk space utilization for mounts

### ISSUE THREAD

**Issue by caius88** [netdata/netdata#5071]
##### Bug report summary
Using netdata inside the official docker container (netdata/netdata) a partition mounted under `/mnt/<name>` is not recognized by netdata. It only found the disk (sdb in this case) in _disks_ section. **Disk space utilization** info for the given mount are not dispalyed.     
##### OS / Environment
Ubuntu Server 18.04.1 LTS
##### Steps To Reproduce
Command: 
`cat /host/proc/self/mountinfo | grep /mnt/<name>` inside the container 
`cat /proc/self/mountinfo | grep /mnt/<name>` on the host
##### Expected behavior
The outputs of the above commands are different: inside the container nothing appear, on the host the mount appear. The docker-compose file is correctly configured with `/proc:/host/proc:ro` directive and the container user is set with `grep docker /etc/group | cut -d ':' -f 3`.

**Comment by caius88** [comment]
> 
> 
> Could you share how you started a container?

Hi, i apologize for the delay. I use docker-compose config to run netdata container:

  ```
netdata:
    image: netdata/netdata
    container_name: netdata
    volumes:
      - ${APPDIR}/netdata/netdata.conf:/etc/netdata/netdata.conf:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    hostname: ${HOST_NAME}
    ports:
      - "19999:19999"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    environment:
      - PGID=${PGID_DOCKER}
      - PUID=${PUID}
      - TZ=${TZ}
```
