### ISSUE TITLE
RabbitMQ Plugin wrong metrics for nodes in cluster

### ISSUE THREAD

**Issue by vpapas** [netdata/netdata#5118]
Hello,

In a RabbitMQ cluster netdata reports same data for all nodes.
The cluster consists of 4 nodes and only the metrics from the 1st node seem to be correct in netdata. The data for the other 3 nodes are the same with the data from 1st node.

**Netdata version**: v1.12.0-rc2-7-g838ea60.
**RabbitMQ version**: 3.6.6-1.
**Operating System**: Centos 7

Netdata RabbitMQ config is the following:

```
# netdata python.d.plugin configuration for rabbitmq
#
# This file is in YaML format. Generally the format is:
#
# name: value
#
# There are 2 sections:
#  - global variables
#  - one or more JOBS
#
# JOBS allow you to collect values from multiple sources.
# Each source will have its own set of charts.
#
# JOB parameters have to be indented (using spaces only, example below).

# ----------------------------------------------------------------------
# Global Variables
# These variables set the defaults for all JOBs, however each JOB
# may define its own, overriding the defaults.

# update_every sets the default data collection frequency.
# If unset, the python.d.plugin default is used.
# update_every: 1

# priority controls the order of charts at the netdata dashboard.
# Lower numbers move the charts towards the top of the page.
# If unset, the default for python.d.plugin is used.
# priority: 60000

# retries sets the number of retries to be made in case of failures.
# If unset, the default for python.d.plugin is used.
# Attempts to restore the service are made once every update_every
# and only if the module has collected values in the past.
# retries: 60

# autodetection_retry sets the job re-check interval in seconds.
# The job is not deleted if check fails.
# Attempts to start the job are made once every autodetection_retry.
# This feature is disabled by default.
# autodetection_retry: 0

# ----------------------------------------------------------------------
# JOBS (data collection sources)
#
# The default JOBS share the same *name*. JOBS with the same name
# are mutually exclusive. Only one of them will be allowed running at
# any time. This allows autodetection to try several alternatives and
# pick the one that works.
#
# Any number of jobs is supported.
#
# All python.d.plugin JOBS (for all its modules) support a set of
# predefined parameters. These are:
#
# job_name:
#     name: myname            # the JOB's name as it will appear at the
#                             # dashboard (by default is the job_name)
#                             # JOBs sharing a name are mutually exclusive
#     update_every: 1         # the JOB's data collection frequency
#     priority: 60000         # the JOB's order on the dashboard
#     retries: 60             # the JOB's number of restoration attempts
#     autodetection_retry: 0  # the JOB's re-check interval in seconds
#
# Additionally to the above, rabbitmq plugin also supports the following:
#
#     host: 'ipaddress'                # Server ip address or hostname. Default: 127.0.0.1
#     port: 'port'                     # Rabbitmq port. Default: 15672
#     scheme: 'scheme'                 # http or https. Default: http
#
# if the URL is password protected, the following are supported:
#
#     user: 'username'
#     pass: 'password'
#
# ----------------------------------------------------------------------
# AUTO-DETECTION JOBS
# only one of them will run (they have the same name)
#
local:
 host: '127.0.0.1'
 user: 'guest'
 pass: 'guest'

socket:
  name     : 'local'
  host     : '127.0.0.1'
  port     :  15672
  user     : '********'
  pass     : '********'
```

Do i need a different configuration?

Thank you in advance,
Vasso
