### ISSUE TITLE
python go_expvar: reuse same expvar key in different charts

### ISSUE THREAD

**Issue by liepumartins** [netdata/netdata#5133]
I have a go program with several incrementing expvars, I would like to chart both incremental and absolute values. Goal is to get and show total number of operations and operations per minute and operations per hour.

However, if I try to add different chart using the same expvar, this happens `INFO: go_expvar: myapp: Duplicate expvar key counters.downloaded: skipping line.` 
All the other ids are unique.

```
...
- id: "counters_down"
      options:
        name: counters
        title: "downloaded"
        units: items
        family: counters
        context: expvar.foo.counters
        chart_type: line
      lines:
        - {expvar_key: 'counters.downloaded_orders', expvar_type: int, id: counters_downloaded, name: 'Items'}
- id: "counters_down_rate"
      options:
        name: counters
        title: "downloaded per second"
        units: items
        family: counters
        context: expvar.foo.counters
        chart_type: line
      lines:
        - {expvar_key: 'counters.downloaded_orders', expvar_type: int, id: counters_downloaded_rate, name: 'Items/s', algorithm: incremental}
...
```
