### ISSUE TITLE
Docker PGID + docker volume mount

### ISSUE THREAD

**Issue by hitmax117** [netdata/netdata#5156]
Running the docker container with `PGID=999` works and shows the docker container names. But I would like to mount a docker volume as well to keep some data out of the docker container to survive updates, but with `PGID=999` it has no access to the volume mount. And when I use `PUID=1000 PGID=1000` to have write access I lose the docker names.

So how can I mount a volume in docker while preserving the docker names instead of id's?

**Comment by paulfantom** [comment]
We don't use `PUID`, netdata process inside a container is always running with PUID and PGID specified in https://github.com/netdata/netdata/blob/master/packaging/docker/Dockerfile#L83-L84. `PGID` is used only to add netdata user to supplementary group.

As for answering your question, that depends on which directory you want to mount as a volume:
1) For `/etc/netdata`, you can mount it as read-only as long as it can be read by other users (mode `a+r`). So you can have files with UID=1000 and they will still be read by netdata process inside a container
2) Other directories - that's more tricky (and not advised to do). For this you need to mount them as read-write and they **cannot** have UID=1000 or GID=1000, they need to be UID=201 and GID=201. To modify such files from host, you have a couple of options:
    - modify them from inside of a netdata docker container
    - modify them from host using user account with UID=201
    - modify them as root and change file ownership after modifications.


In the end you should just mount a volume and use `PGID`. For example this is a docker-compose.yml I am using:
```yaml
  netdata:
    image: netdata/netdata
    hostname: nas
    restart: 'always'
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    environment:
      PGID: 989
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "${PWD}/netdata/health_alarm_notify.conf:/etc/netdata/health_alarm_notify.conf:ro"
```

And as you can see I am mounting `${PWD}/netdata/health_alarm_notify.conf` as read-only, where this file has following stats:
```bash
$ ls -l netdata/
-rw-rw-r--. 1 paulfantom paulfantom 121 Sep 22 12:05 health_alarm_notify.conf

$ id
uid=1000(paulfantom) gid=1000(paulfantom)
```
