### ISSUE TITLE
Plan migration to go.d plugin for common collectors

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#5311]
##### Feature idea summary
Related to #5006 

We need to plan the next step for an assisted migration of users from the old plugins to go.d, where we have reimplemented a collector.

##### Expected behavior
Come up with a design of what we will implement within v1.13

**Comment by ilyam8** [comment]
> ~Plan migration to go.d plugin for common modules~ Plan migration to go.d plugin for common collectors

We need to agree on definitions, i see it's still confusing.  And I think it doesn't matter if module word has special meaning in `go`. 

Netdata currently use: `collector`, `plugin`, `module`, `orchestrator`. 

`collector` is a data collection plugin (collector == (data collection) plugin).

`orchestrator` is a special type of `collector`. It doesn't collect any data by themselve. It contains data collection `modules`.

We need strictly define them.

**Comment by ilyam8** [comment]
> We need to plan the next step for an assisted migration of users from the old plugins to go.d


 * disable python module by default
 * enable corresponding go module by default
 * add additional configuration translation logic to the installer ([python script](https://github.com/netdata/netdata/issues/5144)?)

Python module can be disabled:
 - in python.d.plugin (can't be enabled via conf, completely disabled)
 - in module, using `disable_by_default = True` (can be enabled again via conf)

Tranlator script logic depends on the disabling approach.

**Comment by ilyam8** [comment]
Configuration translation is very depends on module. Lets take mysql:

Python version configuration types:
 - `my.cnf`
 - socket
 - tcp

```yaml
mycnf2:
  name     : 'local'
  'my.cnf' : '/etc/mysql/my.cnf'

socket3:
  name     : 'local'
  # user     : ''
  # pass     : ''
  socket   : '/var/lib/mysql/mysql.sock'

tcpipv4:
  name     : 'local'
  # user     : ''
  # pass     : ''
  host     : '127.0.0.1'
  port     : '3306'
```

Go version uses [dsn syntax](https://github.com/go-sql-driver/mysql#dsn-data-source-name): 

> [username[:password]@][protocol[(address)]]/dbname[?param1=value1&...&paramN=valueN]

```yaml
jobs:
  - name: local
    dsn: netdata@tcp(127.0.0.1:3306)/

  - name: local
    dsn: root@/

  - name: local
    dsn: root@unix(/var/run/mysqld/mysqld.sock)/

  - name: local
    dsn: root@unix(/usr/local/var/mysql/mysql.sock)/
```

__

So it is not a trivial task, it is easy to make a mistake.
