### ISSUE TITLE
Docker persistent volume mounts

### ISSUE THREAD

**Issue by picto3000** [netdata/netdata#5516]
As standard practise I create several persistent volumes as part of adding a new container to my compose file. These generally fall into two camps:

Persistant config
`      - ${USERDIR}/docker/netdata/netdata:/etc/netdata`

Log files on HDD (Docker itself runs on an SSD)
`      - ${LOG}/netdata:/var/log/netdata`

I've tried both of these with no success. Netdata won't start if I include these volumes, even if I'm explicit with the log files. e.g.
`- ${LOG}/netdata/access.log:/var/log/netdata/access.log`
`- ${LOG}/netdata/debug.log:/var/log/netdata/debug.log`
`- ${LOG}/netdata/error.log:/var/log/netdata/error.log`

You can see from my compose file below, I've attempted many different volumes, and all have the same outcome of not allowing netdata to start:

```
#Netdata - real-time performance and health monitoring
  netdata:
    image: netdata/netdata:latest
    container_name: netdata
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - ${USERDIR}/docker/netdata/netdata:/etc/netdata
#      - ${USERDIR}/docker/netdata/libexec:/usr/libexec/netdata
#      - ${USERDIR}/docker/netdata/share:/usr/share/netdata
#      - ${USERDIR}/docker/netdata/lib:/var/lib/netdata
#      - ${LOG}/netdata:/var/log/netdata
#      - ${LOG}/netdata/access.log:/var/log/netdata/access.log
#      - ${LOG}/netdata/debug.log:/var/log/netdata/debug.log
#      - ${LOG}/netdata/error.log:/var/log/netdata/error.log
#      - ${TMP}/netdata:/var/cache/netdata
    hostname: netdata.domain.com
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    restart: always
    networks:
      - traefik_proxy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=netdata"
      - "traefik.frontend.rule=Host:netdata.${DOMAINNAME}"
      - "traefik.port=19999"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.headers.customFrameOptionsValue=ALLOW-FROM https://${DOMAINNAME}"
      - "traefik.frontend.auth.basic=${HTTP_USERNAME}:${HTTP_PASSWORD}"
      - "traefik.frontend.auth.basic.removeHeader=true"
```
edit: privacy
