### ISSUE TITLE
Cant see user name when run netdata in docker

### ISSUE THREAD

**Issue by luanmingyi** [netdata/netdata#5585]
##### Question summary
I run netdata in docker, the user names in the "per user statistics" under `Users` tag are not shown, instead it shows the user id (except for `root` `netdate` `xfs`). I want see the user name in the legand.

It looks like the problem is about docker not netdata, but i search it on google and fail to solve it.

below is my docker-composer file:
```
version: "3"
services:
  netdata:
    image: netdata/netdata
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    environment:
      - PGID=999
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
```

##### OS / Environment
ubuntu 18.04
docker 18.09.3
