### ISSUE TITLE
httpcheck does not export some metrics in version 1.15

### ISSUE THREAD

**Issue by astorath** [netdata/netdata#6157]
##### Bug report summary
After installing netdata 1.15 (used 1.13 previously) some *httpcheck* metrics disappeared from prometheus export. For instance: `netdata_httpcheck_response_time`, `netdata_httpcheck_response_length` 

##### OS / Environment
`CentOS Linux release 7.6.1810 (Core)`

##### Netdata version (output of `netdata -V`)
`netdata v1.15.0`

##### Component Name
*httpcheck*

##### Steps To Reproduce
1. setup `/etc/netdata/go.d/httpcheck.conf` with:
    ```
    jobs:
      - name: test
        url: http://localhost:19999/
        status_accepted:
          - 200
    ```
2. query:
    ```bash
    curl -L http://localhost:19999/api/v1/allmetrics?format=prometheus | grep  "^netdata_httpcheck_response_time"
    ```
3. Nothing in output...

##### Expected behavior
`/api/v1/allmetrics?format=prometheus` should return a metric:
```
netdata_httpcheck_response_time_ms_average{chart="httpcheck_test.response_time",family="response",dimension="time"} 4.3002560 1559117880000
```
