### ISSUE TITLE
Docker network interfaces shown as veth* under "Network Interfaces" when Netdata is running in container

### ISSUE THREAD

**Issue by gschaffner** [netdata/netdata#6882]
##### Bug report summary
When running Netdata in a Docker container (per the [docs](https://docs.netdata.cloud/packaging/docker/)), the network interfaces of Docker containers are each shown as `veth*` and in the "Network Interfaces" section. They should be shown with the container's name and in the appropriate section for that Docker container (as they are when Netdata does not run in a container).

Note that this is even when the Netdata has access to `/var/run/docker.sock`, both through a docker socket proxy or a volume with `docker` group access.

This bug is related to #5383. This bug was fixed for Netdata instances running not in a container, but still remains for those in a container.

##### OS / Environment
Debian 10.1
`docker-compose.yml`:
```yml
---
version: '2'
services:
  # system monitoring stack

  # Docker socket proxy so Netdata has API access to a restricted Docker API
  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: docker-socket-proxy
    privileged: true
    environment:
      - CONTAINERS=1 # enable access to containers API endpoint
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  # system monitoring: metric collector & web/api server
  netdata:
    image: netdata/netdata
    container_name: netdata
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    hostname: example.com
    environment:
      - DOCKER_HOST=docker-socket-proxy:2375
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    ports:
      - 19999:19999
    depends_on:
      - docker-socket-proxy
    restart: unless-stopped
```

##### Netdata version (ouput of `netdata -V`)
`netdata v1.17.1-16-g270ede57`

##### Component Name
`collectors`, or possibly Docker container configuration

##### Steps To Reproduce
Run `docker-compose up -d` with the compose file above and view the webserver at `http://localhost:19999`. Note that containers will be named properly, but their networks won't.

##### Expected behavior
The network interfaces for containers should be shown with the container's name and in the appropriate section for that Docker container (as they are when Netdata does not run in a container).
