### ISSUE TITLE
Collector metadata template (related to #5102)

### ISSUE THREAD

**Issue by cosmix** [netdata/netdata#7142]
As described in #5102 and #4415 we would like to provide an automatically generated and maintained Collectors landscape/documentation that will allow users to easily find, filter and search available Netdata integrations.

In order to do this, we need to be able to identify a number of properties of the collector that will be used in the landscape. To this end, I propose we use a YAML or JSON metadata file, required as part of all collectors. 

This file should provide pointers to sources of information as well as metadata _that would be either impossible or exceedingly hard for the automated script to find/extract on its own_.

The metadata file should have a standard format following a template {r,d}efined in this issue. Assuming we adopt YAML for this purpose, this is a template file we can start with:

```yaml
collector:
  name: mysql
  category: database
  repo: github.com/mysql/mysql-server
  homepage: www.oracle.com/mysql
  linkedin: www.linkedin.com/mysql
  min_tested_version: 3.0
  max_tested_version: 8.0
```

It should also have a standard name, across all collectors, so that the script can pick it up and process it, e.g. `collector_info.yml`. The output of the script should be a `processed_collectors.yml` that will include all the necessary information for rendering the Collectors Landscape.
