### ISSUE TITLE
Kubernetes - Kubelet Connection Refused

### ISSUE THREAD

**Issue by bitva77** [netdata/netdata#7188]
##### Bug report summary

Installed Netdata into a Kubernetes cluster.  Nothing regarding Kubernetes or Docker or anything is reported on the dashboard.  A look at the logs I see stuff like this:

```
2019-10-24 22:20:07: go.d ERROR: coredns[coredns] Get http://127.0.0.1:9153/metrics: dial tcp 127.0.0.1:9153: connect: connection refused
2019-10-24 22:20:07: go.d ERROR: coredns[coredns] Check failed
```
```
2019-10-24 22:20:07: go.d ERROR: k8s_kubelet[k8s_kubelet] Get http://127.0.0.1:10255/metrics: dial tcp 127.0.0.1:10255: connect: connection refused
2019-10-24 22:20:07: go.d ERROR: k8s_kubelet[k8s_kubelet] Check failed
```
```
2019-10-24 22:20:18: cgroup-name.sh: WARNING: cannot find the name of k8s pod with containerID 'docker-7e7864cd7c5914903b157cbdd57a83d1bf798f5f15029fa171bb
a8c386a8ee4c.scope'. Setting name to docker-7e7864cd7c5914903b157cbdd57a83d1bf798f5f15029fa171bba8c386a8ee4c.scope and disabling it
2019-10-24 22:20:18: cgroup-name.sh: INFO: cgroup 'kubepods.slice_kubepods-podfbb1abc8_053e_11e9_b989_0050569d11bd.slice_docker-7e7864cd7c5914903b157cbdd57
a83d1bf798f5f15029fa171bba8c386a8ee4c.scope' is called 'docker-7e7864cd7c5914903b157cbdd57a83d1bf798f5f15029fa171bba8c386a8ee4c.scope'
2019-10-24 22:20:18: netdata ERROR : PLUGIN[cgroups] : child pid 81464 exited with code 3.
```

and it goes on and on......

##### OS / Environment

Red Hat 7.6 - Kubernetes 1.15.2 (installed via kubeadm)

##### Netdata version (ouput of `netdata -V`)

1.18.0

##### Component Name

Kubernetes

##### Steps To Reproduce

helm template --name netdata --set master.database.persistence=false --set master.alarms.persistence=false  ./netdata | kubectl apply -f -

##### Expected behavior

I'd see Kubernetes and related stats.

##### Other Info

CoreDNS as an example, shouldn't the connection be to kube-dns.kube-system.svc.cluster.local as opposed to localhost?:

```
nc -vvv kube-dns.kube-system.svc.cluster.local 9153
Connection to kube-dns.kube-system.svc.cluster.local 9153 port [tcp/*] succeeded!
```

Kubelet might be a configuration issue on my end.  I'm using a pretty standard vanilla install of Kubernetes via Kubeadm.  The kubelet service is listening on the secure port 10250 but not 10255 so not sure how to get connectivty to  10255 (read only port).

Any help would be great.

Thanks!

-Matt

**Comment by ilyam8** [comment]
hi @bitva77 

The urls are configurable, could you try to add 2nd job

> https://github.com/netdata/go.d.plugin/blob/52a2cc00fff1f9c8661bef16b84bdb112941a5cb/config/go.d/coredns.conf#L182-L183

```yaml
jobs:
  - url: http://127.0.0.1:9153/metrics
  - url: kube-dns.kube-system.svc.cluster.local
```

> listening on the secure port 10250

To get data from it we need authentication and ssl, am i right?

**Comment by bitva77** [comment]
Thanks!  So CoreDNS is good with this:

```
- url: http://kube-dns.kube-system.svc.cluster.local:9153/metrics
```

Regarding Kubelet - you have to authenticate.   Something like this within a pod will do it:

curl -sSk -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://kubelet.kube-system.svc.cluster.local:10250/metrics

This would be hitting the service though so who knows which node you'd actually be querying.  You'd instead want to specify a job for each node.

But the problem I see is getting that service account token.  Not sure how best to insert that into the ConfigMap (or if it's even the right way to go).

**Comment by ilyam8** [comment]
@bitva77 

> /var/run/secrets/kubernetes.io/serviceaccount/token

Is this default path? Is this token readable by netdata?

It looks like we need to add reading token from file functionality to the module.

You can add this manually btw

 - get token from file
 - add to the job following

```yaml
jobs:
  - url: http://127.0.0.1:10255/metrics
    headers:
      Authorization: 'Bearer <INSERT TOKEN HERE>'
```

I think it will work with this config.

**Comment by bitva77** [comment]
The token is generated every time the pod starts so I'm not sure how to populate ` Authorization: 'Bearer <INSERT TOKEN HERE>'` correctly.  I don't think there's a static token we can use (nor would that be the most secure).

Let me try to figure out how Prometheus is handling that.  It authenticates to the Kubelet some how as well

**Comment by bitva77** [comment]
Looks like Prometheus uses the token file as well:

```
- job_name: monitoring/kubelet/0
  honor_labels: true
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: https
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - kube-system
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
```

Could do an InitContainer on the slaves to populate the kubelet config file with the token.  Any other ideas?
