### ISSUE TITLE
[web_log] wrong timings

### ISSUE THREAD

**Issue by Wing924** [netdata/netdata#7234]
##### Bug report summary

web log module show wrong response  time.

<img width="575" alt="スクリーンショット 2019-10-31 9 39 02" src="https://user-images.githubusercontent.com/8895721/67909403-77952100-fbc2-11e9-87a4-96861d1cfae3.png">

##### OS / Environment

OS: CentOS release 6.3 (Final)
kernel: 2.6.32-279.22.1.el6.centos.plus.x86_64

##### Netdata version (ouput of `netdata -V`)

netdata v1.17.1

##### Component Name

web_log (python)

##### Expected behavior

min/max/avg should be < 1ms

**Comment by ilyam8** [comment]
Hi @Wing924 

Nginx logs? Did you check them? I wonder what the real values.

**Comment by Wing924** [comment]
### log example (apache log)
```
xx.xx.xx.xx - - [31/Oct/2019:16:48:53.354 +0900] "GET /healthcheck.pl HTTP/1.1" 200 350 "-" "check_http/v2.1.1 (nagios-plugins 2.1.1)" - " -" 3875 www2.example.com - "-" "-" "-" "-" "-"
xx.xx.xx.xx - - [31/Oct/2019:16:48:53.949 +0900] "GET /wwwcheck.pl HTTP/1.1" 200 318 "-" "-" - " -" 3822 www.example.com - "-" "-" "-" "-" "-"
xx.xx.xx.xx - - [31/Oct/2019:16:48:55.199 +0900] "GET /wwwcheck.pl HTTP/1.1" 200 318 "-" "-" - " -" 3932 www.example.com - "-" "-" "-" "-" "-"
```
### netdata config
```yaml
httpd:
  name: 'local'
  path: 'path/to/access_log'
  all_time: false
  histogram: ...
  custom_log_format:
    pattern: '(?P<address>[\da-f.:]+|localhost) -.*? "(?P<request>[^"]*)" (?P<code>[1-9]\d{2}) (?P<bytes_sent>\d+|-) "(?P<referer>([^\"]|\")*)" "(?P<agent>([^\"]|\")*)" (?P<cookie>[^ ]*) (?P<resp_time>\d+(\.\d+)?)'
```
