### ISSUE TITLE
Netdata on balena devices

### ISSUE THREAD

**Issue by OdysLam** [netdata/netdata#7288]
#7003

# Feature idea summary

[Balena](https://balena.io) is a fleet-management platform that brings docker containers on an array of Edge devices, such as Raspberry pi, Samsung Artik, Beaglebone, etc. It uses a modified version of docker containers (based on Moby) in order to make them as efficient as possible; Edge devices demand that due to their resource-constrained nature.

<img src="https://www.balena.io/docs/img/common/architecture.png" alt="alt text"  height="500">

It uses a subset of the docker-compose.yaml language to described multi-container applications. The application is built on the cloud and shipped as binaries to the devices, where an orchestrator setups the containerized services and manages the system/services.

The problem is that balena does not allow to mount volumes, thus at the moment, netdata's view of the device is fairly limited. 

I have opened a [post ](https://forums.balena.io/t/install-netdata-on-balena-device-raspberry-pi-3-issues-alternatives/42634) in the balena forums, to point it out to the balena team. 

I am writing this post due to PR #7287 . I suspect that something is in the works, so any tip or workaround fix is greatly appreciated!

Thank you for your time!  🙏

Cheers

**Comment by stelfrag** [comment]
Hi @OdysLam 

Thank you for using netdata and raising this issue here and also the balena forums. Indeed netdata
needs access e.g. to /proc to start collecting advanced metrics (the docker compose as you described lists the volumes)

**Comment by OdysLam** [comment]
Hey @stelfrag,

I haven't responded earlier as there seems to be an impasse at the moment. In order to load the volumes, one needs to modify the balena-supervisor source code. Albeit not particularly hard, the solution is neither production material nor an easy patch that any advanced sysadmin will like to make. 

Thus, I am waiting for the official response from the balena team in the forums. I will update here with any updates.

Cheers

**Comment by stelfrag** [comment]
@OdysLam thank you for the update.

Waiting for some good news from the balena team!

**Comment by dt-rush** [comment]
This is now possible as we've added labels to allow `:ro` mounting of `sysfs` and `procfs`.

Simply add the following as a service in your `docker-compose.yml`:

```
netdata:
        image: netdata/netdata
        ports:
            - "19999:19999"
        entrypoint: >-
            sh -c "ln -s /var/run/balena.sock /var/run/docker.sock &&
            /usr/sbin/run.sh"
        cap_add:
            - SYS_PTRACE
        security_opt:
            - 'apparmor:unconfined'
        labels:
            io.balena.features.sysfs: 1
            io.balena.features.balena-socket: 1
            io.balena.features.procfs: 1
```
