### ISSUE TITLE
go.d module doesn't load custom settings

### ISSUE THREAD

**Issue by iredmail** [netdata/netdata#7394]
##### Bug report summary

go.d doesn't load custom settings

##### OS / Environment

CentOS 7.

##### Netdata version (ouput of `netdata -V`)

```
# /opt/netdata/usr/sbin/netdata -V
netdata v1.19.0
```

##### Component Name

phpfpm

##### Steps To Reproduce

- Install nginx + php-fpm on a CentOS 7 box, configure nginx to server `https://localhost/status` page.
- Add custom `go.d/phpfpm.conf` with content below (it uses `https` instead of `http`):

```
jobs:
  - name: local
    url: https://localhost/status?full&json
    tls_skip_verify: yes
```

##### Expected behavior

Netdata should load this custom url with `https`, not the default one with `http`.
