### ISSUE TITLE
[discussion] generic log parser

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#7420]
##### Feature idea summary

It would be nice to have generic log parser. Idea is to check other solutions, understand use cases and prepare for writing.

Related:
- #3729
- #2813
- #4334

##### Expected behavior

To have enough info to start working on it.

**Comment by ilyam8** [comment]
> generic log parser

First of all what is parse?

Parse logic is simple. Parse a line simply means to split the line into named fields. 

That is what usually a log parser does:

Line:

```
203.0.113.2 - - [22/Mar/2009:09:30:31 +0100] "HEAD /example.org HTTP/2" 400 4028
```

Parsed Line:
```
"remote_client"="203.0.113.2",
"request"="HEAD /example.org HTTP/2",
"status_code"="400",
"bytes_sent"="4028"
```

___

In case of `netdata` in addition we need:
- Process parsed data (dashboard shows only received charts, all logic inside a collector)
- Create/update/delete charts (before start and during runtime)

Lets take [Weblog](https://github.com/netdata/go.d.plugin/tree/master/modules/weblog) module as an example.

In fact **it does no parsing**. The only things module does are:
- Process parsed data
- Create/update/delete charts

It is true for every netdata module since it is responsible for everything.

Ok, is it possible to describe `Weblog` logic via configuration file - i think no. 
It has some very specific parts (for example see [1](https://github.com/netdata/go.d.plugin/blob/2240677c2a61a8260a7b84cceda0f949a703cba8/modules/weblog/collect.go#L180-L216), [2](https://github.com/netdata/go.d.plugin/blob/2240677c2a61a8260a7b84cceda0f949a703cba8/modules/weblog/collect.go#L276-L301)).

> It is true for every netdata module since it is responsible for everything.

^^ We need specific log parser module for specific application. Because module is not parser, it is data processer/chart creator!

___

Based on `Weblog`, if the value is string, we could:
 1. count number of occurrences per pattern per field (ex.: matches per user defined url pattern against reqURI field).
 2. count number of occurrences per value (ex.: req per vhosts, status code etc.)

If the value is int/float:
 1. calc summary (min, avg, max)
 2. calc histogram (use defined buckets)
 3. use exact value
 4. add the value on every iteration


Original request
> Monitor an application specific log file and then create a chart based on occurrences of a log line.

This one is easy to implement, but we need to think on all features from start and find a good ratio between flexibility and complexity.

That is another requests:

> Graphing the latency of each user over time by regexing out the username and latency value would be awesome.

Line:

> User xyz has performed an action with a latency of 502ms

it is app specific or we could add some cross fields calculation?

**Comment by ilyam8** [comment]
@markptrueman @Thijzer @LeeNX @hamedbrd (why you? you were in generic log parse relsated issued 😄) lets discuss, i want to understand your use cases to see what we need to implement.

**Comment by ilyam8** [comment]
To make it easier - we have a line parsed into list of `key`, `value` pairs.

We need to describe processing data/charts in the config.

A quick thought - probably we need diferent types of chart, eash of them will implement its own logic, will have its own configuration. 

I mean:
 - count number of occurrences per pattern per field (static num of dimensions - num of patterns)
 - count number of occurrences per value (new dimension for every value).

It looks better/easier than a chart with a lot of options/switches.

**Comment by ilyam8** [comment]
Again, how i understand it - we are not talking about parser, we are talking about [synthetic charts](https://docs.netdata.cloud/collectors/statsd.plugin/#synthetic-statsd-charts) analog.

Data is parsed (list of `name, value` pairs), we need to create some charts using it.

I think we need **list of predefined templates**. One template per use case.

Use cases so far:
 - string: count number of matches per pattern per field
 - string: count number of occurences value in the field
 - int/float: calculate summary
 - int/float: calculate histogram
 - int/float: chart value

___

That is example (just to show the gist, namings are lame).

User set format, there we have N named fields.

```yaml
  - name: "name1"
    path: /path/to/file.log
    log_type: csv
    csv_config:
      format: '- - $field1 - - $field2 $field3 $field4 $field5 $field6 $field7'
```

We are using these fields to create charts.

 - string: count number of matches per pattern per field

```yaml
jobs:
    charts_matches:
      - chart: 'name title units family context type algorithm'
        dimensions:
          - 'PATTERN name'
          - 'PATTERN name'
        stop_on_first: yes
        field: $field1
```

- string: count number of occurences value in the field

```yaml
    charts_occurrences:
      - chart: 'name title units family context type algorithm'
        field: $field2
      - chart: 'name title units family context type algorithm'
        field: $field3
```


 - int/float: calculate summary

```yaml
    charts_summary:
      - chart: 'name title units family context type algorithm'
        field: $field4
```

 - int/float: calculate histogram

```yaml
    charts_hitogram:
      - chart: 'name title units family context type algorithm'
        histogram: [1,3,10,30,100]
        field: $field5
```

 - int/float: chart value

```yaml
      - chart: 'name title units family context type algorithm'
        fields: [$field6, $field7]
        dimensions:
          - 'name divisor multiplier'
          - 'name divisor multiplier'
```

___

I really dont know for now how make templates not verbose and clear at the same time. 

> chart: 'name title units family context type algorithm'

This is not good at all, there is hardcoded order, it is easy to make a mistake.

But following looks verbose (though i prefer it):

```yaml
chart:
  name: name
  title: title
  units: units
  family: family
  context: context
  type: type
  algorithm: algorithm
```
