### ISSUE TITLE
Trying to use ssl_protocol and ssl_cipher in web_log

### ISSUE THREAD

**Issue by edwade** [netdata/netdata#7446]
#### Question summary
I am trying to get ssl_protocol and ssl_cipher in to the web_log as per #7245 
##### OS / Environment
Ubuntu 18.04.3 LTS
##### Component Name
Go.d WebLog
##### Expected results
I am expecting to see the ssl_cipher and protocol in the charts but they're not appearing. Log format is:
```
log_format netdata '$remote_addr - $remote_user [$time_local] '
                      '"$request" $status $body_bytes_sent '
                      '$request_length $request_time $upstream_response_time '
                      '"$http_referer" "$http_user_agent" '
                      '$ssl_protocol $ssl_cipher';
```

The details are not shown when using either the web interface or the command `sudo -u netdata /usr/libexec/netdata/plugins.d/go.d.plugin -d -m web_log`

**Comment by ilyam8** [comment]
Hi @edwade 

You need to use custom log format to get `ssl_*` stuff charted.

> https://github.com/netdata/go.d.plugin/tree/master/modules/weblog#custom-log-format


```yaml
jobs:
  - name: nginx_with_ssl
    path: /path/to/file.log
    log_type: csv
    csv_config
      format: '- - $remote_addr - - [$time_local] "$request" $status $body_bytes_sent $request_length $request_time $upstream_response_time - - $ssl_protocol $ssl_cipher'
```
