### ISSUE TITLE
Configuration management files (Chef, Puppet, Saltstack, Ansible, etc)

### ISSUE THREAD

**Issue by saivert** [netdata/netdata#798]
We need a collection of files for automating the installation of netdata.

I bring you one for Saltstack, it might not be perfect but at least it ran on Debian.

```
pkg_autoconf:
  pkg.installed:
  {% if grains['os'] == 'Gentoo'%}
    - name: sys-devel/autoconf
  {% else %}
    - name: autoconf
  {% endif %}

pkg_autoconf_archive:
  pkg.installed:
  {% if grains['os'] == 'Gentoo'%}
    - name: sys-devel/autoconf-archive
  {% else %}
    - name: autoconf-archive
  {% endif %}

pkg_autogen:
  pkg.installed:
  {% if grains['os'] == 'Gentoo'%}
    - name: sys-devel/autogen
  {% else %}
    - name: autogen
  {% endif %}

pkg_automake:
  pkg.installed:
  {% if grains['os'] == 'Gentoo'%}
    - name: sys-devel/automake
  {% else %}
    - name: automake
  {% endif %}

pkg_curl:
  pkg.installed:
  {% if grains['os'] == 'Gentoo'%}
    - name: net-misc/curl
  {% else %}
    - name: curl
  {% endif %}

pkg_git:
  pkg.installed:
  {% if grains['os'] == 'Gentoo'%}
    - name: dev-vcs/git
  {% else %}
    - name: git
  {% endif %}

pkg_gcc:
  pkg.installed:
  {% if grains['os'] == 'Gentoo'%}
    - name: sys-devel/gcc
  {% else %}
    - name: gcc
  {% endif %}

pkg_iproute2:
  pkg.installed:
  {% if grains['os'] == 'Debian'%}
    - name: iproute2
  {% elif grains['os'] == 'Gentoo'%}
    - name: sys-apps/iproute2
  {% elif grains['os'] == 'Ubuntu' and grains['osrelease'] == '12.04' %}
    - name: iproute
  {% else %}
    - name: iproute
  {% endif %}

pkg_libz_dev:
  pkg.installed:
  {% if grains['os'] == 'Arch'%}
    - name: zlib
  {% elif grains['os'] == 'Debian'%}
    - name: zlib1g-dev
  {% elif grains['os'] == 'Gentoo'%}
    - name: sys-libs/zlib
  {% elif grains['os'] in ['CentOS', 'RedHat', 'Suse'] %}
    - name: zlib-devel
  {% else %}
    {% 'Do not know how to install this package' %}
  {% endif %}

pkg_libuuid_dev:
  pkg.installed:
  {% if grains['os'] == 'Arch'%}
    - name: util-linux
  {% elif grains['os'] == 'Debian'%}
    - name: uuid-dev
  {% elif grains['os'] == 'Gentoo'%}
    - name: sys-apps/util-linux
  {% elif grains['os'] in ['CentOS', 'RedHat', 'Suse'] %}
    - name: libuuid-devel
  {% else %}
    {% 'Do not know how to install this package' %}
  {% endif %}

pkg_libmnl_dev:
  pkg.installed:
  {% if grains['os'] == 'Arch'%}
    - name: libmnl
  {% elif grains['os'] == 'Debian'%}
    - name: libmnl-dev
  {% elif grains['os'] == 'Gentoo'%}
    - name: net-libs/libmnl
  {% elif grains['os'] in ['CentOS', 'RedHat'] %}
    - name: libmnl-devel
  {% elif grains['os'] == 'Suse' %}
    - name: libmnl0
  {% else %}
    {% 'Do not know how to install this package' %}
  {% endif %}


pkg_make:
  pkg.installed:
  {% if grains['os'] == 'Gentoo'%}
    - name: sys-devel/make
  {% else %}
    - name: make
  {% endif %}


pkg_netcat:
  pkg.installed:
  {% if grains['os'] == 'Arch'%}
    - name: netcat
  {% elif grains['os'] == 'Debian'%}
    - name: netcat
  {% elif grains['os'] == 'Gentoo'%}
    - name: net-analyzer/netcat
  {% elif grains['os'] in ['CentOS', 'RedHat'] %}
    - name: nmap-ncat
  {% elif grains['os'] == 'Suse' %}
    - name: netcat-openbsd
  {% else %}
    - name: netcat
  {% endif %}


pkg_pkg_config:
  pkg.installed:
  {% if grains['os'] == 'Arch'%}
    - name: pkgconfig
  {% elif grains['os'] == 'Debian'%}
    - name: pkg-config
  {% elif grains['os'] == 'Gentoo'%}
    - name: dev-util/pkgconfig
  {% elif grains['os'] in ['CentOS', 'RedHat'] %}
    - name: pkgconfig
  {% elif grains['os'] == 'Suse' %}
    - name: pkg-config
  {% else %}
    - name: pkg-config
  {% endif %}



netdatarepo:
  git.latest:
    - name: https://github.com/firehol/netdata.git
    - depth: 1
    - target: /root/netdatagit
    - force_reset: True

netdatainstall:
  require:
    - git: netdatarepo
    - pkg: pkg_git
    - pkg: pkg_gcc
    - pkg: pkg_make
    - pkg: pkg_autoconf
    - pkg: pkg_autogen
    - pkg: pkg_automake
    - pkg: pkg_pkg_config
  cmd.run:
    - cwd: /root/netdatagit
    - name: ./netdata-installer.sh

```

**Comment by ktsaou** [comment]
Thanks!

So, this file should just be included with netdata? in `system/netdata.saltstack` for example?

**Comment by saivert** [comment]
I wouldn't recommend that yet. It is far from complete. I also believe that what install-required-packages.sh script does should be done properly by saltstack using pillars for various distros. Running external scripts should be minimized as much as possible because saltstack can't do proper error checking. All it knows is whether the script executed or not. Also this .sls file is only for Debian based distros as it refers to git-core package which doesn't exist anywhere else (it is just called git on Fedora/Centos). I was not so secretly hoping someone would come along and fix up my script as I have just started learning Saltstack.

**Comment by saivert** [comment]
I have updated the state file now. Using templating and grains you can easily do the right thing depending on what distro you are targetting.

**Comment by jffz** [comment]
Also worked to make it in an ansible playbook.

RHEL
```yaml
---
- name: "Installation pré-requis"    
  yum:
    name: "{{ item }}"
    state: present
  with_items: 
    - autoconf
    - autoconf-archive
    - autogen
    - automake
    - curl
    - gcc
    - git
    - jq
    - libmnl-devel
    - libuuid-devel
    - make
    - pkgconfig
    - zlib-devel

- name: "Clone repo"
  git:
    clone: yes
    repo: https://github.com/firehol/netdata.git
    dest: /tmp/netdata

- name: "Installation"
  shell: cd /tmp/netdata/ && ./netdata-installer.sh --dont-wait --libs-are-really-here

- name: "Clean /tmp"
  file:
    path: /tmp/netdata
    state: absent

- name: "KillAll"
  shell: killall netdata

- name: "Configuration du daemon"
  systemd:
    daemon_reload: yes
    name: netdata
    enabled: yes
    state: started
```

Debian
```yaml
---
- name: "Installation pré-requis"    
  yum:
    name: "{{ item }}"
    state: present
  with_items: 
    - zlib1g-dev
    - uuid-dev
    - libmnl-dev
    - gcc
    - make
    - git
    - autoconf
    - autoconf-archive
    - autogen
    - automake
    - pkg-config

- name: "Clone repo"
  git:
    clone: yes
    repo: https://github.com/firehol/netdata.git
    dest: /tmp/netdata

- name: "Installation"
  shell: cd /tmp/netdata/ && ./netdata-installer.sh --dont-wait --libs-are-really-here

- name: "Clean /tmp"
  file:
    path: /tmp/netdata
    state: absent

- name: "KillAll"
  shell: killall netdata

- name: "Configuration du daemon"
  systemd:
    daemon_reload: yes
    name: netdata
    enabled: yes
    state: started
```

**Comment by paulfantom** [comment]
@jffz I think your Debian version won't work since it has `yum` directive. Also you can merge those two with use of ansible facts and `when` directive.

**Comment by jffz** [comment]
Huh I missed my paste. I was thinking about doing a cross distro playbook.
Ô will update soon

**Comment by jffz** [comment]
Here is a cross distro playbook. @paulfantom, what do you want me to check with facts ? 

```yaml
---
- name: "Installation pré-requis"    
  apt:
    name: "{{ item }}"
    state: present
  with_items: 
    - autoconf
    - autoconf-archive
    - autogen
    - automake
    - gcc
    - git
    - libmnl-dev
    - make
    - pkg-config
    - uuid-dev
    - zlib1g-dev
  when: ansible_os_family == "Debian"

- name: "Installation pré-requis"    
  yum:
    name: "{{ item }}"
    state: present
  with_items: 
    - autoconf
    - autoconf-archive
    - autogen
    - automake
    - curl
    - gcc
    - git
    - jq
    - libmnl-devel
    - libuuid-devel
    - make
    - pkgconfig
    - zlib-devel
  when: ansible_os_family == "RedHat"

- name: "Clone repo"
  git:
    clone: yes
    repo: https://github.com/firehol/netdata.git
    dest: /tmp/netdata

- name: "Installation"
  shell: cd /tmp/netdata/ && ./netdata-installer.sh --dont-wait --libs-are-really-here

- name: "Clean /tmp"
  file:
    path: /tmp/netdata
    state: absent

- name: "KillAll"
  shell: killall netdata

- name: "Configuration du daemon"
  systemd:
    daemon_reload: yes
    name: netdata
    enabled: yes
    state: started
```
