### ISSUE TITLE
Unable to get functional netdata with docker image

### ISSUE THREAD

**Issue by cpw** [netdata/netdata#8083]
I am trying to use the docker image for netdata to monitor a host, relatively persistently. On-host monitoring is ok, but the convenience of docker management makes it attractive vs having to ssh into the box every few days to recover a crashed netdata instance.

##### Bug report summary

I installed the docker v1.19.0 image (the latest tag is about 1.15 or so?!) and it gives an error when accessing the dashboard:
```
curl 172.17.0.3:19999
Access to file is not permitted: &#x2F;usr&#x2F;share&#x2F;netdata&#x2F;web&#x2F;&#x2F;index.html
```

##### OS / Environment

docker compose file I just tested locally to pop up a container:
```
version: '2'
services: 
    netdata:
        image: 'netdata/netdata:v1.19.0'
        container_name: 'netdata'
        network_mode: 'bridge'
        hostname: 'cerberus'
        restart: 'always'
        cap_add:
            - SYS_PTRACE
        security_opt:
            - apparmor:unconfined
        volumes:
            - /etc/passwd:/host/etc/passwd:ro
            - /etc/group:/host/etc/group:ro
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /etc/os-release:/host/etc/os-release:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /srv/netdata/config:/etc/netdata
            - netdatadb:/var/cache/netdata
            - netdata:/var/lib/netdata
        environment:
            - DOCKER_USR=root
        labels: 
            traefik.enable: 'true'
            traefik.http.routers.netdata.entrypoints: 'websecure'
            traefik.http.routers.netdata.middlewares: 'auth@file'
            traefik.http.routers.netdata.rule: 'Host(`****`)'
            traefik.http.routers.netdata.tls.certresolver: '****'
volumes: 
    netdata:
    netdatadb:
```

##### Netdata version

 It should be 1.19? I notice that the "latest" tag works, but is 1.15, which has annoying db engine weirdness. I was hoping to use 1.19 instead.

##### Component Name

web component

##### Steps To Reproduce

1. Deploy docker-compose configuration above.
2. Try and access the netdata dashboard.

##### Expected behavior

I expected to get a netdata instance...

Is the only functional netdata docker image the "latest" tag, running 1.15-xxx (not very latest)?

**Comment by prologic** [comment]
Hi @cpw :)

I took your `docker-compose.yml` and _only_ slightly modified it a little bit and got it working on my macOS Desktop with Docker for Desktop without issue.

This is what I did:

```yaml
version: '2'
services: 
    netdata:
        image: 'netdata/netdata:v1.19.0'
        container_name: 'netdata'
        network_mode: 'bridge'
        hostname: 'cerberus'
        restart: 'always'
        cap_add:
            - SYS_PTRACE
        security_opt:
            - apparmor:unconfined
        volumes:
            - /etc/passwd:/host/etc/passwd:ro
            - /etc/group:/host/etc/group:ro
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /etc/os-release:/host/etc/os-release:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - netdataconfig:/etc/netdata
            - netdatadb:/var/cache/netdata
            - netdatalib:/var/lib/netdata
        environment:
            - DOCKER_USR=root
volumes: 
    netdataconfig:
    netdatalib:
    netdatadb:
```

```sh
$ docker-compose up -d
Creating volume "test-8083_netdataconfig" with default driver
Creating volume "test-8083_netdatalib" with default driver
Recreating netdata ... done
$ docker-compose ps
 Name         Command        State     Ports
----------------------------------------------
netdata   /usr/sbin/run.sh   Up      19999/tcp
```

And was able to access the API:

```sh
$ curl -q -s localhost:19999/api/v1/info | jq '.version'
"v1.19.0"
```

I'm not seeing the issue you posted above here... Can you help me understand more about what's going on for you or not going on?

**Comment by ilyam8** [comment]
i used config from OP and got same result

```console
test@DEB10-1:~$ IP=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' netdata); curl http://$IP:19999

Access to file is not permitted: &#x2F;usr&#x2F;share&#x2F;netdata&#x2F;web&#x2F;&#x2F;index.htmltest@DEB10-1:~$
```

**Comment by ilyam8** [comment]
not a specialist, @cpw why dont you add

```
    ports:
      - 19999:19999
```

?

**Comment by prologic** [comment]
My repro is likely invalid; sorry about that. Let me see what's going on her.e...

**Comment by prologic** [comment]
I added:

```yaml
ports:
  - "29999:19999/tcp"
```

And it works:

```sh
$ curl -q -s -o - http://localhost:29999/api/v1/info | jq '.version'
"v1.19.0"
```

I forgot I also have a NetData on my iMac / localhost 🤣

**Comment by prologic** [comment]
You definitely need to expose the port(s) in some way to be accessible.

**Comment by cpw** [comment]
You don't need to expose the ports. You can access the container on it's docker associated IP address - this works well. If you look, i have traefik labels to do front end configuration. It seems several are able to reproduce. Note: the API isn't the problem - the web UI is the issue. The API responds fine. But netdata isn't very useful if I can't access the Web UI.

**Comment by prologic** [comment]
Oh I see... Sorry for the confusion; let me poke around a bit more and get back to you. I also run/use Traefik here as well and do something fairly similar to you. I'll respond back with my findings soon.

**Comment by prologic** [comment]
And it all works :)

![run](https://user-images.githubusercontent.com/1290234/74501493-10636880-4f36-11ea-9dec-8c96ca6827d9.png)

**Comment by prologic** [comment]
Sorry about previous Email/Notification -- Wrong Issue!

**Comment by ilyam8** [comment]
> http://localhost:29999/api/v1/info

`/api/v1/info` works because error is 

> Access to file is not permitted: /usr/share/netdata/web//index.html


try `http://localhost:29999`

**Comment by prologic** [comment]
> Access to file is not permitted: /usr/share/netdata/web//index.html

<img width="1312" alt="Screen Shot 2020-02-14 at 17 51 41" src="https://user-images.githubusercontent.com/1290234/74511871-b1601c80-4f52-11ea-980c-27b1256063eb.png">

I see the same thing too ☝️ Hmmm 🤔

**Comment by prologic** [comment]
I _believe_ this is coming from:

```sh
prologic@Jamess-iMac
Fri Feb 14 17:53:03
~/NetData/netdata
 (kernel_collector_integration) 0
$ sift 'Access to file is not permitted'
web/server/web_client.c:338:    buffer_strcat(w->response.data, "Access to file is not permitted: ");
docs/step-by-step/step-08.md:76:If you get a blank page with this text: `Access to file is not permitted: /usr/share/netdata/web/custom-dashboard.html`.
```

**Comment by prologic** [comment]
Hmmm 🤔 very strange...

The files are owned by `netdata/netdata`, the process is running as `root` and there's an access/permission problem? 

```sh
prologic@Jamess-iMac
Fri Feb 14 17:54:03
~/tmp/test-8083
 125
$ docker-compose ps
 Name         Command        State            Ports
-------------------------------------------------------------
netdata   /usr/sbin/run.sh   Up      0.0.0.0:29999->19999/tcp

prologic@Jamess-iMac
Fri Feb 14 17:54:07
~/tmp/test-8083
 0
$ dps
CONTAINER ID        IMAGE                     COMMAND              CREATED             STATUS              PORTS                      NAMES
b029a44dbb09        netdata/netdata:v1.19.0   "/usr/sbin/run.sh"   7 hours ago         Up 7 hours          0.0.0.0:29999->19999/tcp   netdata

prologic@Jamess-iMac
Fri Feb 14 17:54:08
~/tmp/test-8083
 0
$ dke -t b029a44dbb09 /bin/sh
/ # ps aux
PID   USER     TIME  COMMAND
    1 root      3:55 /usr/sbin/netdata -u root -D -s /host -p 19999
   43 root      0:21 /usr/libexec/netdata/plugins.d/go.d.plugin 1
   64 root      0:05 /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
 1063 root      1:19 /usr/libexec/netdata/plugins.d/apps.plugin 1
 1064 root      0:00 /bin/sh
 1069 root      0:00 ps aux
/ # ls -lah /usr/share/netdata/web//index.html
-rw-rw-r--    1 netdata  netdata   126.5K Nov 27 22:51 /usr/share/netdata/web//index.html
/ # whoami
root
/ #
```

**Comment by prologic** [comment]
When I hit http://localhost:2999/ This is what I get in the `error.log`:

```
2020-02-14 07:58:48: 6: 28 '[172.17.0.1]:34508' 'CONNECTED'
2020-02-14 07:58:48: 4: 28 '[172.17.0.1]:34502' 'DATA' (sent/all = 95/97 bytes -2%, prep/sent/total = 0.05/0.08/0.13 ms) 403 '/'
2020-02-14 07:58:48: 4: 28 '[172.17.0.1]:34502' 'DATA' (sent/all = 93/92 bytes -20050808775771250688%, prep/sent/total = 0.06/0.07/0.13 ms) 403 '/favicon.ico'
```

Doesn't seem to give any hint as to what's going wrong though 😢

**Comment by prologic** [comment]
As a quick work-around I did this:

```sh
$ dke -t b029a44dbb09 /bin/sh
/usr/share/netdata # chown -R root:root web
/usr/share/netdata #
```

And now it works

**Comment by prologic** [comment]
`dke` => `alias dke='docker exec`

**Comment by prologic** [comment]
I _think_ I sort of understand what's going on here... First up running NetData as `root` is a bad idea `DOCKER_USR=root` -- This breaks (_for some reason I don't fully understand yet_) NetData's ability to read the files in files in `/usr/share/netdata/web` (_which makes no sense to me_).

Secondly; the volumes:

```yaml
            - netdatadb:/var/cache/netdata
            - netdata:/var/lib/netdata
```

Seem to cause problems which needs further investigation.

**Comment by prologic** [comment]
@Ferroin I _may_ not be able to get back to this in my today so if you could have a look I'd appreciate it! I've added it to our backlog.

**Comment by IvanTurgenev** [comment]
adding `- DOCKER_USR=root` fixed it for me

```
version: '3'
services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: anservusgog # set to fqdn of host
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - ./config:/etc/netdata
    environment:
      - DOCKER_USR=root 
      - DOCKER_HOST=proxy:2375
      - VIRTUALIZATION=kvm
  proxy:
    container_name: netdata_proxy
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1


```
