### ISSUE TITLE
feat: aggregate jobs

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#8252]
##### Feature idea summary

Job is a collection module instance with a specific parameters. Every job of the same module produces ~ same set of charts.

Currenlty there is no way to have aggregated statistics w/o exporting metrics to some external db and useing some tool to sum metrics.

Example of go `web_log` configuration:

```yaml
jobs:
  - name: nginx
    path: /var/log/nginx/access.log
  - name: apache
    path: /var/log/apache2/access.log
```

Aggregated job would produce summary metrics for both `nginx` and `apache` jobs. It could have following config:

```yaml
aggregated_jobs:
  - name: ngix_and_apache
    jobs:
      - name: nginx
        path: /var/log/nginx/access.log
      - name: apache
        path: /var/log/apache2/access.log
```

Or just:

```yaml
aggregated_jobs:
  - name: ngix_and_apache
    jobs:
      - name: nginx  # use nginx job from `jobs:` section
      - name: apache # use apache job from `jobs:` section
```

___

It sounds useful to me, but i would like to hear some comments on it.

##### Expected behavior

Have aggregated jobs.
