### ISSUE TITLE
`go.d.conf` modules format is confusing

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#8390]
@ilyam8 

Thanks, I got it sorted out, few things that I had missed or messed up.

1.) In "go.d.conf" I had uncommented mysql line but accidentally removed space from start.
2.) My go.d/mysql.conf was broken

_Originally posted by @WerdPress in https://github.com/netdata/netdata/issues/8370#issuecomment-597318547_

- `python.d.conf`

```yaml
key: value
key: value
...
```

 - `go.d.conf`

```yaml
key: value
key: value

modules:
# name: yes
# name: yes
  ...

...
```

go.d.conf modules format is a source of problems, it is very easy to broke it if you remove a space before a module name.

Broken config example:

```yaml
key: value
key: value

modules:
name: yes
```

We need to handle the problem case and make it python.d.conf like
