### ISSUE TITLE
Incorrect netdata hostname

### ISSUE THREAD

**Issue by PixiBixi** [netdata/netdata#8440]
##### Bug report summary
Hi everyone, i launch netdata with a Docker container, i have an issue to setup the hostname, there's my docker-compose.yml file

```
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: netdata.yann.domain.tld
    restart: always
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/dl/netdata.conf:/etc/netdata/orig/health_alarm_notify.conf:rw
    environment:
      - PGID=998
      - VIRTUAL_HOST=netdata.yann.domain.tld
      - LETSENCRYPT_EMAIL=x@y.fr
      - LETSENCRYPT_HOST=netdata.yann.domain.tld
```

##### OS / Environment
```
Linux yann.lw.domain.tld 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux

Debian GNU/Linux 10 (buster)

docker-compose version 1.25.4, build unknown
docker-py version: 4.2.0

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
```

##### Netdata version
netdata v1.19.0-100-g7278d5bc
 

##### Component Name
Web component i assume

##### Steps To Reproduce
1. Fresh Debian 10 install with Docker, docker-compose
2. Run my docker-compose (Expose ports 19999 might by easier for you)

##### Expected behavior
In my hostname, i except to see `netdata.yann.domain.tld` however, i only see netdata hostname...

However, the hostname is correctly setup in my container : 

```
λ yann ~ → docker exec -ti netdata hostname
netdata
λ yann ~ → docker exec -ti netdata hostname -f
netdata.yann.domain.tld
```

I assume somewhere in your code, you need to replace hostname by hostname -f ?

I have this issue only with Debian 10 and these Docker version, with Debian 9 and Docker 18.09.2, there's no problem.
