### ISSUE TITLE
[new collector]: traefik v2

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#8600]
##### Feature idea summary

[python traefik  module](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/traefik) doesnt work with v2. We need to update it or write a new collector support 2.x.

##### Expected behavior

collect metrics from traefik v2.x

**Comment by ilyam8** [comment]
@knatsakis 

Could you share traefikv2 [metrics](https://docs.traefik.io/v1.7/configuration/metrics/#prometheus)?

**Comment by knatsakis** [comment]
You could use the local-dev-env for that. I will share details privately.

**Comment by agustinvinao** [comment]
Hi, @knatsakis do you have a running example on traefik v2 to share please thanks

**Comment by knatsakis** [comment]
Hi @agustinvinao, I am not sure what you mean here?

Do you mean a public traefik v2 instance that provides metrics? If, so, unfortunately, no, I don't have an instance to provide.

Could you clarify a bit?

**Comment by agustinvinao** [comment]
@knatsakis Im trying to use netdata using docker and traefik:

```yml
version: '3.7'
networks:
  default:
    name: $NETWORK
    external: true
services:
  netdata:
    image: netdata/netdata
    hostname: $HOSTNAME
    networks:
      - default
    cap_add:
      - SYS_PTRACE
    volumes:
      - $USERDIR/docker/netdata/netdatalib:/var/lib/netdata
      - $USERDIR/docker/netdata/netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    deploy:
      placement:
        constraints:
          - 'node.role == manager'
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "true"
        traefik.docker.network: $NETWORK
        # HTTP Routers
        traefik.http.routers.netdata.rule: Host(`performance.$DOMAIN_NAME`)
        traefik.http.routers.netdata.tls.certresolver: $CERT_RESOLVER
        traefik.http.routers.netdata.entrypoints: "websecure"
        traefik.http.routers.netdata.tls: "true"
        # Middlewares
        traefik.http.routers.netdata.middlewares: "authtraefik"
        # HTTP Services
        traefik.http.routers.netdata.service: "netdata"
        traefik.http.services.netdata.loadbalancer.server.port: 19999
```

This is my docker-compose file, but it doesn't work. If you have a docker-compose setup that may help

**Comment by knatsakis** [comment]
I am using the following:

```
---
version: '3.7'

networks:
  default:
    external:
      name: 'netdata'

services:
  netdata:
    cap_add:
      - 'SYS_PTRACE'
    command: >-
      -W set statsd "bind to" "udp:*:8125 tcp:*:8125"
    container_name: 'netdata'
    hostname: 'netdata'
    image: 'netdata:latest'
    labels:
      traefik.enable: 'true'
      traefik.http.services.netdata.loadbalancer.server.port: '19999'

      traefik.http.routers.netdata-router-0.entrypoints: 'https'
      traefik.http.routers.netdata-router-0.middlewares: 'netdata-middleware-redirectregex'
      traefik.http.routers.netdata-router-0.rule: 'Path(`/netdata`)'
      traefik.http.routers.netdata-router-0.service: 'netdata'
      traefik.http.routers.netdata-router-0.tls: 'true'

      traefik.http.routers.netdata-router-1.entrypoints: 'https'
      traefik.http.routers.netdata-router-1.middlewares: 'netdata-middleware-replacepathregex'
      traefik.http.routers.netdata-router-1.rule: 'PathPrefix(`/netdata/`)'
      traefik.http.routers.netdata-router-1.service: 'netdata'
      traefik.http.routers.netdata-router-1.tls: 'true'

      traefik.http.middlewares.netdata-middleware-redirectregex.redirectregex.permanent: 'true'
      traefik.http.middlewares.netdata-middleware-redirectregex.redirectregex.regex: '^(https?://.*/netdata)$$'
      traefik.http.middlewares.netdata-middleware-redirectregex.redirectregex.replacement: '$${1}/'

      traefik.http.middlewares.netdata-middleware-replacepathregex.replacepathregex.regex: '^/netdata/(.*)'
      traefik.http.middlewares.netdata-middleware-replacepathregex.replacepathregex.replacement: '/$${1}'
    ports:
      - '8125:8125/tcp'
      - '8125:8125/udp'
      - '19999:19999'
    security_opt:
      - 'apparmor:unconfined'
    volumes:
      - '/etc/group:/host/etc/group:ro'
      - '/etc/passwd:/host/etc/passwd:ro'
      - '/proc:/host/proc:ro'
      - '/sys:/host/sys:ro'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
```

for netdata and:

```
---
version: '3.7'

networks:
  default:
    external:
      name: 'netdata'

services:
  traefik:
    container_name: 'traefik'
    environment:
      TRAEFIK_ACCESSLOG:                         'true'
      TRAEFIK_API_INSECURE:                      'true'
      TRAEFIK_METRICS_PROMETHEUS:                'true'
      TRAEFIK_ENTRYPOINTS_HTTP_ADDRESS:          ':80'
      TRAEFIK_ENTRYPOINTS_HTTPS_ADDRESS:         ':443'
      TRAEFIK_PROVIDERS_DOCKER:                  'true'
      TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT: 'false'
      TRAEFIK_PROVIDERS_FILE_DIRECTORY:          '/etc/traefik'
    hostname: 'traefik'
    image: 'docker.io/traefik:2.1.4'
    labels:
      traefik.enable: 'true'
      traefik.http.services.traefik.loadbalancer.server.port: '80'

      traefik.http.routers.traefik-router-0.entrypoints: 'http'
      traefik.http.routers.traefik-router-0.middlewares: 'app-middleware-redirectscheme'
      traefik.http.routers.traefik-router-0.rule: 'PathPrefix(`/`)'
      traefik.http.routers.traefik-router-0.service: 'traefik'

      traefik.http.middlewares.app-middleware-redirectscheme.redirectscheme.port: '8443'
      traefik.http.middlewares.app-middleware-redirectscheme.redirectscheme.scheme: 'https'
    ports:
      - '8080:80'
      - '8443:443'
      - '8000:8080'
    volumes:
      - '.traefik:/etc/traefik:ro'
      - '/var/run/docker.sock:/var/run/docker.sock:rw'
```

for traefik.

Hope it helps!
