### ISSUE TITLE
Memcached connect over socket

### ISSUE THREAD

**Issue by prodigystd** [netdata/netdata#8607]
Hello everyone!
I am trying to connect memcached over socket file in centos 7.
I have read the following docs and examples:
> https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/memcached
> https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/memcached/memcached.conf

So, I am using the following confing:

```yaml
localmem:
  name     : 'memcached local'
  socket   : '/tmp/memcached.sock' # I tried 'unix:///tmp/memcached.sock' too.
  update_every: 1         # the JOB's data collection frequency
  priority: 60000         # the JOB's order on the dashboard
  penalty: yes            # the JOB's penalty
  autodetection_retry: 0  # the JOB's re-check interval in seconds
```

Memcached itself run as a service with the following config:

```cmd
PORT="11211"
USER="someuser"
MAXCONN="1024"
CACHESIZE="1024"
OPTIONS="-t 18 -s /tmp/memcached.sock"
```

But, still is not working.
So, what I am doing wrong?
