### ISSUE TITLE
Design and implement Generic Prometheus Collector

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#8613]
##### Feature idea summary

A new internal collector based on the statsd code. This collector will scrape an arbitrary number of prometheus `/metrics` endpoints, and convert the data to a collection of Netdata charts. The conversion will be an extension of the synthetics charts functionality.

Related issues:
* #7897 

---

We decided to implement it in `golang`, not in `c`. Main reason is having it in `golang` we able to use prometheus query engine from prometheus project.

**Comment by KlavsKlavsen** [comment]
I would very much like this as well - since we have hosts that are behind NAT - and we already use netdata proxy setup - so metrics are streamed to a central netdata - and it would be fantastic to just add prometheus /metric endpoints for a netdata agent to scrape, so it got streamed to our netdata proxy.

**Comment by ilyam8** [comment]
We have no all detailes it is in _grooming_ state.

We collect metrics from some application that exposes data in prometheus format. They are:

- [cockroachdb](https://github.com/netdata/go.d.plugin/tree/master/modules/cockroachdb#cockroachdb-monitoring-with-netdata)
- [coredns](https://github.com/netdata/go.d.plugin/tree/master/modules/coredns#coredns-monitoring-with-netdata)
- [docker_engine](https://github.com/netdata/go.d.plugin/tree/master/modules/docker_engine#docker-engine-monitoring-with-netdata)
- [kubelet](https://github.com/netdata/go.d.plugin/tree/master/modules/k8s_kubelet#kubelet-monitoring-with-netdata)
- [kube-proxy](https://github.com/netdata/go.d.plugin/tree/master/modules/k8s_kubeproxy#kube-proxy-monitoring-with-netdata)
- [pulsar](https://github.com/netdata/go.d.plugin/tree/master/modules/pulsar#apache-pulsar-monitoring-with-netdata)
- [vernemq](https://github.com/netdata/go.d.plugin/tree/master/modules/vernemq#vernemq-monitoring-with-netdata)
- [wmi](https://github.com/netdata/go.d.plugin/tree/master/modules/wmi#windows-machine-monitoring-with-netdata)

All they work the same way:

- http request to the `/metrics` endpoint
- parse response
- map these metrics to charts dimensions + additional calculations ([example](https://github.com/netdata/go.d.plugin/blob/master/modules/wmi/collect_cpu.go))

Additional calculations are almost always needed - using raw metrics as is doesnt work in most of the cases, you need to convert them to something meaningful (example - [node_exporter grafana dashboard](https://github.com/rfrail3/grafana-dashboards/blob/master/prometheus/node-exporter-full.json), see `expr`)

---

That is how grafana chart looks like in the GUI:

<img width="1011" alt="Screenshot 2020-06-29 at 14 53 23" src="https://user-images.githubusercontent.com/22274335/86001925-4a7e6400-ba18-11ea-906b-d43a57b7c549.png">

Basically it is set of _Metrics_:
- query
- legend
- some other options

---

There is no doubt this approach works - it expects a user knows [`PromQL`](https://prometheus.io/docs/prometheus/latest/querying/basics/) and have some expirence with an application (to build appropriate queries).


I think to make `Generic Prometheus Collector` really _Generic_ we need to follow same way:

- use `PromQL` for queris
- use some simple chart template language for charts creation


---

The collector workflow:

- load chart templates from the configuration file
- scrape the endpoint (after this step we have like mini prometheus database - current scrape)
- execute queries, create charts, etc...

Written above required a configuration (queries, charts). We think that we need some `auto` mode where a user need to provide only an endpoint address, it would be nice to have some algorith to visualize metrics w/o explicit configuration - ofc it is far from meaningful, it doesnt allow to apply health checks but sounds like a better then nothing. At the moment it is just an idea.

---

We tend to use `PromQL` in this collector because:
- we deal with prometheus metrics
- users know its syntax
- it works, it is not complex compared to SQL for example
- it is very unlikely we can offer something better and it is better to use something solid from the beginning

**Comment by ilyam8** [comment]
We are thinking about configuration file for the collector (chart templates).

These are some points from me:

- format should be YAML
- should be explicit and clear


It is clear that using `PromQL` in configuration file in the config is error-prone so we need to avoid any other uncertainty/complexity to the config, it is clear that having a lot of chart templates == big config, but saving some lines shouldnt be our main goal.

One of the things i like in python is [PEP 20 -- The Zen of Python](https://www.python.org/dev/peps/pep-0020/) statement:

> Explicit is better than implicit.

There is an example what it means for me:

```yml
name: <name>
units: <units>
family: <family>
```

is better then

```yml
definition: <name> <units> <family>
```

2nd example is coupled with order, it is very easy to make a mistake in that order, you need constanly to check documentation what is the order, it is to change something (the only way to change something is to keep appending things).

Basically several distinct options > `a_b_c`. To make it less verbose it is better to provide some default whenever we can and **make them optional**.

**Comment by KlavsKlavsen** [comment]
Just an idea. Should one perhaps support the relabel syntax from prometheus? possibly even simply using its collector code (if it can be used seperately - I'd expect it would be a lib) ? Then its something prometheus users know already ? I scrape from netdata in the end, so I might as well relabel there..

**Comment by ilyam8** [comment]
@KlavsKlavsen we are gonna use promethes query enging. I see there is `label_replace()` function, it think that is what you are saying.

So anything possible to do using `PromQL` is possible (ofc there are some restriction - we can functions that expectes instant vectors, scalars only, because we have not tsdb, we have only last crape metrics database).

**Comment by KlavsKlavsen** [comment]
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config was the one I was thinking of.

**Comment by amoss** [comment]
> Explicit is better than implicit.

I don't think it is that straight-forward. Terse is more useful than verbose. If every detail is listed in the configuration file then it becomes large and unwieldy. This means that the important details are buried among the noise. We need to find a reasonable balance that promotes usability.

We need to see some outlines / sketches of config for different use-cases (as we discussed). I would like to see examples where:
1. The input and output are about the same size, i.e. a simple case where the PQL data-model maps onto the Netdata chart/dimension structure without many changes.
2. A case where the output is much smaller, i.e. we are filtering the input Prometheus data down to something smaller and simpler.
3. A case where the output is much larger than then config, i.e. we are using templating to dynamically set the Netdata structure from parts of the data that we see input in the Prometheus format.

**Comment by ilyam8** [comment]
@KlavsKlavsen netdata metrics in fact have no labels, there is nothing to relabel. However we treat adding labels as one of the most important features we need to add.

**Comment by ilyam8** [comment]
Lets take `wmi` collector [charts](https://github.com/netdata/go.d.plugin/tree/master/modules/wmi#charts) as an example (metrics from [windows_exporter](https://github.com/prometheus-community/windows_exporter#windows_exporter)).

## CPU

- `windows_cpu_cstate_seconds_total`
- `windows_cpu_dpcs_total`
- `windows_cpu_interrupts_total`
- `windows_cpu_time_total`

```cmd
# HELP windows_cpu_cstate_seconds_total Time spent in low-power idle state
# TYPE windows_cpu_cstate_seconds_total counter
windows_cpu_cstate_seconds_total{core="0,0",state="c1"} 28905.096248399997
windows_cpu_cstate_seconds_total{core="0,0",state="c2"} 0
windows_cpu_cstate_seconds_total{core="0,0",state="c3"} 0
windows_cpu_cstate_seconds_total{core="0,1",state="c1"} 29243.3328989
windows_cpu_cstate_seconds_total{core="0,1",state="c2"} 0
windows_cpu_cstate_seconds_total{core="0,1",state="c3"} 0
windows_cpu_cstate_seconds_total{core="0,2",state="c1"} 29914.2833381
windows_cpu_cstate_seconds_total{core="0,2",state="c2"} 0
windows_cpu_cstate_seconds_total{core="0,2",state="c3"} 0
windows_cpu_cstate_seconds_total{core="0,3",state="c1"} 29465.377036899998
windows_cpu_cstate_seconds_total{core="0,3",state="c2"} 0
windows_cpu_cstate_seconds_total{core="0,3",state="c3"} 0

# HELP windows_cpu_dpcs_total Total number of received and serviced deferred procedure calls (DPCs)
# TYPE windows_cpu_dpcs_total counter
windows_cpu_dpcs_total{core="0,0"} 305034
windows_cpu_dpcs_total{core="0,1"} 170434
windows_cpu_dpcs_total{core="0,2"} 162396
windows_cpu_dpcs_total{core="0,3"} 213509

# HELP windows_cpu_interrupts_total Total number of received and serviced hardware interrupts
# TYPE windows_cpu_interrupts_total counter
windows_cpu_interrupts_total{core="0,0"} 5.9163056e+07
windows_cpu_interrupts_total{core="0,1"} 1.0966489e+07
windows_cpu_interrupts_total{core="0,2"} 1.1142989e+07
windows_cpu_interrupts_total{core="0,3"} 1.0967361e+07

# HELP windows_cpu_time_total Time that processor spent in different modes (idle, user, system, ...)
# TYPE windows_cpu_time_total counter
windows_cpu_time_total{core="0,0",mode="dpc"} 3.828125
windows_cpu_time_total{core="0,0",mode="idle"} 28535.546875
windows_cpu_time_total{core="0,0",mode="interrupt"} 22.734375
windows_cpu_time_total{core="0,0",mode="privileged"} 2113.09375
windows_cpu_time_total{core="0,0",mode="user"} 860.296875
windows_cpu_time_total{core="0,1",mode="dpc"} 1.5625
windows_cpu_time_total{core="0,1",mode="idle"} 29413.609375
windows_cpu_time_total{core="0,1",mode="interrupt"} 12.171875
windows_cpu_time_total{core="0,1",mode="privileged"} 943.984375
windows_cpu_time_total{core="0,1",mode="user"} 1151.109375
windows_cpu_time_total{core="0,2",mode="dpc"} 3.328125
windows_cpu_time_total{core="0,2",mode="idle"} 29943.328125
windows_cpu_time_total{core="0,2",mode="interrupt"} 16.84375
windows_cpu_time_total{core="0,2",mode="privileged"} 634.875
windows_cpu_time_total{core="0,2",mode="user"} 930.5
windows_cpu_time_total{core="0,3",mode="dpc"} 49.390625
windows_cpu_time_total{core="0,3",mode="idle"} 29285.5
windows_cpu_time_total{core="0,3",mode="interrupt"} 31.078125
windows_cpu_time_total{core="0,3",mode="privileged"} 1082.90625
windows_cpu_time_total{core="0,3",mode="user"} 1140.296875
```

---

Charts to get

- per core charts (separate set of chart per core) (metrics: `windows_cpu_cstate_seconds_total`, `windows_cpu_time_total`)

```go
	cpuCoreUtilChart = Chart{
		ID:       "core_%s_cpu_utilization",
		Title:    "Core%s CPU Utilization",
		Units:    "percentage",
		Fam:      "cpu",
		Ctx:      "wmi.cpu_utilization",
		Type:     module.Stacked,
		Priority: prioCPUCoreUtil,
		Dims: Dims{
			{ID: "cpu_core_%s_idle", Name: "idle", Algo: module.PercentOfIncremental, Div: 1000, DimOpts: Opts{Hidden: true}},
			{ID: "cpu_core_%s_dpc", Name: "dpc", Algo: module.PercentOfIncremental, Div: 1000},
			{ID: "cpu_core_%s_user", Name: "user", Algo: module.PercentOfIncremental, Div: 1000},
			{ID: "cpu_core_%s_privileged", Name: "privileged", Algo: module.PercentOfIncremental, Div: 1000},
			{ID: "cpu_core_%s_interrupt", Name: "interrupt", Algo: module.PercentOfIncremental, Div: 1000},
		},
	}
	cpuCoreCStateChart = Chart{
		ID:       "core_%s_cpu_cstate",
		Title:    "Core%s Time Spent in Low-Power Idle State",
		Units:    "percentage",
		Fam:      "cpu",
		Ctx:      "wmi.cpu_cstate",
		Type:     module.Stacked,
		Priority: prioCPUCoreCState,
		Dims: Dims{
			{ID: "cpu_core_%s_c1", Name: "c1", Algo: module.PercentOfIncremental, Div: 1000},
			{ID: "cpu_core_%s_c2", Name: "c2", Algo: module.PercentOfIncremental, Div: 1000},
			{ID: "cpu_core_%s_c3", Name: "c3", Algo: module.PercentOfIncremental, Div: 1000},
		},
	}
```

- separate dimension per core (metrics: `windows_cpu_dpcs_total`, `windows_cpu_interrupts_total`)

```go
	cpuDPCsChart = Chart{
		ID:       "cpu_dpcs",
		Title:    "Received and Serviced Deferred Procedure Calls (DPC)",
		Units:    "dpc/s",
		Fam:      "cpu",
		Ctx:      "wmi.cpu_dpcs",
		Type:     module.Stacked,
		Priority: prioCPUDPCs,
	}
	cpuInterruptsChart = Chart{
		ID:       "cpu_interrupts",
		Title:    "Received and Serviced Hardware Interrupts",
		Units:    "interrupts/s",
		Fam:      "cpu",
		Ctx:      "wmi.cpu_interrupts",
		Type:     module.Stacked,
		Priority: prioCPUInterrupts,
	}
```

- summary chart (metrics: `windows_cpu_time_total`)

```go
	cpuUtilChart = Chart{
		ID:       "cpu_utilization_total",
		Title:    "Total CPU Utilization (all cores)",
		Units:    "percentage",
		Fam:      "cpu",
		Ctx:      "wmi.cpu_utilization_total",
		Type:     module.Stacked,
		Priority: prioCPUUtil,
		Dims: Dims{
			{ID: "cpu_idle", Name: "idle", Algo: module.PercentOfIncremental, Div: 1000, DimOpts: Opts{Hidden: true}},
			{ID: "cpu_dpc", Name: "dpc", Algo: module.PercentOfIncremental, Div: 1000},
			{ID: "cpu_user", Name: "user", Algo: module.PercentOfIncremental, Div: 1000},
			{ID: "cpu_privileged", Name: "privileged", Algo: module.PercentOfIncremental, Div: 1000},
			{ID: "cpu_interrupt", Name: "interrupt", Algo: module.PercentOfIncremental, Div: 1000},
		},
	}
```

**Comment by ilyam8** [comment]
# Network

metrics:

- `windows_net_bytes_received_total`
- `windows_net_bytes_sent_total`
- `windows_net_bytes_total`
- `windows_net_packets_outbound_discarded`
- `windows_net_packets_outbound_errors`
- `windows_net_packets_received_discarded`
- `windows_net_packets_received_errors`
- `windows_net_packets_received_total`
- `windows_net_packets_received_unknown`
- `windows_net_packets_total`
- `windows_net_packets_sent_total`
- `windows_net_current_bandwidth`

```cmd
# HELP windows_net_bytes_received_total (Network.BytesReceivedPerSec)
# TYPE windows_net_bytes_received_total counter
windows_net_bytes_received_total{nic="Intel_R__PRO_1000_MT_Desktop_Adapter"} 4.5418e+06
windows_net_bytes_received_total{nic="Intel_R__PRO_1000_MT_Desktop_Adapter__2"} 1.0661733e+07

# HELP windows_net_bytes_sent_total (Network.BytesSentPerSec)
# TYPE windows_net_bytes_sent_total counter
windows_net_bytes_sent_total{nic="Intel_R__PRO_1000_MT_Desktop_Adapter"} 1.780848e+06
windows_net_bytes_sent_total{nic="Intel_R__PRO_1000_MT_Desktop_Adapter__2"} 1.86479806e+08

# HELP windows_net_bytes_total (Network.BytesTotalPerSec)
# TYPE windows_net_bytes_total counter
windows_net_bytes_total{nic="Intel_R__PRO_1000_MT_Desktop_Adapter"} 6.322648e+06
windows_net_bytes_total{nic="Intel_R__PRO_1000_MT_Desktop_Adapter__2"} 1.97141539e+08

# HELP windows_net_packets_outbound_discarded (Network.PacketsOutboundDiscarded)
# TYPE windows_net_packets_outbound_discarded counter
windows_net_packets_outbound_discarded{nic="Intel_R__PRO_1000_MT_Desktop_Adapter"} 0
windows_net_packets_outbound_discarded{nic="Intel_R__PRO_1000_MT_Desktop_Adapter__2"} 0

...

# HELP windows_net_current_bandwidth (Network.CurrentBandwidth)
# TYPE windows_net_current_bandwidth gauge
windows_net_current_bandwidth{nic="Intel_R__PRO_1000_MT_Desktop_Adapter"} 1e+09
windows_net_current_bandwidth{nic="Intel_R__PRO_1000_MT_Desktop_Adapter__2"} 1e+09
```

Charts. In this case we need different metrics grouped by label in one chart.

```go
	nicBandwidthChart = Chart{
		ID:       "nic_%s_bandwidth",
		Title:    "Bandwidth %s",
		Units:    "kilobits/s",
		Fam:      "net",
		Ctx:      "wmi.net_bandwidth",
		Type:     module.Area,
		Priority: prioNICBandwidth,
		Dims: Dims{
			{ID: "net_%s_bytes_received", Name: "received", Algo: module.Incremental, Div: 1000 * 125},
			{ID: "net_%s_bytes_sent", Name: "sent", Algo: module.Incremental, Div: -1000 * 125},
		},
		Vars: Vars{
			{ID: "net_%s_current_bandwidth"},
		},
	}
	nicPacketsChart = Chart{
		ID:       "nic_%s_packets",
		Title:    "Packets %s",
		Units:    "packets/s",
		Fam:      "net",
		Ctx:      "wmi.net_packets",
		Type:     module.Area,
		Priority: prioNICPackets,
		Dims: Dims{
			{ID: "net_%s_packets_received_total", Name: "received", Algo: module.Incremental, Div: 1000},
			{ID: "net_%s_packets_sent_total", Name: "sent", Algo: module.Incremental, Div: -1000},
		},
	}
	nicErrorsChart = Chart{
		ID:       "nic_%s_errors",
		Title:    "Errors %s",
		Units:    "errors/s",
		Fam:      "net",
		Ctx:      "wmi.net_errors",
		Type:     module.Area,
		Priority: prioNICErrors,
		Dims: Dims{
			{ID: "net_%s_packets_received_errors", Name: "inbound", Algo: module.Incremental, Div: 1000},
			{ID: "net_%s_packets_outbound_errors", Name: "outbound", Algo: module.Incremental, Div: -1000},
		},
	}
	nicDiscardsChart = Chart{
		ID:       "nic_%s_discarded",
		Title:    "Discards %s",
		Units:    "discards/s",
		Fam:      "net",
		Ctx:      "wmi.net_discarded",
		Type:     module.Area,
		Priority: prioNICDiscards,
		Dims: Dims{
			{ID: "net_%s_packets_received_discarded", Name: "inbound", Algo: module.Incremental, Div: 1000},
			{ID: "net_%s_packets_outbound_discarded", Name: "outbound", Algo: module.Incremental, Div: -1000},
		},
	}
```

**Comment by amoss** [comment]
Starting to fill out some of the details, the `%s` needs to be specified - i.e. what value is used to fill it. Here is an idea for the cpu core chart based on your example above. There are some issues with it, e.g. what to do if the value of the `core` label contains characters that are reserved for a field such as the `id` below.

```
chart:
  source: windows_cpu_time_total
  for-each:
    index: core
    chart:
      title: Core {core} CPU Utilization
      id: core_{core}_cpu_utilization        # Possible problem with reserved characters
      units: percentage
      family: cpu
      context: wmi.cpu_utilization
      dimensions:
        id: cpu_core_{core}_{mode}
        name: {mode}
        algorithm: percent of incremental
        divisor: 1000
      dimension:                            # i.e. this is a special case to override above
        cpu_core_{core}_idle:
          options:
            hidden: true
```

Also I'm not sure about the placement of the `for-each` - whether or not it leads to a clear structure that is easy to write or if we should move things around for clarity. This doesn't include lifting out individual pieces using regexs.

**Comment by amoss** [comment]
The c_state charts look much more difficult - I think there is a bug in your description :) In the cpu utilization example you had idle as a hidden dimension so that the normalization onto a percentage would work properly. In the c_state chart there is no count of the number of second not in one of the three c_states, so it is the percentage of the sleep time in each c_state, not the percentage of total time spent in the c_state.

**Comment by amoss** [comment]
The summary chart for the cpu is an interesting case, I'm not sure about the PQL syntax but something like this?

```
chart:
	title: Total CPU Utilization
	id: cpu_utilization_total
	units: percentage
	family: cpu
	context: wmi.cpu_utilization
        type: stacked
	dimension:
          id: idle
          expr: sum by core (windows_cpu_time_total{mode="idle"}
	  divisor: 1000
          option: hidden
	dimension:
          id: dpc
          expr: sum by core (windows_cpu_time_total{mode="dpc"}
	  divisor: 1000
	dimension:
          id: user
          expr: sum by core (windows_cpu_time_total{mode="user"}
	  divisor: 1000
	dimension:
          id: privileged
          expr: sum by core (windows_cpu_time_total{mode="privileged"}
	  divisor: 1000
	dimension:
          id: interrupt
          expr: sum by core (windows_cpu_time_total{mode="interrupt"}
	  divisor: 1000
```

It would be nice to wrap up those separate dimensions into a single expression that we template from...

**Comment by ilyam8** [comment]
summary is just `sum by (mode) windows_cpu_time_total`

**Comment by amoss** [comment]
How does the result of the query map onto chart dimensions?

**Comment by ilyam8** [comment]
result is always [`Instant vector`](https://prometheus.io/docs/prometheus/latest/querying/basics/#expression-language-data-types) (or scalar, but lets dont take into account it for now)

> Instant vector - a set of time series containing a single sample for each time series, all sharing the same timestamp


so it would be

```
{mode="dpc"} 3.828125
{mode="idle"} 28535.546875
{mode="interrupt"} 22.734375
{mode="privileged"} 2113.09375
{mode="user"} 860.296875
```

each mode is a dimension - summary chart.

**Comment by amoss** [comment]
In the earlier example the outside `chart` should really be `template` and the `source` would make more sense as `source expr`, so? ...

```
template:
  source expr: sum by (mode) (windows_cpu_time_total)
  for-each:
    index: mode
    chart:
	title: Total CPU Utilization
	id: cpu_utilization_total
	units: percentage
	family: cpu
	context: wmi.cpu_utilization
        type: stacked
      dimensions:
        id: {mode}
        name: {mode}
        algorithm: percent of incremental
        divisor: 1000
      dimension:                            # i.e. this is a special case to override above
        idle:
          options:
            hidden: true
```

**Comment by amoss** [comment]
This would be templating the dimensions in a single chart:
```
template:
  source expr: sum by (mode) (windows_cpu_time_total)
  chart:
    title: Total CPU Utilization
    id: cpu_utilization_total
    units: percentage
    family: cpu
    context: wmi.cpu_utilization
    type: stacked
  for-each:
    index: mode
    dimension:
        id: {mode}
        name: {mode}
        algorithm: percent of incremental
        divisor: 1000
  dimension:                            # i.e. this is a special case to override above
    idle:
     options:
       hidden: true

**Comment by ilyam8** [comment]
# CPU 

My main idea - you need to read configuration like English text and it should be understandable.

I think we can add defaults for some parameters (like title, charttype, dimalgorithm, etc...).

## Per Core Charts

**Used metrics**:
 - `windows_cpu_cstate_seconds_total`
 - `windows_cpu_cstate_seconds_total`

<details>
<summary>Metrics</summary>

```cmd
# HELP windows_cpu_cstate_seconds_total Time spent in low-power idle state
# TYPE windows_cpu_cstate_seconds_total counter
windows_cpu_cstate_seconds_total{core="0,0",state="c1"} 28905.096248399997
windows_cpu_cstate_seconds_total{core="0,0",state="c2"} 0
windows_cpu_cstate_seconds_total{core="0,0",state="c3"} 0
windows_cpu_cstate_seconds_total{core="0,1",state="c1"} 29243.3328989
windows_cpu_cstate_seconds_total{core="0,1",state="c2"} 0
windows_cpu_cstate_seconds_total{core="0,1",state="c3"} 0
windows_cpu_cstate_seconds_total{core="0,2",state="c1"} 29914.2833381
windows_cpu_cstate_seconds_total{core="0,2",state="c2"} 0
windows_cpu_cstate_seconds_total{core="0,2",state="c3"} 0
windows_cpu_cstate_seconds_total{core="0,3",state="c1"} 29465.377036899998
windows_cpu_cstate_seconds_total{core="0,3",state="c2"} 0
windows_cpu_cstate_seconds_total{core="0,3",state="c3"} 0

# HELP windows_cpu_time_total Time that processor spent in different modes (idle, user, system, ...)
# TYPE windows_cpu_time_total counter
windows_cpu_time_total{core="0,0",mode="dpc"} 3.828125
windows_cpu_time_total{core="0,0",mode="idle"} 28535.546875
windows_cpu_time_total{core="0,0",mode="interrupt"} 22.734375
windows_cpu_time_total{core="0,0",mode="privileged"} 2113.09375
windows_cpu_time_total{core="0,0",mode="user"} 860.296875
windows_cpu_time_total{core="0,1",mode="dpc"} 1.5625
windows_cpu_time_total{core="0,1",mode="idle"} 29413.609375
windows_cpu_time_total{core="0,1",mode="interrupt"} 12.171875
windows_cpu_time_total{core="0,1",mode="privileged"} 943.984375
windows_cpu_time_total{core="0,1",mode="user"} 1151.109375
windows_cpu_time_total{core="0,2",mode="dpc"} 3.328125
windows_cpu_time_total{core="0,2",mode="idle"} 29943.328125
windows_cpu_time_total{core="0,2",mode="interrupt"} 16.84375
windows_cpu_time_total{core="0,2",mode="privileged"} 634.875
windows_cpu_time_total{core="0,2",mode="user"} 930.5
windows_cpu_time_total{core="0,3",mode="dpc"} 49.390625
windows_cpu_time_total{core="0,3",mode="idle"} 29285.5
windows_cpu_time_total{core="0,3",mode="interrupt"} 31.078125
windows_cpu_time_total{core="0,3",mode="privileged"} 1082.90625
windows_cpu_time_total{core="0,3",mode="user"} 1140.296875
```

</details>


**Configuration**:

```yaml
- id: "core_{{core}}_cpu_utilization"
  title: "Core{{core}} CPU Utilization"
  units: "percentage"
  family: "cpu"
  context: "wmi.cpu_utilization"
  type: "stacked"
  dimensions:
    - expr: 'windows_cpu_time_total{mode!="idle"}'
      id: "cpu_core_{{core}}_{{mode}}"
      name: "{{mode}}"
      algorithm: "%incremental"
    - expr: 'windows_cpu_time_total{mode="idle"}'
      id: "cpu_core_{{core}}_{{mode}}"
      name: "{{mode}}"
      algorithm: "%incremental"
      hidden: yes

- id: "core_{{core}}_cpu_state"
  title: "Core{{core}} Time Spent in Low-Power Idle State"
  units: "percentage"
  family: "cpu"
  context: "wmi.cpu_cstate"
  type: "stacked"
  dimensions:
    - expr: "windows_cpu_cstate_seconds_total"
      id: "cpu_core_{{core}}_{{state}}"
      name: "{{state}}"
      algorithm: "%incremental"
```

## Per Core Dimensions 

**Used metrics**:
- `windows_cpu_dpcs_total`
- `windows_cpu_interrupts_total`


<details>
<summary>Metrics</summary>

```cmd
# HELP windows_cpu_dpcs_total Total number of received and serviced deferred procedure calls (DPCs)
# TYPE windows_cpu_dpcs_total counter
windows_cpu_dpcs_total{core="0,0"} 305034
windows_cpu_dpcs_total{core="0,1"} 170434
windows_cpu_dpcs_total{core="0,2"} 162396
windows_cpu_dpcs_total{core="0,3"} 213509

# HELP windows_cpu_interrupts_total Total number of received and serviced hardware interrupts
# TYPE windows_cpu_interrupts_total counter
windows_cpu_interrupts_total{core="0,0"} 5.9163056e+07
windows_cpu_interrupts_total{core="0,1"} 1.0966489e+07
windows_cpu_interrupts_total{core="0,2"} 1.1142989e+07
windows_cpu_interrupts_total{core="0,3"} 1.0967361e+07
```

</details>

**Configuration**:

```yaml
- id: "cpu_dpcs"
  title: "Received and Serviced Deferred Procedure Calls (DPC)"
  units: "dpc/s"
  family: "cpu"
  context: "wmi.cpu_dpcs"
  type: "stacked"
  dimensions:
    - expr: "windows_cpu_dpcs_total"
      id: "cpu_core_{{core}}_dpcs"
      name: "core_{{core}}"
      algorithm: "incremental"

- id: "cpu_interrupts"
  title: "Received and Serviced Hardware Interrupts"
  units: "interrupts/s"
  family: "cpu"
  context: "wmi.cpu_interrupts"
  type: "stacked"
  dimensions:
    - expr: "windows_cpu_interrupts_total"
      id: "cpu_core_{{core}}_interrupts"
      name: "core_{{core}}"
      algorithm: "incremental"
```

## Summary

Used metrics:
- `windows_cpu_time_total`

<details>
<summary>Metrics</summary>

```cmd
# HELP windows_cpu_time_total Time that processor spent in different modes (idle, user, system, ...)
# TYPE windows_cpu_time_total counter
windows_cpu_time_total{core="0,0",mode="dpc"} 3.828125
windows_cpu_time_total{core="0,0",mode="idle"} 28535.546875
windows_cpu_time_total{core="0,0",mode="interrupt"} 22.734375
windows_cpu_time_total{core="0,0",mode="privileged"} 2113.09375
windows_cpu_time_total{core="0,0",mode="user"} 860.296875
windows_cpu_time_total{core="0,1",mode="dpc"} 1.5625
windows_cpu_time_total{core="0,1",mode="idle"} 29413.609375
windows_cpu_time_total{core="0,1",mode="interrupt"} 12.171875
windows_cpu_time_total{core="0,1",mode="privileged"} 943.984375
windows_cpu_time_total{core="0,1",mode="user"} 1151.109375
windows_cpu_time_total{core="0,2",mode="dpc"} 3.328125
windows_cpu_time_total{core="0,2",mode="idle"} 29943.328125
windows_cpu_time_total{core="0,2",mode="interrupt"} 16.84375
windows_cpu_time_total{core="0,2",mode="privileged"} 634.875
windows_cpu_time_total{core="0,2",mode="user"} 930.5
windows_cpu_time_total{core="0,3",mode="dpc"} 49.390625
windows_cpu_time_total{core="0,3",mode="idle"} 29285.5
windows_cpu_time_total{core="0,3",mode="interrupt"} 31.078125
windows_cpu_time_total{core="0,3",mode="privileged"} 1082.90625
windows_cpu_time_total{core="0,3",mode="user"} 1140.296875
```

</details>

**Configuration**:

```yaml
- id: "cpu_utilization_total"
  title: "Total CPU Utilization (all cores)"
  units: "percentage"
  family: "cpu"
  context: "wmi.cpu_utilization_total"
  type: "stacked"
  dimensions:
    - expr: 'sum by (mode) (windows_cpu_time_total{mode!="idle"})'
      id: "cpu_{{mode}}"
      name: "{{mode}}"
      algorithm: "%incremental"
    - expr: 'sum by (mode) (windows_cpu_time_total{mode="idle"})'
      id: "cpu_{{mode}}"
      name: "{{mode}}"
      algorithm: "%incremental"
      hidden: yes
```

**Comment by ilyam8** [comment]
# Network

## Received/Sent bytes && NIC Bandwidth

Metrics:
- `windows_net_bytes_received_total`
- `windows_net_bytes_sent_total`
- `windows_net_current_bandwidth`

<details>
<summary>Metrics</summary>

```cmd
# HELP windows_net_bytes_received_total (Network.BytesReceivedPerSec)
# TYPE windows_net_bytes_received_total counter
windows_net_bytes_received_total{nic="Intel_R__PRO_1000_MT_Desktop_Adapter"} 4.5418e+06
windows_net_bytes_received_total{nic="Intel_R__PRO_1000_MT_Desktop_Adapter__2"} 1.0661733e+07

# HELP windows_net_bytes_sent_total (Network.BytesSentPerSec)
# TYPE windows_net_bytes_sent_total counter
windows_net_bytes_sent_total{nic="Intel_R__PRO_1000_MT_Desktop_Adapter"} 1.780848e+06
windows_net_bytes_sent_total{nic="Intel_R__PRO_1000_MT_Desktop_Adapter__2"} 1.86479806e+08

# HELP windows_net_current_bandwidth (Network.CurrentBandwidth)
# TYPE windows_net_current_bandwidth gauge
windows_net_current_bandwidth{nic="Intel_R__PRO_1000_MT_Desktop_Adapter"} 1e+09
windows_net_current_bandwidth{nic="Intel_R__PRO_1000_MT_Desktop_Adapter__2"} 1e+09
```

</details>

**Configuration**:

```yaml
- id: "nic_{{nic}}_bandwidth"
  title: "Bandwidth {{nic}}"
  units: "kilobits/s"
  family: "net"
  context: "wmi.net_bandwidth"
  type: "area"
  dimensions:
    - expr: 'windows_net_bytes_received_total'
      id: "net_{{nic}}_received"
      name: "received"
      algorithm: "incremental"
    - expr: 'windows_net_bytes_sent_total'
      id: "net_{{nic}}_sent"
      name: "sent"
      algorithm: "incremental"
  variables:
    - expr: 'windows_net_current_bandwidth'
      id: "net_{{nic}}_current_bandwidth"
```

All other network charts have ~same configuration, i am not gonna add them.

**Comment by amoss** [comment]
> My main idea - you need to read configuration like English text and it should be understandable.

Ah, just like COBOL or Java :) I think we should aim for simple and understandable. There is a strange trade-off in how verbose we make the language.

* When everything is explicit it looks simpler in small cases - because we see everything.
* When a lot of information is implicit it looks more complex in small cases - because we have to know / infer parts.

When the cases become larger it flips around:
* When everything is explicit is looks far more complex - 1000s of lines of noise to find the few important lines of signal.
* When a lot of information is implicit is looks simpler - we are focusing on the important parts.

We only know how it behaves and which is the more important criteria by trying it out on more examples.

**Comment by amoss** [comment]
```
- id: "nic_{{nic}}_bandwidth"
  title: "Bandwidth {{nic}}"
  units: "kilobits/s"
  family: "net"
  context: "wmi.net_bandwidth"
  type: "area"
  dimensions:
    - expr: 'windows_net_bytes_received_total'
      id: "net_{{nic}}_received"
      name: "received"
      algorithm: "incremental"
    - expr: 'windows_net_bytes_sent_total'
      id: "net_{{nic}}_sent"
      name: "sent"
      algorithm: "incremental"
  variables:
    - expr: 'windows_net_current_bandwidth'
      id: "net_{{nic}}_current_bandwidth"
```

It is not clear what this is - chart / template etc. We have to infer it from the `{{nic}}` inside some of the fields. This means that the value of the `id` field changes the meaning of the keys higher up in the tree - this could be confusing for users and more difficult to implement.

I think it is simpler to have some kind of keyword earlier that specifies that it is a template,  and some way of explicitly indexing the fields that generates each chart.
