### ISSUE TITLE
service discovery: k8s discovery design and poc

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#8648]
##### Feature idea summary

Outcome of #5729

> Design k8s collector endpoint autodiscovery
> We need to have a way for our collectors to discover automatically the ephemeral endpoints in a k8s cluster.

This will be a service discovery k8s module. The only way to get data in k8s is to get it from the API server.

It will be installed in a pod with netdata-slave.

##### Expected behavior

To have k8s service discovery working, it should be able to find known applications and create jobs. Plugins wont be able to consume these jobs, will be implemented later.

**Comment by ilyam8** [comment]
Desing will be added soon.

**Comment by ilyam8** [comment]
Before i started to work on it an important thing to keep in mind was:

Discovery sources can be any. K8s is only one of them.

Service auto-discovery in general:
- gather data **from different sources**
- identify application(s) from the data
- convert data to the **appropriate plugin(s)/module(s)** configuration files
- export these configuration files to the **appropriate destination**

No Go in my opinion:
- be coupled with a specific source (ex.: k8s)
- be coupled with a specific configuration file consumer (ex.: go.d)
- have hard coded identification logic
- have any hard coded business logic

Go in my opinion:
- all specific logic should be outside of service auto-discovery code
- all specific logic should be in the service auto-discovery configuration file
- a user should be able to tune it for his need (what to collect, how to identify, configuration format, where to export configuration)

Who is a user: first of all we are the user. **We provide default discovery configuration.**


Generic flow:
- gather data from **user defined sources** =>
- identify plugin(s)/module(s) **based on user defined conditions** =>
- find appropriate **user defined template(s) based on user defined conditions** =>
- create configuration(s) from these template(s)
- find appropriate **user defined destination(s)** for the configuration(s) **based on user defined conditions** =>
- export these configurations to the appropriate destination(s) **based on user defined conditions** 

___

My proposal is _4 steps service auto-discovery pipeline_:
- **discovering**: contains any number of source specific discovers. Here we **discover and tag targets**. (tag is just a string).
- **tagging**: contains any number of tagging chains. Here we **tag the targets** based on matches.
- **building**: contains any number of tagging chains. Here we **create configurations and tag them**.
- **exporting**: contains any number of exporting chains. Here we **export configuration** (ex.: write to a file(s)).

Routing inside a chain and between them is based on tags. Every step has selectors.

Matches format: go template.
Configuration template format: go template.

___

k8s discoverer have several roles. They are same as prometheus have:
> https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config

Every role provides set attributes which accesible in tagging (match target) and building (create config from template).

For example for k8s pod role we have

```go
	podTarget struct {
		ID      string
		Address string

		Namespace   string
		Name        string
		Annotations map[string]string
		Labels      map[string]string
		NodeName    string
		PodIP       string

		ContName     string
		Image        string
		Env          map[string]string
		PortNumber   string
		PortName     string
		PortProtocol string
	}

```

___

Example of pipeline configuration:

```yaml
name: k8s
discovering:
  k8s:
    - tags: module=undefined
      role: pod

# => target: {module=undefined}

tagging:
  - selector: module=undefined
    tags: -module=undefined plugin=go.d
    match:
      - cond: '{{and (eqAny .PortNumber "80,8080") (contains .Image "apache")}}'
        tags: module=apache
      - cond: '{{and (eqAny .PortNumber "80,8080") (contains .Image "nginx")}}'
        tags: module=nginx

# => target: {plugin=go.d module=apache} OR {plugin=go.d module=nginx}

building: # target => config(s)
  - selector: !module=undefined plugin=go.d
    tags: export=file plugin=go.d
    apply:
      - selector: module=apache
        tags: module=apache
        template: |
          - module: apache
            name: apache-{{.ID}}
            url: http://{{.Address}}/server_status?auto
      - selector: module=nginx
        tags: module=nginx
        template: |
          - module: nginx
            name: nginx-{{.ID}}
            url: http://{{.Address}}/stub_status

# => config: {export=file plugin=go.d module=apache} + {export=file plugin=go.d module=nginx}

exporting:
  - selector: export=file
    file:
      - selector: plugin=go.d
        filename: go-sd.conf
        flush: 10


```
