### ISSUE TITLE
Alarms for Postgres multi instances

### ISSUE THREAD

**Issue by EnzoAkira** [netdata/netdata#8670]
##### Question summary
Hi guys!
I put this as a question, but I think it could be a bug, I think!
So, I have this scenario:
* Cluster w/ 3 hosts [server-01;server-02;server-03]
* server-01 w/ Postgres in master | server-02/03 w/ Postgres in replication
* Netdata 1.20 installed on all hosts

My postgres.conf is as follows:

<details>
<summary>postgres.conf</summary>
<p>

```yml
(all commented stuff)
...
cloud1:
 host  : '/nvme_db1/cloud1/9.6/unix_socket'
 user  : 'postgres'

cloud2:
 host  : '/nvme_db1/cloud2/9.5/unix_socket'
 user  : 'postgres'

cloud3:
 host  : '/nvme_db2/cloud3/11/unix_socket'
 user  : 'postgres'

cloud4:
 host  : '/nvme_db2/cloud4/12/unix_socket'
 user  : 'postgres'
...
```

</p>
</details>

In total I have 10 instances/jobs configured on **postgres.conf**

My needs:
I need to be able to detect if an instance/job is down, in a dynamic way (because the instances/jobs are propagated by ansible to each db server).

My test until now:
I research all charts in netdata related to postgres and found that on **Netdata Monitoring** > python.d are this charts [netdata.runtime_postgres_xxxx]. So I try to create an alarm to get run time and if it's 0 or nan (instance crash or terminated) but I'm getting some issues, for now my alarm below.

<details>
<summary>postgres.conf</summary>
<p>

```yml
template: postgres_instance_runtime
on: netdata.pythond_runtime
lookup: average -1s unaligned of run time
units: miliseconds
every: 5s
crit: $this == nan OR $this = 0
delay: up 1s down 5m multiplier 1.2 max 1h
repeat: critical 120s
info: Postgres Instances Run Time
to: sre
```

</p>
</details>  

My problem with this is when I stop replication on _server-03_ (as a test), the graph in **Netdata Monitoring** > python.d freezes and the values do not change until I restart replication. A gap is shown in the graph when I start replicating again, consequently the alarm never triggers.

### OS
All servers run centos-release-7-7
