### ISSUE TITLE
Question about configuration directory in container

### ISSUE THREAD

**Issue by steakhutzeee** [netdata/netdata#8677]
Hello :)

I'm running netdata into a container with this compose file:

```
version: '3'
services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    ports:
      - 19999:19999
    environment:
      - PGID=996
      - DO_NOT_TRACK=1
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
networks:
    default:
      external:
        name: my-net
```

I was trying to understand how to configure notifications to Discord etc. but can't find the configuration files. Maybe i have missed some paths in my compose files?

I have an AppData directory on my drive and i usually point there for the configurations of my containers.
For example for netdata could be /srv/dev-disk-by-label-HC2/AppData/Netdata:/config

Or maybe i can just add some env variables for the services i want to send the alarms to? 
For example:

`-e DISCORD_WEBHOOK_URL=https://discordapp.com/api/webhooks/XXXX -e DISCORD_RECIPIENT=alerts`
Any idea?

Thanks in advance!

**Comment by ilyam8** [comment]
hi @steakhutzeee 

Netdata user configurations is in `/etc/netdata`. You can to put `health_alarm_notify.conf` file in there.

There are several ways to do it, let me give you an example:

 - bind specific file into container

Download:

> wget https://raw.githubusercontent.com/netdata/netdata/master/health/notifications/health_alarm_notify.conf

Bind (see `--mount` option):

```sh
docker run -d --name=netdata \
  -p 19999:19999 \
  -e PGID=995 \
  -e DO_NOT_TRACK=1 \
  -v /etc/passwd:/host/etc/passwd:ro \
  -v /etc/group:/host/etc/group:ro \
  -v /proc:/host/proc:ro \
  -v /sys:/host/sys:ro \
  -v /etc/os-release:/host/etc/os-release:ro \
  -v /var/run/docker.sock:/var/run/docker.sock:ro \
  -v /etc/os-release:/host/etc/os-release:ro \
  --mount type=bind,source=$(pwd)/health_alarm_notify.conf,target=/etc/netdata/health_alarm_notify.conf \
  --cap-add SYS_PTRACE \
  --security-opt apparmor=unconfined \
  --restart unless-stopped \
  netdata/netdata:v1.21.0
```

Configure it from the host sytem, restart netdata container.

___

If you are on linux you can use named volumes (docker server runs natively, not in vm, easy to access volumes from the host system), if there is no volume all dst dir files are copied into it:

```sh
docker run -d --name=netdata \
  -p 19999:19999 \
  -e PGID=995 \
  -e DO_NOT_TRACK=1 \
  -v /etc/passwd:/host/etc/passwd:ro \
  -v /etc/group:/host/etc/group:ro \
  -v /proc:/host/proc:ro \
  -v /sys:/host/sys:ro \
  -v /etc/os-release:/host/etc/os-release:ro \
  -v /var/run/docker.sock:/var/run/docker.sock:ro \
  -v /etc/os-release:/host/etc/os-release:ro \
  --mount source=netdatetc,target=/etc/netdata \
  --mount source=netdatalib,target=/var/lib/netdata \
  --mount source=netdatacache,target=/var/cache/netdata \
  --cap-add SYS_PTRACE \
  --security-opt apparmor=unconfined \
  --restart unless-stopped \
  netdata/netdata:v1.21.0
```

netdata volumes are in `/var/lib/docker/volumes/netdata*`

```sh
[ilyam-pc ~]# wget https://raw.githubusercontent.com/netdata/netdata/master/health/notifications/health_alarm_notify.conf -q -P /var/lib/docker/volumes/netdatetc/_data/
[ilyam-pc ~]# ls -l /var/lib/docker/volumes/netdatetc/_data/
total 88
drwxr-xr-x 2 root root  4096 апр  6 04:32 charts.d
drwx------ 2  201  201  4096 апр  6 04:32 claim.d
drwxr-xr-x 2 root root  4096 апр  6 04:32 custom-plugins.d
-rwxr-xr-x 1 root root  2045 апр  6 04:32 edit-config
drwxr-xr-x 2 root root  4096 апр  6 04:32 go.d
-rw-r--r-- 1 root root 44198 апр 11 02:25 health_alarm_notify.conf
drwxr-xr-x 2 root root  4096 апр  6 04:32 health.d
-rw-r--r-- 1 root root   208 апр  6 04:32 netdata.conf
drwxr-xr-x 2 root root  4096 апр  6 04:32 node.d
lrwxrwxrwx 1 root root    23 апр  6 04:32 orig -> /usr/lib/netdata/conf.d
drwxr-xr-x 2 root root  4096 апр  6 04:32 python.d
drwxr-xr-x 2 root root  4096 апр  6 04:32 ssl
drwxr-xr-x 2 root root  4096 апр  6 04:32 statsd.d
```

**Comment by ilyam8** [comment]
So idea is to mount specific file (`health_alarm_notify.conf`) or dir (`/etc/netdata`), it can be `bind` or `volume`.

My examples are not for docker-compose, but you got the gist 😄 


I would say:
 - `/var/lib/netdata` should be `volume`
 - `/var/cache/netdata` should be `volume`
 - `/etc/netdata` should be `bind` (because you need to change files there manually)

**Comment by steakhutzeee** [comment]
First of all, thanks for your detailed explanation!
I'm new to docker so i'm trying to figure out your suggestions.

Could i just add to my compose these lines?:

```
volumes:
  - /srv/dev-disk-by-label-HC2/AppData/Netdata/etc/netdata:/etc/netdata
  - /srv/dev-disk-by-label-HC2/AppData/Netdata/var/lib/netdata:/var/lib/netdata
  - /srv/dev-disk-by-label-HC2/AppData/Netdata/var/cache/netdata:/var/cache/netdata
```

What should be the differences with the bind mounts, and your configuration? I've never used those in my compose files.

A thing to add is that my docker base path is different from the default one, i've changed the path.

Had a look there and in my docker path: `/srv/dev-disk-by-label-HC2/DockerBasePath/docker/` i only have 1 file, that's `metadata.db`

**Comment by ilyam8** [comment]
[volume](https://docs.docker.com/storage/volumes/) vs bind [mounts](https://docs.docker.com/storage/bind-mounts/)

> Could i just add to my compose these lines?

i think yes, just try.

**Comment by steakhutzeee** [comment]
Tried but had strange errors. So arranged this compose file:

```
version: '3.3'
services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    ports:
      - 19999:19999
    environment:
      - PGID=996
      - DO_NOT_TRACK=1
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - type: volume
        source: lib
        target: /var/lib/netdata
      - type: volume
        source: cache
        target: /var/cache/netdata
      - type: bind
        source: etc
        target: /etc/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
volumes:
  lib:
  cache:
  etc:
networks:
    default:
      external:
        name: my-net
```

When i run it i have this error: `ERROR: for netdata  Cannot create container for service netdata: invalid mount config for type "bind": invalid mount path: 'etc' mount path must be absolute`

if i use volume instead of bind for "etc", the volume is created without issues.

So here i have two questions:

1. How you think i could solve this issue with bind?
2. Maybe a dumb question, I see that the volumes are created inside the volumes dir, so if i want to backup the files i have to do that manually. I can't use a separate dir like i was saying before? An AppData dir, instead of the volumes one.
