### ISSUE TITLE
Found many error logs when using docker for deployment

### ISSUE THREAD

**Issue by FirstJavaMaster** [netdata/netdata#8769]
##### Bug report summary

There are many error logs when installing using docker. However, it seems that the monitoring page can be accessed normally.

![image](https://user-images.githubusercontent.com/22362110/79714650-185bd200-8304-11ea-9a5b-1a95bac55f64.png)

I configured docker-compose according to the official method. Just like this:

```
version: '3'
services:
  netdata:
    image: netdata/netdata
    hostname: "139"
    environment:
      - PGID=991
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
```

It will be the same even if I remove `environment`.

And this is the docker log file.

[e0862d1f69e58a9be92ba244f73c87efbcbddd1a3e3752b40b7c0c20ec5b621e-json.log](https://github.com/netdata/netdata/files/4501228/e0862d1f69e58a9be92ba244f73c87efbcbddd1a3e3752b40b7c0c20ec5b621e-json.log)

##### OS / Environment

```
Linux docker1 3.10.0-1062.1.1.el7.x86_64 #1 SMP Fri Sep 13 22:55:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 7.7.1908 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:HOME_URL="https://www.centos.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.centos.org/"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.7.1908 (Core)
/etc/system-release:CentOS Linux release 7.7.1908 (Core)
```

##### Netdata version

The latest version in docker hub. 2020-04-20.

##### Component Name

It seems to be related to the performance monitoring of docker.

##### Steps To Reproduce

Just start the image according to the docker-compose file.

##### Expected behavior

Are these error logs normal? Are the resources occupied by docker on this machine counted normally?
