### ISSUE TITLE
plugin reload support: go.d.plugin

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#8804]
### Feature idea summary

Go.d plugin should keep track of changes in the configuration file and reload jobs (remove deleted, add new) based on them.

This feature is needed in k8s. Related: #8803

Reload details will be added later.

___

**It basically means**: rewrite [go-orchestrator setup/create/start/runtime logic](https://github.com/ilyam8/go-orchestrator)

##### Expected behavior

Have reload support in go.d plugin

**Comment by ilyam8** [comment]
Current implementation:

- look for specific configuration file in `NETDATA_USER_CONFIG_DIR/go.d`, `NETDATA_STOCK_CONFIG_DIR/go.d` (in that order) directories
- use the first one found
- create jobs (job - a module with specific parameters) from the config file
- start jobs

**We do this only at the start of plugin.**

Config file has `global` and `jobs` sections, example:

```yaml
# [ GLOBAL ]
update_every: 1
autodetection_retry: 0
priority: 70000

# [ JOBS ]
jobs:
  - name: local
    url: http://localhost/server-status?auto

  - name: local
    url: http://127.0.0.1/server-status?auto
```


**There is no information what collector it is**, we use the config filename for identification, for instance for `apache` collector we expect `apache.conf` configuration file.

___


In general we need to add support for:
- loading configuration files during runtime (if there are any changes)
- new configuration file format (in addition to old one)

new config file format

```yaml
  - name: local
    module: apache
    url: http://localhost/server-status?auto

  - name: local
    module: nginx
    url: http://127.0.0.1/stub_status
```

Since it is a one file we use `module` key for collector identification.

___

**Adding reload is a lot of changes to the current read configs/load jobs logic.** 


We need:
- add jobs in runtime
- stop/remove jobs in runtime 
- keep track of jobs sources (filenames)
- keep track of configuration changes

Add/stop/remove jobs is not simple, possible cases:
- **ADD job(s)**

```yaml
  - name: local
    module: apache
    url: http://localhost/server-status?auto
```

=>

```yaml
  - name: local
    module: apache
    url: http://localhost/server-status?auto

  - name: local
    module: nginx
    url: http://127.0.0.1/stub_status
```

- **REMOVE job(s)**

```yaml
  - name: local
    module: apache
    url: http://localhost/server-status?auto
```

=>

```yaml
# nothing
```

- **ADD/REMOVE job(s)**

```yaml
  - name: local
    module: apache
    url: http://localhost/server-status?auto
```

=>

```yaml
  - name: local
    module: nginx
    url: http://127.0.0.1/stub_status
```

---

The hard part is handling changes - distinguish between removed/changed job.
