### ISSUE TITLE
service discovery: k8s sane default config

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#9015]
##### Feature idea summary

Part of #8925

We want to get service discovery working in k8s cluster, it means we need default configuration with predefined identification rules, configuration templates, etc.

<details>
<summary>service discovery example config file</summary>

```yaml
name: k8s
discovering:
  k8s:
    - tags: unknown
      role: pod

tagging:
  - selector: unknown
    tags: -unknown go.d
    match:
      - cond: '{{and (eqAny .PortNumber "80 8080") (glob .Image "*httpd*")}}'
        tags: apache
      - cond: '{{and (eqAny .PortNumber "80 8080") (glob .Image "*nginx*")}}'
        tags: nginx

building:
  - selector: !unknown go.d
    tags: file go.d
    apply:
      - selector: apache
        tags: apache
        template: |
          - module: apache
            name: apache-{{.TUID}}
            url: http://{{.Address}}/server_status?auto
      - selector: nginx
        tags: nginx
        template: |
          - module: nginx
            name: nginx-{{.TUID}}
            url: http://{{.Address}}/stub_status

exporting:
  file:
    - selector: file go.d
      filename: "/opt/output.yml"
```

</details>

---

Mainly we need to :

- add identification rules, current idea is to use port + image name:

```yaml
tagging:
  - selector: unknown
    tags: -unknown go.d
    match:
      - cond: '{{and (eqAny .PortNumber "80 8080") (glob .Image "*httpd*")}}'
        tags: apache
      - cond: '{{and (eqAny .PortNumber "80 8080") (glob .Image "*nginx*")}}'
        tags: nginx
```

- add configuration templates. We gonna add only go.d modules configs.

```yaml
building:
  - selector: !unknown go.d
    tags: file go.d
    apply:
      - selector: apache
        tags: apache
        template: |
          - module: apache
            name: apache-{{.TUID}}
            url: http://{{.Address}}/server_status?auto
      - selector: nginx
        tags: nginx
        template: |
          - module: nginx
            name: nginx-{{.TUID}}
            url: http://{{.Address}}/stub_status
```

___

# TODO
- ask sre guys for access to the k8s cluster or services we are using in the cloud - i need ports + image names
- populate default configs with identification rules, configuration templates

##### Expected behavior

Have sd k8s sane default config that will do in our k8s cluster
