### ISSUE TITLE
CGroup PID not detected when running netdata as a container

### ISSUE THREAD

**Issue by HolgerHees** [netdata/netdata#9037]
Hello,

I'm currently using your latest docker container 1.22.0. 

Mostly everything runs fine except the network interface detection from other docker containers running on the host system.

The netdata container is running with SYS_PTRACE and "apparmor:unconfined" and the directory /sys is mounted as /host/sys readonly.

Inside the container I can see that it was detected as a sysfs

But I get a lot of log messages like

```
cgroup-network-helper.sh: INFO: searching for network interfaces of cgroup '/host/sys/fs/cgroup/cpu,cpuacct/docker/xxx'
/usr/libexec/netdata/plugins.d/cgroup-network ERROR : MAIN : child pid 775 exited with code 1.
/usr/libexec/netdata/plugins.d/cgroup-network ERROR : MAIN : Cannot find a cgroup PID from cgroup '/host/sys/fs/cgroup/cpu,cpuacct/docker/xxx'
```

I checked already the plugin cgroup-network-helper.sh and found out that the file cgroup.procs is processed which is empty inside the container. If I check it outside on the host system it returns a pid.

If I check a different file e.g. cpu.shares inside the container it returns a number, so it looks that it works in general.

best

**Comment by HolgerHees** [comment]
I was able to get it working by "--pid host" together with "--privileged"

but this will give the container nearly unlimited access to the host system.

**Comment by prologic** [comment]
Hello! 👋Please follow the instructions [here}(https://learn.netdata.cloud/docs/agent/packaging/docker) and if you still have problems please let us know! Based on your desc I have a feeling you might be missing some mount points and other required facilities.

**Comment by HolgerHees** [comment]
Hi, I completely followed your documentation.

and my mountpoints are

```
- '/etc/os-release:/host/etc/os-release:ro'
- '/etc/passwd:/host/etc/passwd:ro'
- '/etc/group:/host/etc/group:ro'
- '/proc:/host/proc:ro'
- '/sys:/host/sys:ro'
- '/var/run/docker.sock:/var/run/docker.sock:ro'
```

and if I use "--pid host" together with "--privileged" everything works. So for me it sounds like a permission problem.

I'm deploying it with ansible
```
- name: create docker container
  docker_container:
    name: netdata_test
    image: "netdata/netdata:v{{netdata_version}}"
    state: present
    network_mode: "host"
    env:
      TZ: "{{timezone}}"
      PGID: "473"
      NETDATA_PORT: "29999"
    log_driver: journald
    log_options:
      tag: netdata_test
    capabilities:
      - SYS_PTRACE
    security_opts:
      - "apparmor:unconfined"
    volumes:
      - '{{ global_lib }}netdata_test:/var/lib/netdata:z'
      - '{{ global_lib }}netdata_test/cache:/var/cache/netdata:z'      
      - "{{ global_etc }}netdata/netdata.conf:/etc/netdata/netdata.conf:ro,z"
      - "{{ global_etc }}netdata/python.d.conf:/etc/netdata/python.d.conf:ro,z"
      - "{{ global_etc }}netdata/health_alarm_notify.conf:/etc/netdata/health_alarm_notify.conf:ro,z"
      - "{{ global_etc }}netdata/fping.conf:/etc/netdata/fping.conf:ro,z"
      - "{{ global_etc }}netdata/.environment:/etc/netdata/.environment:ro,z"
      - "{{ global_etc }}netdata/health.d/disks.conf:/etc/netdata/health.d/disks.conf:ro,z"
      - "{{ global_etc }}netdata/health.d/softnet.conf:/etc/netdata/health.d/softnet.conf:ro,z"
      - "{{ global_etc }}netdata/health.d/net.conf:/etc/netdata/health.d/net.conf:ro,z"
      - "{{ global_etc }}netdata/health.d/fping.conf:/etc/netdata/health.d/fping.conf:ro,z"
      - '/etc/os-release:/host/etc/os-release:ro'
      - '/etc/passwd:/host/etc/passwd:ro'
      - '/etc/group:/host/etc/group:ro'
      - '/proc:/host/proc:ro'
      - '/sys:/host/sys:ro'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
```
