### ISSUE TITLE
Netdata docker image creating zombie process

### ISSUE THREAD

**Issue by JonAnder83** [netdata/netdata#9070]
##### Bug report summary

I've noticed netdata causes a process to go zombie on my systems running it from within docker.

##### OS / Environment

```
Linux olisar 5.4.40-1-ARCH #1 SMP PREEMPT Thu May 14 01:48:56 UTC 2020 armv7l GNU/Linux
/etc/os-release:NAME="Arch Linux ARM"
/etc/os-release:PRETTY_NAME="Arch Linux ARM"
/etc/os-release:ID=archarm
/etc/os-release:ID_LIKE=arch
/etc/os-release:BUILD_ID=rolling
/etc/os-release:ANSI_COLOR="38;2;23;147;209"
/etc/os-release:HOME_URL="https://archlinuxarm.org/"
/etc/os-release:DOCUMENTATION_URL="https://archlinuxarm.org/wiki"
/etc/os-release:SUPPORT_URL="https://archlinuxarm.org/forum"
/etc/os-release:BUG_REPORT_URL="https://github.com/archlinuxarm/PKGBUILDs/issues"
/etc/os-release:LOGO=archlinux
```

##### Netdata version

netdata v1.22.1-32-gc35149a3

##### Steps To Reproduce

1. Deploy the image
2. Get netdata to run

Reproduced on 2 different raspberry pi's model 3B+ running same version of arch, same configuration for the docker container and same netdata version.

These commands are run from the OS, not from the container:
```$ ps -el | grep Z
F S   UID   PID  PPID  C PRI  NI ADDR SZ WCHAN  TTY          TIME CMD
1 Z   201  2647   891  0  99  19 -     0 -      ?        00:00:00 timeout <defunct>
$ ps -aux | grep 891
201        891  4.4  8.3 144460 79940 ?        SNsl 10:44   5:28 /usr/sbin/netdata -u netdata -D -s /host -p 19999 -W set web w         
```

##### Expected behavior

Welp, it would be nice not to have zombies lying around :)

**Comment by ilyam8** [comment]
Hi @JonAnder83 

> Deploy the image

This is all, just `docker run ...` and there is zombie process?

This my output (manjaro)

```cmd
[ilyam@ilyam-pc ~]$ ps faxu | grep "[n]etdata"
201        93525  5.5  0.0  49688 27948 ?        SNsl 13:57   0:12  |       \_ /usr/sbin/netdata -u netdata -D -s /host -p 19999 -W set web web files group root -W set web web files owner root
201        93697  0.1  0.0 125700 17128 ?        SNl  13:57   0:00  |           \_ /usr/libexec/netdata/plugins.d/go.d.plugin 1
root       93710  1.4  0.0  55652  3960 ?        SN   13:57   0:03  |           \_ /usr/libexec/netdata/plugins.d/apps.plugin 1
201        93743  0.5  0.0  31892 28728 ?        SNl  13:57   0:01  |           \_ /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
```

```cmd
[ilyam@ilyam-pc ~]$ docker exec -it netdata ps faxu | grep "[n]etdata"
    1 netdata   0:12 /usr/sbin/netdata -u netdata -D -s /host -p 19999 -W set w
  144 netdata   0:00 /usr/libexec/netdata/plugins.d/go.d.plugin 1
  153 root      0:03 /usr/libexec/netdata/plugins.d/apps.plugin 1
  186 netdata   0:01 /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.pl
```

**Comment by JonAnder83** [comment]
```
sudo ps faxu | grep "[n]etdata"
201      32706 12.0  4.9 108900 47256 ?        SNsl 12:54   2:12  |       \_ /usr/sbin/netdata -u netdata -D -s /host -p 19999 -W set web web files group root -W set web web files owner root
201      32757  0.2  0.1  14800  1904 ?        SNl  12:54   0:02  |       |   \_ /usr/sbin/netdata --special-spawn-server
201        632  0.1  1.4 813400 13640 ?        SNl  12:54   0:01  |       |   \_ /usr/libexec/netdata/plugins.d/go.d.plugin 1
root       690  4.7  0.2   5036  2652 ?        SN   12:54   0:51  |       |   \_ /usr/libexec/netdata/plugins.d/apps.plugin 1
201        691  0.6  1.9  23976 18360 ?        SNl  12:54   0:06  |       |   \_ /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
```

I run the image based on this yml file I tailored:

```
version: "3"
#docker-compose -f docker-compose.netdata.yml up -d
services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: olisar # set to fqdn of host
    restart: always
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - var_lib:/var/lib/netdata

volumes:
  var_lib:
```

The zombie process seems to come and go. I've noticed it because I'm collecting stats with grafana.
At first, some days ago, I thought it was just something normal, but after seeing it oftenly, I've decided to look into it, now that the weekend allows me to dig deeper in this kind of stuff.

Thanks!
