### ISSUE TITLE
Netdata install failure on OMV5 on Raspberyy-Pi4

### ISSUE THREAD

**Issue by Copaxy** [netdata/netdata#9344]
##### Question summary
Hello, 
it is my first time using github and i never did a issue before but i hope i do nothing wrong. 

 I think my issue is so easy for you and the pros probbably rolling their eyes but still please help me 😅
I have a failure while installing netdata on OMV5 on my Raspberry-Pi 4 with portainer. 
Because i am just learning doing stuff with dockers i searched for a tutorial but all tutorials i found were for old versions and gave me errors or didn't work. I tried to do a own container but it failed.  
So i tried this code for a Stack in portainer from someone else: 

```
version: '2'
services:
  netdata:
    image: netdata/netdata
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

```

But i get this error: 
 
![image](https://user-images.githubusercontent.com/66993806/84750485-a0382280-afbb-11ea-821f-850c978e2b3e.png)

(I hope the picture works) 

Deployment error, Error response from daemon: Get https://registry-1.docker.io/v2/:dial tcp: lookup registry-1.docker.io on [::1]:53:read udp [::1]:53464->[::1]:53: read: connection refused

what does that mean, What do i wrong? and can you recommend me a good tutorial or guide for learning to do stuff in portainer which is up to date?

I am a newbi, i just two days ago got into docker and portainer, so sorry for stupidy
