### ISSUE TITLE
k8s cluster (control-plane) monitoring

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#9366]
##### Feature idea summary

These are [k8s cluster control-plane services](https://kubernetes.io/docs/reference/command-line-tools-reference/) that exposes metrics.

In addition there are bunch of addons, i assume most of them expose metrics too:

> https://github.com/kubernetes/kubernetes/tree/master/cluster/addons

---

Picture (simple setup, can be not like that):

<img width="655" alt="Screenshot 2020-06-18 at 10 29 19" src="https://user-images.githubusercontent.com/22274335/84998068-0659ac80-b158-11ea-97cd-ee65e21eb98f.png">

---

Data based on minikube/gke. Likely should be adjusted.

**Most of the control-plane components are not accesible in cloud env** (which totally makes sense).

# [`kube-scheduler`](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/)

```yaml
name: kube-scheduler
image: k8s.gcr.io/kube-scheduler:v1.17.3
metrics:
  endpoint: 10251/metrics
  info:
    - pod doesnt expose any ports.
    - controlled by `--address`. Default 0.0.0.0. 
    - controlled by `--port`. HTTP, DEPRECATED. Default 10251. (pod.spec.containers.command)
    - controlled by `--secure-port`. HTTPS, authentication + authorization. Default 10259. (pod.spec.containers.command)
```

# [`kube-controller-manager`](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/)

```yaml
name: kube-controller-manager
image: k8s.gcr.io/kube-controller-manager:v1.17.3
metrics:
  endpoint: 10252/metrics
  info:
    - pod doesnt expose any ports.
    - controlled by `--address`. Default 0.0.0.0. 
    - controlled by `--port`. HTTP, DEPRECATED. Default 10252. (pod.spec.containers.command)
    - controlled by `--secure-port`. HTTPS, authentication + authorization. Default 10257. (pod.spec.containers.command)
```

# [`kube-proxy`](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/)

```yaml
name: kube-proxy
image: k8s.gcr.io/kube-proxy:v1.17.3
metrics:
  endpoint: 10249/metrics
  info:
    - pod doesnt expose any ports.
    - controlled by `--metrics-bind-address`. Default 127.0.0.1:10249.
```

# [`apiserver`](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/)

```yaml
name: kube-apiserver
image: k8s.gcr.io/kube-apiserver:v1.17.3
metrics:
  - endpoint: 8443/metrics
    info:
      - pod doesnt expose any ports.
      - controlled by `--advertise-address` or `--bind-address`. Default host's default interface.
      - controlled by `--secure-port`. Default is `6443`. Set to `8443` in minikube.
      - has built-in proxy, can be used to reach a Node, Pod, or Service (https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#so-many-proxies)
```

# [`coredns`](https://github.com/coredns/coredns)

```yaml
name: coredns
image: k8s.gcr.io/coredns:1.6.5
metrics:
  endpoint: 9153/metrics
  info:
    - pod exposes 9153, name: metrics
    - port set in ConfigMap (prometheus :9153)
```

# [`kube-dns`](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns/kube-dns)

```yaml
- name: kubedns
  image: k8s.gcr.io/k8s-dns-kube-dns-amd64:1.15.4
  metrics:
    endpoint: 10055/metrics
    info:
      - pod exposes 10055, name metrics (it seems it is controlled by env 'PROMETHEUS_PORT')

- name: sidecar
  image: k8s.gcr.io/k8s-dns-sidecar-amd64:1.15.4
  metrics:
    ednpoint: 10054/metrics
```

# [`etcd`](https://kubernetes.io/docs/concepts/overview/components/#etcd)

```yaml
name: etcd
image: k8s.gcr.io/etcd:3.4.3-0
metrics: 
  endpoint: 2381/metrics
  info:
    - pod doesnt expose any ports.
    - controlled by `--listen-metrics-urls`. Default http://127.0.0.1:2381. 
```

# [`kubelet`](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/)

```yaml
# not a container

metrics:
  endpoint: 10255/metrics
  info:
    - accessible via apiserver proxy `/api/v1/nodes/NODE_NAME/proxy/metric`
    - http: controlled by `--read-only-port` (or config param). Default 10255.
    - https: controlled by `--port` (or config param). Default 10250.
```

##### Expected behavior

Collect metrics from:

- [ ] kube-scheduler
- [ ] kube-controller-manager
- [X] kube-proxy
- [ ] kube-apiserver
- [X] coredns
- [ ] kube-dns
- [ ] etcd
- [X] kubelet
