### ISSUE TITLE
Generic Prometheus Collector private/auto mode

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#9470]
### Feature idea summary

Build a generic collector that utilises prometheus metric format for collecting application/micro-service metrics.

Our plan is to have this plugin working ~ [`stats.d plugin`](https://learn.netdata.cloud/docs/agent/collectors/statsd.plugin#statsd-charts).

`stats.d` can visualize statsd collected metrics in 2 ways:
 - `private` charts: each metric gets its own private chart. This is the default and does not require any configuration.
 - `synthetic` charts: can be created, combining multiple metrics, independently of their metric types. For this type of charts, special configuration is required, to define the chart title, type, units, its dimensions, etc.

So prometheus collector will be working like that:
 -  `private` charts: w/o configuration.
 -  `synthetic` charts: w/ configuration.

`private`/`synthetic` terms likely will not be used, but lets stick to them for now.

---

## Private (initial version)

Configuration:
 - endpoint URL [mandatory]
 - some other not mandatory parameters (not defined)

**Note**: it is understandable that is not meaningful/useful in general (could do in some simple cases tho), what it does in fact - just visualizing metrics. However it is better then nothing and could be used before a user has defined `synthetic` charts.

How it works:
- with zero configuration create charts from services that use generic prometheus metric format.
- collect all metrics and store as private charts - one chart per metric.
- use one dimension per time series within the metric.
- two caps: soft cap (10) and hard cap (50) on number of dimensions per chart.
- heuristics to define chart metadata, driven by config file(?):
  - units (see [link](https://prometheus.io/docs/practices/naming/#metric-names))
  - dim algorithm (`_total`)

## Synthetic

Configuration:
 - endpoint URL [mandatory]
 - chart templates [mandatory]

Chart templates (stil wip):
 - use [`PromQL`](https://prometheus.io/docs/prometheus/latest/querying/basics/) to make queries to the local db (one scrape metrics).
 - use query rv instant vector labels as dynamic variables (charts/dimensions).

Some examples:

<details>
<summary>Metrics</summary>

```cmd
# HELP windows_cpu_cstate_seconds_total Time spent in low-power idle state
# TYPE windows_cpu_cstate_seconds_total counter
windows_cpu_cstate_seconds_total{core="0,0",state="c1"} 28905.096248399997
windows_cpu_cstate_seconds_total{core="0,0",state="c2"} 0
windows_cpu_cstate_seconds_total{core="0,0",state="c3"} 0
windows_cpu_cstate_seconds_total{core="0,1",state="c1"} 29243.3328989
windows_cpu_cstate_seconds_total{core="0,1",state="c2"} 0
windows_cpu_cstate_seconds_total{core="0,1",state="c3"} 0
windows_cpu_cstate_seconds_total{core="0,2",state="c1"} 29914.2833381
windows_cpu_cstate_seconds_total{core="0,2",state="c2"} 0
windows_cpu_cstate_seconds_total{core="0,2",state="c3"} 0
windows_cpu_cstate_seconds_total{core="0,3",state="c1"} 29465.377036899998
windows_cpu_cstate_seconds_total{core="0,3",state="c2"} 0
windows_cpu_cstate_seconds_total{core="0,3",state="c3"} 0

# HELP windows_cpu_time_total Time that processor spent in different modes (idle, user, system, ...)
# TYPE windows_cpu_time_total counter
windows_cpu_time_total{core="0,0",mode="dpc"} 3.828125
windows_cpu_time_total{core="0,0",mode="idle"} 28535.546875
windows_cpu_time_total{core="0,0",mode="interrupt"} 22.734375
windows_cpu_time_total{core="0,0",mode="privileged"} 2113.09375
windows_cpu_time_total{core="0,0",mode="user"} 860.296875
windows_cpu_time_total{core="0,1",mode="dpc"} 1.5625
windows_cpu_time_total{core="0,1",mode="idle"} 29413.609375
windows_cpu_time_total{core="0,1",mode="interrupt"} 12.171875
windows_cpu_time_total{core="0,1",mode="privileged"} 943.984375
windows_cpu_time_total{core="0,1",mode="user"} 1151.109375
windows_cpu_time_total{core="0,2",mode="dpc"} 3.328125
windows_cpu_time_total{core="0,2",mode="idle"} 29943.328125
windows_cpu_time_total{core="0,2",mode="interrupt"} 16.84375
windows_cpu_time_total{core="0,2",mode="privileged"} 634.875
windows_cpu_time_total{core="0,2",mode="user"} 930.5
windows_cpu_time_total{core="0,3",mode="dpc"} 49.390625
windows_cpu_time_total{core="0,3",mode="idle"} 29285.5
windows_cpu_time_total{core="0,3",mode="interrupt"} 31.078125
windows_cpu_time_total{core="0,3",mode="privileged"} 1082.90625
windows_cpu_time_total{core="0,3",mode="user"} 1140.296875

# HELP windows_cpu_dpcs_total Total number of received and serviced deferred procedure calls (DPCs)
# TYPE windows_cpu_dpcs_total counter
windows_cpu_dpcs_total{core="0,0"} 305034
windows_cpu_dpcs_total{core="0,1"} 170434
windows_cpu_dpcs_total{core="0,2"} 162396
windows_cpu_dpcs_total{core="0,3"} 213509

# HELP windows_cpu_interrupts_total Total number of received and serviced hardware interrupts
# TYPE windows_cpu_interrupts_total counter
windows_cpu_interrupts_total{core="0,0"} 5.9163056e+07
windows_cpu_interrupts_total{core="0,1"} 1.0966489e+07
windows_cpu_interrupts_total{core="0,2"} 1.1142989e+07
windows_cpu_interrupts_total{core="0,3"} 1.0967361e+07

# HELP windows_cpu_time_total Time that processor spent in different modes (idle, user, system, ...)
# TYPE windows_cpu_time_total counter
windows_cpu_time_total{core="0,0",mode="dpc"} 3.828125
windows_cpu_time_total{core="0,0",mode="idle"} 28535.546875
windows_cpu_time_total{core="0,0",mode="interrupt"} 22.734375
windows_cpu_time_total{core="0,0",mode="privileged"} 2113.09375
windows_cpu_time_total{core="0,0",mode="user"} 860.296875
windows_cpu_time_total{core="0,1",mode="dpc"} 1.5625
windows_cpu_time_total{core="0,1",mode="idle"} 29413.609375
windows_cpu_time_total{core="0,1",mode="interrupt"} 12.171875
windows_cpu_time_total{core="0,1",mode="privileged"} 943.984375
windows_cpu_time_total{core="0,1",mode="user"} 1151.109375
windows_cpu_time_total{core="0,2",mode="dpc"} 3.328125
windows_cpu_time_total{core="0,2",mode="idle"} 29943.328125
windows_cpu_time_total{core="0,2",mode="interrupt"} 16.84375
windows_cpu_time_total{core="0,2",mode="privileged"} 634.875
windows_cpu_time_total{core="0,2",mode="user"} 930.5
windows_cpu_time_total{core="0,3",mode="dpc"} 49.390625
windows_cpu_time_total{core="0,3",mode="idle"} 29285.5
windows_cpu_time_total{core="0,3",mode="interrupt"} 31.078125
windows_cpu_time_total{core="0,3",mode="privileged"} 1082.90625
windows_cpu_time_total{core="0,3",mode="user"} 1140.296875
```

</details>

Templates:

```yml
# Per Core Charts
# You can see by ID - chart per CORE, dimensions - dynamic.

- id: "core_{{core}}_cpu_utilization"
  title: "Core{{core}} CPU Utilization"
  units: "percentage"
  family: "cpu"
  context: "wmi.cpu_utilization"
  type: "stacked"
  dimensions:
    - expr: 'windows_cpu_time_total{mode!="idle"}'
      id: "cpu_core_{{core}}_{{mode}}"
      name: "{{mode}}"
      algorithm: "%incremental"
    - expr: 'windows_cpu_time_total{mode="idle"}'
      id: "cpu_core_{{core}}_{{mode}}"
      name: "{{mode}}"
      algorithm: "%incremental"
      hidden: yes

- id: "core_{{core}}_cpu_state"
  title: "Core{{core}} Time Spent in Low-Power Idle State"
  units: "percentage"
  family: "cpu"
  context: "wmi.cpu_cstate"
  type: "stacked"
  dimensions:
    - expr: "windows_cpu_cstate_seconds_total"
      id: "cpu_core_{{core}}_{{state}}"
      name: "{{state}}"
      algorithm: "%incremental"

# Per Core Dimensions
# You can see by ID - this is one chart, dimensions - dynamic. 

- id: "cpu_dpcs"
  title: "Received and Serviced Deferred Procedure Calls (DPC)"
  units: "dpc/s"
  family: "cpu"
  context: "wmi.cpu_dpcs"
  type: "stacked"
  dimensions:
    - expr: "windows_cpu_dpcs_total"
      id: "cpu_core_{{core}}_dpcs"
      name: "core_{{core}}"
      algorithm: "incremental"

- id: "cpu_interrupts"
  title: "Received and Serviced Hardware Interrupts"
  units: "interrupts/s"
  family: "cpu"
  context: "wmi.cpu_interrupts"
  type: "stacked"
  dimensions:
    - expr: "windows_cpu_interrupts_total"
      id: "cpu_core_{{core}}_interrupts"
      name: "core_{{core}}"
      algorithm: "incremental"

# Summary
# You can see by ID - this is one chart, dimensions - dynamic.

- id: "cpu_utilization_total"
  title: "Total CPU Utilization (all cores)"
  units: "percentage"
  family: "cpu"
  context: "wmi.cpu_utilization_total"
  type: "stacked"
  dimensions:
    - expr: 'sum by (mode) (windows_cpu_time_total{mode!="idle"})'
      id: "cpu_{{mode}}"
      name: "{{mode}}"
      algorithm: "%incremental"
    - expr: 'sum by (mode) (windows_cpu_time_total{mode="idle"})'
      id: "cpu_{{mode}}"
      name: "{{mode}}"
      algorithm: "%incremental"
      hidden: yes

```

##### Expected behavior

Have private mode implemented.
