### ISSUE TITLE
megaRAID not alarming

### ISSUE THREAD

**Issue by tinyhammers** [netdata/netdata#9551]
Hey guys...

Hope you're all keeping safe.
I'm trying to track down an issue I've got with the megaRAID alarm.
I've got a bunch of boxes using megaRAID, and I've got Netdata showing the adapter state, but for some reason isn't triggering an alarm when its degraded.

```
alarm: adapter_state
      on: megacli.adapter_degraded
   units: is degraded
  lookup: sum -10s
   every: 10s
    crit: $this > 0
    info: adapter state
      to: sysadmin
```

My understanding is the above should trigger an alarm if the state is greater than 0. Netdata is reporting the state as 1, but isn't creating an alert for it.

For fun I tried `crit: $this == 1`, but that didn't work either.

Here's my job config, if that helps at all
```
 RAID_check:
     name: RAID_check                           
     update_every: 1        
     priority: 60000        
     penalty: yes           
     autodetection_retry: 0
```
Any idea what it might be, or is there a log I can check?

Thanks :)
