### ISSUE TITLE
Secure OpenTSDB backend does not work with InfluxDb

### ISSUE THREAD

**Issue by den1s2** [netdata/netdata#9631]
##### Bug report summary
When turning on SSL for the opentsdb backend in the latest v23 netdata, a few measurements are created in the corresponding InfluxDB database, but only a few measurement points are written to it. No error messages on either netdata, or influxdb side.

This issue is already reported on GitHub: OpenTSDB and TLS #9068.
A test was performed, but the number of measurements, and the points therein were not checked.

We set up the latest netdata in a Kubernetes cluster with the helm chart provided at https://github.com/netdata/helmchart.
Configured the backend with 

```cmd
[backend]
          enabled = yes
          type = opentsdb:https
          destination = influxdb:4242
          send hosts matching = system. *  
```

We set up the influxdb with the following helm chart: https://influxdata.github.io/helm-charts
Created a self-signed certificate, mounted it, and turned on the opentsdb interface:

```yaml
  opentsdb: 
    enabled : true
    bind-address : ":4242"
    database : "netdata"
    tls-enabled : true
    certificate : "/etc/ssl/keycrt/influxdb.pem" 
```

##### OS / Environment

```cmd
Environment
Kubernetes and OS versions:
Master and Woker node OS: Ubuntu 18.04.4 LTS
kubeadm: v1.18.2
kubectl:
client: v1.18.2
server: v1.18.2
cni:
calico: v3.11
metrics-server: k8s.gcr.io/metrics-server-amd64:v0.3.6 (image)
kubernetes-dashboard: kubernetesui/dashboard:v2.0.0-rc6 (image)
```

##### Netdata version
v23
 

##### Component Name
backend

##### Steps To Reproduce
We set up the latest netdata in a Kubernetes cluster with the helm chart provided at https://github.com/netdata/helmchart.
Configured the backend with 

```cmd
[backend]
          enabled = yes
          type = opentsdb:https
          destination = influxdb:4242
          send hosts matching = system. *  
```

We set up the influxdb with the following helm chart: https://influxdata.github.io/helm-charts
Created a self-signed certificate, mounted it, and turned on the opentsdb interface:

```yaml
  opentsdb: 
    enabled : true
    bind-address : ":4242"
    database : "netdata"
    tls-enabled : true
    certificate : "/etc/ssl/keycrt/influxdb.pem" 
```

##### Expected behavior
All the measurements should be there, being continuously filled with data points. Only a subset of the collected metrics have their respective measurements, and only a few points are stored there, those that are collected right after the start.
