### ISSUE TITLE
How do I use named slaves for mariadb?

### ISSUE THREAD

**Issue by churnd** [netdata/netdata#9632]
##### Question summary
Related to this PR:  https://github.com/netdata/go.d.plugin/pull/404

I see support was added to use `SHOW ALL SLAVES STATUS` for mariadb & the PR was merged to master.  I have the latest version installed on my MariaDB multi-master slave with 4 different named slaves.  I don't see anything showing up out of the box in regard to replication.  Do I need to do some extra configuration?

##### OS / Environment
Debian 10

##### Component Name
mysql

##### Expected results
Replication monitored for all slaves.

**Comment by ilyam8** [comment]
@churnd i need to release new version of `go.d.plugin` (i plan to do it today) and add it to the netdata (see https://github.com/netdata/netdata/pull/9340)

**Comment by ilyam8** [comment]
However you can test it right now:

- build the plugin from source (you need `go` v1.13+)
- replace the one that in the `plugins.d` with it

**Comment by churnd** [comment]
Thanks, I see all the named slaves showing up in netdata now without any changes on my part other than netdata automatically updating, but netdata isn't showing any of their values.  Do I need to set a configuration to allow this?

**Comment by ilyam8** [comment]
I believe `REPLICATION CLIENT` is enough

> https://github.com/netdata/go.d.plugin/tree/master/modules/mysql#requirements

---

I add mariadb test data (`ALL SLAVE STATUS`)

https://github.com/netdata/go.d.plugin/blob/master/modules/mysql/testdata/MariaDBv10.5.4-%5Ball_slaves_status%5D.txt

This is test case

https://github.com/netdata/go.d.plugin/blob/86a93241f56a5cee970a95bdf978d9c6d2931abb/modules/mysql/mysql_test.go#L221-L393

These are metrics

https://github.com/netdata/go.d.plugin/blob/86a93241f56a5cee970a95bdf978d9c6d2931abb/modules/mysql/mysql_test.go#L343-L346

https://github.com/netdata/go.d.plugin/blob/86a93241f56a5cee970a95bdf978d9c6d2931abb/modules/mysql/mysql_test.go#L336-L337

**Comment by ilyam8** [comment]
> but netdata isn't showing any of their values

Share the screenshot

**Comment by churnd** [comment]
![image](https://user-images.githubusercontent.com/683720/90531025-8d6cd600-e143-11ea-9b70-c91de1f2312e.png)

```
churnd@mariadb:~$ pt-show-grants --user=root --ask-pass | grep netdata
Enter password: -- Grants for 'netdata'@'localhost'
GRANT PROCESS, REPLICATION CLIENT ON *.* TO `netdata`@`localhost`;
```

```
churnd@mariadb:~$ sudo -u netdata /usr/libexec/netdata/plugins.d/go.d.plugin -d -m mysql
....
....
BEGIN 'mysql_local.slave_behind_PROD_xxx'
SET 'seconds_behind_master_PROD_xxx' =
END

BEGIN 'mysql_local.slave_thread_running_PROD_xxx'
SET 'slave_sql_running_PROD_xxx' =
SET 'slave_io_running_PROD_xxx' =
END

BEGIN 'mysql_local.slave_behind_PROD_yyyyyy'
SET 'seconds_behind_master_PROD_yyyyyy' =
END

BEGIN 'mysql_local.slave_thread_running_PROD_yyyyyy'
SET 'slave_sql_running_PROD_yyyyyy' =
SET 'slave_io_running_PROD_yyyyyy' =
END

BEGIN 'mysql_local.slave_behind_PROD_zz'
SET 'seconds_behind_master_PROD_zz' =
END

BEGIN 'mysql_local.slave_thread_running_PROD_zz'
SET 'slave_sql_running_PROD_zz' =
SET 'slave_io_running_PROD_zz' =
END
```

```
churnd@mariadb:~$ /usr/sbin/mysqld --version
/usr/sbin/mysqld  Ver 10.4.13-MariaDB-1:10.4.13+maria~buster-log for debian-linux-gnu on x86_64 (mariadb.org binary distribution)
```

```
MariaDB [(none)]> SHOW ALL SLAVES STATUS\G
*************************** 1. row ***************************
               Connection_name: PROD_xxx
               Slave_SQL_State: Slave has read all relay log; waiting for the slave I/O thread to update it
                Slave_IO_State: Waiting for master to send event
                   Master_Host: xxx.example.com
                   Master_User: repl
                   Master_Port: 3306
                 Connect_Retry: 60
               Master_Log_File: mariadb-bin.000730
           Read_Master_Log_Pos: 7402630
                Relay_Log_File: relay-bin-prod_xxx.000325
                 Relay_Log_Pos: 7402927
         Relay_Master_Log_File: mariadb-bin.000730
              Slave_IO_Running: Yes
             Slave_SQL_Running: Yes
               Replicate_Do_DB: xxx
           Replicate_Ignore_DB: mysql
            Replicate_Do_Table:
        Replicate_Ignore_Table:
       Replicate_Wild_Do_Table:
   Replicate_Wild_Ignore_Table:
                    Last_Errno: 0
                    Last_Error:
                  Skip_Counter: 0
           Exec_Master_Log_Pos: 7402630
               Relay_Log_Space: 7403280
               Until_Condition: None
                Until_Log_File:
                 Until_Log_Pos: 0
            Master_SSL_Allowed: No
            Master_SSL_CA_File:
            Master_SSL_CA_Path:
               Master_SSL_Cert:
             Master_SSL_Cipher:
                Master_SSL_Key:
         Seconds_Behind_Master: 0
 Master_SSL_Verify_Server_Cert: No
                 Last_IO_Errno: 0
                 Last_IO_Error:
                Last_SQL_Errno: 0
                Last_SQL_Error:
   Replicate_Ignore_Server_Ids:
              Master_Server_Id: 1
                Master_SSL_Crl:
            Master_SSL_Crlpath:
                    Using_Gtid: No
                   Gtid_IO_Pos:
       Replicate_Do_Domain_Ids:
   Replicate_Ignore_Domain_Ids:
                 Parallel_Mode: conservative
                     SQL_Delay: 0
           SQL_Remaining_Delay: NULL
       Slave_SQL_Running_State: Slave has read all relay log; waiting for the slave I/O thread to update it
              Slave_DDL_Groups: 2
Slave_Non_Transactional_Groups: 0
    Slave_Transactional_Groups: 5545939
          Retried_transactions: 388
            Max_relay_log_size: 1073741824
          Executed_log_entries: 22906204
     Slave_received_heartbeats: 73267
        Slave_heartbeat_period: 30.000
                Gtid_Slave_Pos: 0-1-85195881,10-22-51846121,20-31-214301202
*************************** 2. row ***************************
               Connection_name: PROD_yyyyyy
               Slave_SQL_State: Slave has read all relay log; waiting for the slave I/O thread to update it
                Slave_IO_State: Waiting for master to send event
                   Master_Host: yyyyyy
                   Master_User: user
                   Master_Port: 3306
                 Connect_Retry: 60
               Master_Log_File: yyyyyy-bin.000133
           Read_Master_Log_Pos: 82368795
                Relay_Log_File: relay-bin-prod_yyyyyy.000012
                 Relay_Log_Pos: 82369094
         Relay_Master_Log_File: dbyyyyyy-bin.000133
              Slave_IO_Running: Yes
             Slave_SQL_Running: Yes
               Replicate_Do_DB: db1,db2
           Replicate_Ignore_DB: mysql
            Replicate_Do_Table:
        Replicate_Ignore_Table:
       Replicate_Wild_Do_Table:
   Replicate_Wild_Ignore_Table:
                    Last_Errno: 0
                    Last_Error:
                  Skip_Counter: 0
           Exec_Master_Log_Pos: 82368795
               Relay_Log_Space: 82369844
               Until_Condition: None
                Until_Log_File:
                 Until_Log_Pos: 0
            Master_SSL_Allowed: No
            Master_SSL_CA_File:
            Master_SSL_CA_Path:
               Master_SSL_Cert:
             Master_SSL_Cipher:
                Master_SSL_Key:
         Seconds_Behind_Master: 0
 Master_SSL_Verify_Server_Cert: No
                 Last_IO_Errno: 0
                 Last_IO_Error:
                Last_SQL_Errno: 0
                Last_SQL_Error:
   Replicate_Ignore_Server_Ids:
              Master_Server_Id: 21
                Master_SSL_Crl:
            Master_SSL_Crlpath:
                    Using_Gtid: No
                   Gtid_IO_Pos:
       Replicate_Do_Domain_Ids:
   Replicate_Ignore_Domain_Ids:
                 Parallel_Mode: conservative
                     SQL_Delay: 0
           SQL_Remaining_Delay: NULL
       Slave_SQL_Running_State: Slave has read all relay log; waiting for the slave I/O thread to update it
              Slave_DDL_Groups: 5056
Slave_Non_Transactional_Groups: 0
    Slave_Transactional_Groups: 1144344
          Retried_transactions: 0
            Max_relay_log_size: 1073741824
          Executed_log_entries: 5106562
     Slave_received_heartbeats: 65360
        Slave_heartbeat_period: 30.000
                Gtid_Slave_Pos: 0-1-85195881,10-22-51846121,20-31-214301202
*************************** 3. row ***************************
               Connection_name: PROD_zz
               Slave_SQL_State: Slave has read all relay log; waiting for the slave I/O thread to update it
                Slave_IO_State:
                   Master_Host: zz.example.org
                   Master_User: user
                   Master_Port: 3306
                 Connect_Retry: 60
               Master_Log_File: zz-bin.002887
           Read_Master_Log_Pos: 16418350
                Relay_Log_File: relay-bin-prod_xx.000149
                 Relay_Log_Pos: 3398854
         Relay_Master_Log_File: zz-bin.002887
              Slave_IO_Running: No
             Slave_SQL_Running: Yes
               Replicate_Do_DB: zz
           Replicate_Ignore_DB: mysql
            Replicate_Do_Table:
        Replicate_Ignore_Table:
       Replicate_Wild_Do_Table: zz.table1
   Replicate_Wild_Ignore_Table:
                    Last_Errno: 0
                    Last_Error:
                  Skip_Counter: 0
           Exec_Master_Log_Pos: 16404883
               Relay_Log_Space: 3412628
               Until_Condition: None
                Until_Log_File:
                 Until_Log_Pos: 0
            Master_SSL_Allowed: No
            Master_SSL_CA_File:
            Master_SSL_CA_Path:
               Master_SSL_Cert:
             Master_SSL_Cipher:
                Master_SSL_Key:
         Seconds_Behind_Master: NULL
 Master_SSL_Verify_Server_Cert: No
                 Last_IO_Errno: 1595
                 Last_IO_Error: Relay log write failure: could not queue event from master
                Last_SQL_Errno: 0
                Last_SQL_Error:
   Replicate_Ignore_Server_Ids:
              Master_Server_Id: 31
                Master_SSL_Crl:
            Master_SSL_Crlpath:
                    Using_Gtid: No
                   Gtid_IO_Pos:
       Replicate_Do_Domain_Ids:
   Replicate_Ignore_Domain_Ids:
                 Parallel_Mode: conservative
                     SQL_Delay: 0
           SQL_Remaining_Delay: NULL
       Slave_SQL_Running_State: Slave has read all relay log; waiting for the slave I/O thread to update it
              Slave_DDL_Groups: 111756
Slave_Non_Transactional_Groups: 0
    Slave_Transactional_Groups: 14105085
          Retried_transactions: 0
            Max_relay_log_size: 1073741824
          Executed_log_entries: 66058393
     Slave_received_heartbeats: 19458
        Slave_heartbeat_period: 30.000
                Gtid_Slave_Pos: 0-1-85195881,10-22-51846121,20-31-214301202
```
