### ISSUE TITLE
Unable to get pihole plugin working. 

### ISSUE THREAD

**Issue by modem7** [netdata/netdata#9650]
##### Bug report summary

Netdata installed via autoinstall sh script. 
Fedora
netdata v1.23.2-105-nightly

Followed guide in: https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/modules/pihole

Doesn't show up in Netdata. Attempted troubleshooting steps. Troubleshooting seems to fail however.

Steps I took:
```
$ su -
# su -s /bin/bash netdata
bash-4.4$ ./go.d.plugin -d -m pihole
bash: ./go.d.plugin: Permission denied
```

```
[alex@HDA ~]$ ps faxu | grep "[n]etdata"
netdata   1296  2.0  0.5 507804 183388 ?       Ssl  18:37   0:08 /usr/sbin/netdata -P /var/run/netdata/netdata.pid -D
netdata   1308  0.0  0.0  49484  2580 ?        Sl   18:37   0:00  \_ /usr/sbin/netdata --special-spawn-server
netdata   1811  0.1  0.0  12068  3068 ?        S    18:37   0:00  \_ bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
netdata   1828  0.0  0.0 726408 18688 ?        Sl   18:37   0:00  \_ /usr/libexec/netdata/plugins.d/go.d.plugin 1
netdata   1833  2.1  0.0  55152  9592 ?        S    18:37   0:09  \_ /usr/libexec/netdata/plugins.d/apps.plugin 1
root      1834  1.5  0.0  53868  7556 ?        S    18:37   0:06  \_ /usr/libexec/netdata/plugins.d/freeipmi.plugin 1 ignore 1478
netdata   1835  0.0  0.0  12460  3488 ?        S    18:37   0:00  \_ bash /usr/libexec/netdata/plugins.d/charts.d.plugin 1
root      1838  1.1  0.0 261728  6200 ?        Sl   18:37   0:04  \_ /usr/libexec/netdata/plugins.d/ebpf.plugin 1
netdata   1839  3.4  0.1 293220 52688 ?        Sl   18:37   0:14  \_ /usr/bin/python /usr/libexec/netdata/plugins.d/python.d.plugin 1
netdata   2400  0.8  0.0  17408  6416 ?        S    18:37   0:03      \_ /usr/bin/nvidia-smi -x -q -l 1
netdata  10780  0.0  0.0      0     0 ?        Z    18:44   0:00      \_ [postqueue] <defunct>
```
```

jobs:
#  - name: pihole
#    url: http://127.0.0.1

#  - name: pihole
#    url: http://localhost

  - name: local
    top_clients_entries: 10
    top_items_entries: 10

  - name: remote
    url: http://192.168.0.2 #docker IP for PiHole
    password: LqPfgB6dwd5rMcWHv0oJjuXKrPP+/IZj5OSY7ujje7gadPd27/P/WbD4C+ygNjDF (not real password)
```

Output of http://192.168.0.2/admin/api.php
![image](https://user-images.githubusercontent.com/4349962/89211892-6ac2b500-d5ba-11ea-9204-2b52fd344ae1.png)
