### ISSUE TITLE
Netdata loses track of metrics when host is replaced by a new instance

### ISSUE THREAD

**Issue by gamefundas** [netdata/netdata#9885]
I am using Netdata in Master/slave mode where agents are steaming metrics to a central collector which is eventually stored in InfluxDB backend. Whenever we under go deployments for our applications, all of them hosted in AWS the new instances are launched in a new container with new IP addresses. They continue to use the same host name and I can see the data flowing in to Master, registry updated and the UI shows showing the charts for the new instance. But I also notice that the previous instance metrics recorded against this host name has simply vanished. 

Is there a certain way the registry associates it with only one IP? My memory mode is dbengine. The backend influxdb has the data as well recorded against both the IP's so it just seems like a registry thing. May be I dont have the right configuration.

**Comment by amoss** [comment]
The new instances probably have a fresh machine GUID. Internally we use this as the key to identify the child node that metrics are received from. The host-name is only used for presentation, and the IP address for logging. If no machine GUID is supplied to Netdata when it starts up then a random GUID is chosen, this is probably what is happening when you launch a fresh container.

You can make the machine GUID persistent across containers if you store it on the host and then mount the file inside the container, perhaps a scheme like this (using docker-compose syntax as an example):
```
version: '3.3'
services:
    child:
        image: netdata
        volumes:
            - /home/amoss/mguids/hostXXX-guid:/var/lib/netdata/registry/netdata.public.unique.id:ro
```
